### ISSUE TITLE
Search enhancement: multiline output

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1004]
Output配下の`-M, --multiline Output event field information in multiple rows`の対応。
` ¦ `を改行コードにする。

**Comment by hitenkoku** [comment]
出力を確認してみたのですが、csvの出力ではすでに改行が入っているようでした。
このissueはターミナル出力の方かと思いましたがあっておりますでしょうか？

**Comment by hitenkoku** [comment]
失礼いたしました。Search機能の時の出力に対してのissueであることに気づきました。混乱を避けるために対象のコメントをhiddenにしておきます。

**Comment by itiB** [comment]
このPRをレビューする際に思ったのですがこれはcsvにしたときに改行するのは以下のライナーでやればいいかと思いました。csvでなくなってしまうのでわざわざhayabusaでやる必要があるのか少し疑問なのですがどうでしょうか
```
cat 1004.csv | sed 's/ | /\n/g'
```

**Comment by YamatoSecurity** [comment]
コメント、ありがとうございます。勿論、後で置換処理でできますが、hayabusaでやった方が便利です。(多くのWindowsユーザはsedをインストールしていないし、使い方が分からない人も多いと思います）改行を入れてもCSVじゃなくなることはないと思います。問題なくインポートできます。
