### ISSUE TITLE
Enhance pivot-keywords-list terminal output

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1022]
@kazuminn 
これをお願いできますか？
1. Put spaces here:
Before:
```
583 / 583 [=============================================================] 100.00 %
The following pivot keywords were found:
Target IP Addresses: ( %DestAddress% %DestinationIp% ):
```
After:
```
583 / 583 [=============================================================] 100.00 %

The following pivot keywords were found:

Target IP Addresses: ( %DestAddress% %DestinationIp% ):
```
2. Output the headings (`Target IP Addresses: ( %DestAddress% %DestinationIp% ):`, `Subject Users: ( %SubjectUserName% ):`, etc..) in the same Green color as the hayabusa logo. (No color if `--no-color` is specified)
3. If there are no keywords, the results are just blank. Can you output the message "No keywords found." in red?
4. Can you output in the same order as defined in the `pivot_keywords.txt` file? Now it seems random but would like to determine the order. Any other way to set the order is also fine.
5. Can you move the `pivot_keywords.txt` file path to `rules/config/pivot_keywords.txt`? This is so I can update it in real time. I will create the config file there.

もし来週まで実装が難しいのであれば、無理せずに仰って下さい。次のリリースに入れたいです。

**Comment by kazuminn** [comment]
承知しました！
