### ISSUE TITLE
[bug] Info alert shows up twice in Results Summary

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1031]
**Describe the bug**
When only running one rule, the alert shows up twice in the Results Summary.

**Step to Reproduce**
`hayabusa.exe csv-timeline -d ../hayabusa-sample-evtx -r ../hayabusa-rules/hayabusa/builtin/BitsClient_Op/BitsCli_59_Info_BitsJobCreated.yml`

**Expected behavior**
It should only show once.

**Screenshots**
<img width="433" alt="Screen Shot 2023-05-05 at 9 34 27 AM" src="https://user-images.githubusercontent.com/71482215/236357425-56a9f6f7-2cfa-4379-b1a8-44bb1f772261.png">

**Environment (please complete the following information):**

- OS: mac
- hayabusa version: 2.3.3+

This bug does not occur on 2.3.2 and earlier.

@hitenkoku Can you take a look at this? It started to happen in version 2.3.3

**Comment by YamatoSecurity** [comment]
Additional info: it seems like it is showing the number 1 - 5 alerts twice, instead of 1-10 alerts.
Command: `hayabusa.exe csv-timeline -d ../hayabusa-sample-evtx`
<img width="848" alt="Screen Shot 2023-05-05 at 1 39 24 PM" src="https://user-images.githubusercontent.com/71482215/236378956-1d06d97f-20a8-4120-ab33-91e76d4d3d64.png">

**Comment by hitenkoku** [comment]
Sorry for the delay in replying.

The fix was completed in #1032.
Could you please review it?
