### ISSUE TITLE
Output search results to JSON

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1041]
@hitenkoku Would you be interested in this? (Since you probably know the best about JSON outputting)

`search` command, under `Output`:
`  -J, --JSON-output            Save the search results in JSON format (ex: -J -o results.json)`

All fields get outputted with this command so should be easier than `csv-timeline` because you don't need to parse the `Details` data.

Example:
```
{
    "Timestamp": "2022-08-26T11:35:09.625202Z",
    "Hostname": "hostname",
    "Channel": "Channel",
    "EventID": 10,
    "RecordID": 100,
    "EventTitle": "Event Title",
    "AllFieldInfo": {
        "Field1": "data",
        "Field2": "data"
    }
}
```

Also, would like to change `Hostname` to `Computer` and `EventTitle` to `RuleTitle` to match the same field names as `json-timeline`.

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for your suggestion.

I will be happy to respond. Let me check a few things before I respond

1. is there any possibility to output in JSONL like csv-timeline?　If we want to do JSONL output, would it be okay to add another option to the search command

**Comment by YamatoSecurity** [comment]
Thank you!
That's a good question! Maybe some people will prefer JSONL so indeed let's add that.
```
Output:
  -J, --JSON-output    Save the search results in JSON format (ex: -J -o results.json)
  -L, --JSONL-output   Save the search results in JSONL format (ex: -L -o results.jsonl)
  -M, --multiline      Output event field information in multiple rows
  -o, --output <FILE>  Save the search results in CSV format (ex: search.csv)
```

**Comment by hitenkoku** [comment]
Thanks for your comment.
As for JSON-output, is it correct to think that formatting is done by jq, xq, etc.?

**Comment by YamatoSecurity** [comment]
@hitenkoku Yes, if there are no parse errors with `jq`, then it should be fine.

**Comment by hitenkoku** [comment]
` -M, --multiline      Output event field information in multiple rows `,   Adding this option will cause jq parsing to fail, so it is excluded from this creation.
