### ISSUE TITLE
Enhancement: output which output profile is used

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1055]
It seems to be confusing to new users about what information is being outputted so I want to output to the terminal which profile is being used.

After:
```
Start time: 2023/05/19 04:16

Total event log files: 585
Total file size: 137.2 MB

Loading detections rules. Please wait.

Excluded rules: 30
Noisy rules: 7 (Disabled)

Deprecated rules: 162 (4.53%) (Disabled)
Experimental rules: 1867 (52.15%)
Stable rules: 225 (6.28%)
Test rules: 1488 (41.56%)
Unsupported rules: 43 (1.20%) (Disabled)

Hayabusa rules: 152
Sigma rules: 3428
Total enabled detection rules: 3580

Output profile: standard

Scanning in progress. Please wait.
```

In the HTML report:
Before:
```
Total enabled detection rules: 3580
Saved file: test.csv (17.6 MB)
```
After:
```
Total enabled detection rules: 3580
Output profile: standard
Saved file: test.csv (17.6 MB)
```

Right now, `config/default_profile.yaml` contains the fields to output by default but in order to keep track of what the default profile is, we could create a `config/default_profile.txt` file and just put the name of the default profile (example: `standard`) inside it. @hitenkoku What do you think?

Can I assign you to this since you are most familiar with the output profiles and HTML report?

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you very much. I think that content is fine with me as well.
