### ISSUE TITLE
New feature: `-R, --remove-duplicate-data` in `csv-timeline`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1056]
Right now, when multiple rules alert on the same event, the event data will be outputted multiple times.
Example:
<img width="1675" alt="Screen Shot 2023-05-19 at 6 01 17 AM" src="https://github.com/Yamato-Security/hayabusa/assets/71482215/f3e9afd9-3bfc-4851-aa0c-bfef44195a77">

This increases the file size unnecessarily.
Just in the `csv-timeline` command for now, I would like to add a `-R, --remove-duplicate-data` option under the `Output` group.
In the example above, the field data (`Svc: .....`) would be outputted in the top most row (the `info` rule) but deleted for the other rows. (That is, `Details`, `ExtraFieldInfo` and `AllFieldInfo` would be blank)

**Comment by hitenkoku** [comment]
@YamatoSecurity 

Wouldn't it be confusing if it is blank? For example, "Same as above" or "↑" would be a little easier to read, wouldn't it?

**Comment by YamatoSecurity** [comment]
Indeed, how about adding `DUP` in the duplicate lines for now?
