### ISSUE TITLE
Feature Request: Overwrite existing output files

### ISSUE THREAD

**Issue by joswr1ght** [Yamato-Security/hayabusa#1063]
Hayabusa runs so quickly that I run it frequently on the same data set, often adjusting my command line arguments to add timeline analysis, or to change the severity of alerting. However, Hayabusa will refuse to re-run unless I delete the previous output file. I end up running it like this:

```
rm rmme ; ./hayabusa-2.5.1-mac-intel csv-timeline -d ~/samples -o rmme -T
```

I tried to make my output `/dev/null` but Hayabusa refuses to run since _that file exists_.

Request: Add a feature (ideally a command-line option) to overwrite output files automatically. For CSV and JSON output, this might be `-O output.csv`, but we'd need a similar option for HTML reporting and `-H` is already used.

Alternatively, a `--clobber` general option might be useful, preserving the existing functionality of _no clobber_ with `-o` and `-H`.

**Comment by hitenkoku** [comment]
@joswr1ght Thank you for your suggestion. 
Please wait a moment as we will confirm how this feature should be implemented once among the maintainers.

**Comment by YamatoSecurity** [comment]
@joswr1ght Hey Josh, thank you for the suggestion. Indeed, this would be a useful new feature. 

@hitenkoku 
A `-C, --clobber      Overwrite results files` option under `General Options` would probably be easier to implement then a separate `-O` option? What do you think?
It would be used to ignore the file existence checks for `-o` and `-H` for `csv-timeline`, `json-timeline` and `-o` for `metrics`, `logon-summary`, `search` and `pivot-keywords`.

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you very much. I will try to implement it .
