### ISSUE TITLE
Metrics enhancement: word wrap in cell when event title is long

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1067]
When the event title is very long, it will cause wrapping and break the table.

<img width="1489" alt="Screen Shot 2023-06-01 at 7 28 27 AM" src="https://github.com/Yamato-Security/hayabusa/assets/71482215/afc522f7-e1bd-4bd0-85e9-fe1b8ca64f7b">

Both channel name and event title should be limited to 50 characters and then wrap to the next line after that.

**Comment by hitenkoku** [comment]
merged by #1094
