### ISSUE TITLE
Feature Request: Separate Timeline (-T) Output from --no-summary

### ISSUE THREAD

**Issue by joswr1ght** [Yamato-Security/hayabusa#1077]
Problem: the logic of `--no-summary` and timeline generation with `-T` is counter-intuitive. Further, users can't suppress summary information and obtain access to the timeline summary.

Hayabusa does not display the timeline summary information by default; this output is only available when the user specifies `-T` on the command line. This is perfectly reasonable as a default; the user opts-in if they want timeline information displayed in the output.

When the user wants to reduce the Hayabusa terminal output, they can specify `--no-summary`. However, `--no-summary` also suppresses the timeline `-T` generation. This seems illogical, since if the user doesn't want the timeline they can simply omit `-T`. If the user does specify `-T`, then they are indicating that they want the timeline, regardless of other output display/suppression options.

Feature request: Change the Hayabusa logic to display the timeline if the user specifies `-T`, regardless of whether `--no-summary` is also specified.

**Comment by YamatoSecurity** [comment]
Thanks for the issue. It has already been fixed in https://github.com/Yamato-Security/hayabusa/pull/1074
https://github.com/Yamato-Security/hayabusa/issues/1072

**Comment by joswr1ght** [comment]
Amazing! 🙌
