### ISSUE TITLE
[bug] Non-transportable HTML Output

### ISSUE THREAD

**Issue by joswr1ght** [Yamato-Security/hayabusa#1078]
**Describe the bug**
When generating an HTML report with `csv-timeline` or `json-timeline`, the output HTML file uses `src` and `link` references that assume the HTML file is relative to the Hayabusa source tree. This makes the HTML report non-transportable. Analysts that generate an HTML report in a different file system location (or shares the HTML report with a colleague, for example) will get a broken logo and failed CSS styling.

**Step to Reproduce**

1. Run Hayabusa from a directory outside of the Hayabusa source tree, generating an HTML report:

```
$ ~/bin/hayabusa/hayabusa csv-timeline -d /Users/jwright/Dev/sec504linuxlabfiles/winlogs -o out.csv -T --no-summary -H out.html
```
2. Open HTML report

```
$ open out.html
```

<img width="855" alt="Screenshot 2023-06-02 at 6 58 29 AM" src="https://github.com/Yamato-Security/hayabusa/assets/1318817/ac61b435-5007-4bfb-a819-afad896ebfb2">

**Expected behavior**
HTML report should be independent of other local file system resources to facilitate access from other file system locations, and to facilitate transportability.

**Environment (please complete the following information):**

- OS: Verified on Windows, macOS
- hayabusa version v2.5.1

**Suggestion**

Change any `img src=` references to base64 blobs in the HTML report output. Make CSS inline instead of an external file.

**Comment by YamatoSecurity** [comment]
Thanks for the issue. I was thinking the same thing but didn't have a good idea of how to make it portable so thank you for the suggestion. 
@hitenkoku Is it possible to embed the image with base64 and use inline CSS instead?
