### ISSUE TITLE
Speed up results summary calculation

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1088]
@fukusuket Can I ask you to take a look at this since @hitenkoku has lots of other issues already assigned?
I noticed that the output processing time has increased quite a bit in 2.6.0-dev compared to 2.5.1. (Maybe 5-7 times slower)
I took benchmarks here: https://docs.google.com/spreadsheets/d/1XCEkJHYA5N8b7O2KldGp7q0C7_F1HFnibz7HwI90-s0/edit#gid=0
On large datasets, it takes an hour to output the file but when `--no-summary` is used, the time decreases significantly.
I would like to know:
1. Is it possible to speed the output processing up when `--no-summary` is not used. (the default setting)
2. Is it possible to reduce memory usage after the analysis is finished (when Hayabusa says "Scanning finished. Please wait while the results are being saved."). In the past, memory usage decreased sharply after the scan was finished but now memory usage stays high until Hayabusa exists. This may be necessary though for calculating the results summary statistics but I would like to check. (When I use `--no-summary`, memory usage does not decrease after the scan so it seems like variables may be staying in memory longer than necessary.)

**Comment by hitenkoku** [comment]
I am very sorry that my added code has caused a significant delay......
I will check.

**Comment by YamatoSecurity** [comment]
@hitenkoku No problem! Sorry I didn't catch it earlier.

**Comment by fukusuket** [comment]
@hitenkoku @YamatoSecurity 

Sorry, I haven't actually measured it, but when I looked at the source code, the following commit may be the cause?🤔
This route taken only when the `--no-summary` option is used.
https://github.com/Yamato-Security/hayabusa/commit/46e16d5e2fc54c3b4c88e701fe7f8ebab8b9f6ae#diff-e6c361eb7b576e57173f4e9bce9f7b5c7d68031a3335154fe046417a4cae0fc9R427

The [extract_author_name](https://github.com/Yamato-Security/hayabusa/blob/main/src/afterfact.rs#L1593-L1595
) function causes file IO.
Therefore, I think that file IO occurs for each output of detection records now, and it takes time?🤔

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! I think that is probably the cause as well. I just took benchmarks of the #900 New Feature: ExtraFieldInfo PR and it does not have slow output time so it must be caused from a PR after that was implemented.
