### ISSUE TITLE
better to change  `Metrics results:` output when Search Command finished

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#1096]
https://github.com/Yamato-Security/hayabusa/blob/main/src/main.rs#L36 
`Metrics results:` is displayed when the search command finished, so is it better to change the msg to `Saved file`?

_Originally posted by @fukusuket in https://github.com/Yamato-Security/hayabusa/pull/1093#pullrequestreview-1475992915_

**Comment by YamatoSecurity** [comment]
Do you mean, when saving the file, the `metrics` results should not be shown to the screen?
I think that is better and more consistent with the other commands.

**Comment by fukusuket** [comment]
@YamatoSecurity 

Yes! I think  that the message `Metrics results:` should not be shown when executing `search` command. 
 
When the `search` command is executed with `-J` option, `Metrics results` is displayed on the terminal as follows,
```
fukusuke@fukusukenoAir hayabusa-2.5.1-all-platforms % ./hayabusa search -d ../hayabusa-sample-evtx --keywords mimikatz -J -o o.json -q
Searching...

Start time: 2023/06/13 22:16

Total event log files: 584
Total file size: 138.2 MB

584 / 584 [=========================================================================================================================] 100.00 %

Total findings: 35



Scanning finished. Please wait while the results are being saved.

Metrics results:: o.json (34.3 KB)

Elapsed time: 00:00:01.820
```

But in this case, the `o.json`  is not the result of `metrics` , so I thought `Saved file` would be better. 🤔

**Comment by YamatoSecurity** [comment]
Oh, i see. It is a different isssue from what I was talking about.
Yes, the search command should not say `Metrics results`, it should say `Saved file:`

Also, when saving a file with `metrics` for very large data, we don't want to output the data to screen b/c it will be slow so I want to not output the results to stdout.

**Comment by fukusuket** [comment]
Yes, I’m with you on that :)  we don't want to output the metrics large data to screen.

**Comment by YamatoSecurity** [comment]
@hitenkoku Sorry, I noticed a similar issue of when `-J` is run for JSON input but there are no `.json` files, it gives the error `[ERROR] No .evtx files were found.` but it should say `[ERROR] No .json or .jsonl files were found.`
Can you fix this as well? (we can create a separate issue if needed.)
