### ISSUE TITLE
category filtering

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1119]
Similar to [`--exclude-tags` filtering](https://github.com/Yamato-Security/hayabusa/issues/1118), I want to add filtering for logsource `category` as well to let users only scan for certain categories or ignore certain categories to speed up scanning and reduce memory usage.

Under `Filtering` in `csv-timeline` and `--json-timeline` add the following:
`--include-category <CATEGORY>  Only load rules with certain logsource categories (ex: process_creation,pipe_created)`
`--exclude-category <CATEGORY>  Do not load rules with certain logsource categories (ex: process_creation,pipe_created)`

**Comment by hitenkoku** [comment]
Is this option to search for logsource > category, or is it unnecessary to search for logsource > product? If you need to filter by product, please let me create another option.
