### ISSUE TITLE
`HexToDecimal` field data mapping

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1133]
@fukusuket Could I ask you to do this one since you are now the most familiar with field data mapping?
No hurry, so it can be done in the next release if it will take time.
I added a `HexToDecimal` section in the config files here: https://github.com/Yamato-Security/hayabusa-rules/tree/main/config/data_mapping

Most time it will be just one field: `HexToDecimal: 'ProcessId'`

But sometimes can be multiple (EID: 4688):
```
HexToDecimal:
    - 'NewProcessId'
    - 'ProcessId'
```

Unfortunately most PIDs in Windows events are in hex so would be better to convert to decimal.
HexToDecimal will also be ignored when `-F` is used.
The `ProcessId` fields should probably always exist in the defined EIDs but may not in some circumstances so might want to test that hayabusa does not crash, etc.. if the field does not exist.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for the mention :) Yes, I would love to implement it!💪

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much! Then I will assign you to this one.

**Comment by YamatoSecurity** [comment]
closed by https://github.com/Yamato-Security/hayabusa/pull/1154
