### ISSUE TITLE
Add AND logic to keyword search

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1162]
Now, `-k` in the `search `command does OR logic but I have often found it useful if it could search on multiple terms with AND logic.
So under `Filtering` I want to add a `-a, --and-logic   Search keywords with AND logic. (default: OR)`

argument conflicts with `-r`
requires `-k`

**Comment by hitenkoku** [comment]
@YamatoSecurity I will try Implementation.
Can't I combine and and or, is that a problem?
