### ISSUE TITLE
test threads default value

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#1182]
cpu num vs https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html

**Comment by hitenkoku** [comment]
I implemented thread::available_parallelism in https://github.com/Yamato-Security/hayabusa/tree/test/available-parallelism .

Could you check it whether improve speed or not?

**Comment by YamatoSecurity** [comment]
@hitenkoku I checked the number of threads in my environment but they stay the same. I think this may only change in rare virtualized settings, etc.. but I don't think there is harm in changing this. So can you merge this for 2.9.0?
