### ISSUE TITLE
Enhancement: add ETA to progress bar

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1213]
I removed the ETA from the progress bar because it was highly inaccurate and fluctuate widely decreasing and increasing due to hayabusa calculating based on the number of evtx files it is currently processing instead of the number of total records. This is caused because sometimes file size can be very small for a file or very large. I would still like to keep the progress bar as is where we know the file name of the currently scanned evtx file but want to investigate if it is possible to quickly count the total number of records that need to be analyzed and then calculate the ETA based off that. This would also make the progress bar more accurate as it would update on every record scanned instead of based on files it finished scanning.

**Comment by hitenkoku** [comment]
To create this process, all records must first be read and counted, so the reading process will take a long time. To avoid consuming memory, we need a process that reads and counts only records, but the record reading time depends on hayabusa-evtx, so we will not know how long it will take until we try it. I will try to implement a prototype.

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! I think the number of records are written in the evtx file headers so we just need to read those numbers from the different evtx files, not individually count all records. I am not sure how to call it from the evtx library though.

**Comment by YamatoSecurity** [comment]
I looked up the source code to the Windows API call that counts evtx record events `ElfrNumberOfRecords()` from the ReactOS source code here (https://doxygen.reactos.org/d1/d18/base_2services_2eventlog_2rpc_8c.html#a3ba16da749e6a572e0f80709e16ade53)

`ElfrNumberOfRecords()`:
```
{
    PLOGHANDLE pLogHandle;
    PLOGFILE pLogFile;
    ULONG OldestRecordNumber, CurrentRecordNumber;
 
    DPRINT("ElfrNumberOfRecords()\n");
 
    pLogHandle = ElfGetLogHandleEntryByHandle(LogHandle);
    if (!pLogHandle)
        return STATUS_INVALID_HANDLE;
 
    if (!NumberOfRecords)
        return STATUS_INVALID_PARAMETER;
 
    pLogFile = pLogHandle->LogFile;
 
    /* Lock the log file shared */
    RtlAcquireResourceShared(&pLogFile->Lock, TRUE);
 
    OldestRecordNumber  = ElfGetOldestRecord(&pLogFile->LogFile);
    CurrentRecordNumber = ElfGetCurrentRecord(&pLogFile->LogFile);
 
    /* Unlock the log file */
    RtlReleaseResource(&pLogFile->Lock);
 
    DPRINT("Oldest: %lu  Current: %lu\n",
           OldestRecordNumber, CurrentRecordNumber);
 
    if (OldestRecordNumber == 0)
    {
        /* OldestRecordNumber == 0 when the log is empty */
        *NumberOfRecords = 0;
    }
    else
    {
        /* The log contains events */
        *NumberOfRecords = CurrentRecordNumber - OldestRecordNumber;
    }
 
    return STATUS_SUCCESS;
}
```

 ElfGetOldestRecord():
```
{
    ASSERT(LogFile);
    return LogFile->Header.OldestRecordNumber;
}
```

ElfGetCurrentRecord():
```
{
    ASSERT(LogFile);
    return LogFile->Header.CurrentRecordNumber;
}
```

It looks like they calculate it by subtracting the current record number from the oldest record number which are in the evtx header.
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb309024(v=vs.85)


However, it does not seem that the rust evtx crate is parsing out these two values. We may need to update it?

**Comment by YamatoSecurity** [comment]
Humm.. I looked into this and it seems that it is necessary to iterate through all the records in order to count them. I am going to close this issue for now..
