### ISSUE TITLE
Add MITRE Tactics info to HTML report

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1226]
I received some requests to add more support for MITRE ATT&CK.
When investigating, it is good to know what MITRE tactics and techniques were used according to computer so in the HTML report at the bottom, I would like to add a `MITRE ATT&CK Tactics` list that lists up what tactics where detected for each computer. 

Example:

| Computer  | MITRE ATT&CK Tactics                                           |
|-----------|----------------------------------------------------------------|
| ComputerA | `14. Impact`                                                   |
| ComputerB | `1. Reconnaissance` `3. Initial Access` `8. Credential Access` |
| ComputerC | `7. Defense Evasion`                                           |

Although attackers do not necessarily follow the MITRE ATT&CK tactics in order, I suppose it is better to sort them in order.
* `1. Reconnaissance` 
* `2. Resource Development`
* `3. Initial Access`
* `4. Execution`
* `5. Persistence`
* `6. Privilege Escalation`
* `7. Defense Evasion`
* `8. Credential Access`
* `9. Discovery`
* `10. Lateral Movement`
* `11. Collection`
* `12. C2`
* `13. Exfiltration`
* `14. Impact`

Computers should be sorted so that the tactics with higher numbers go to the top of the list.

@hitenkoku Since you are most familiar with the HTML report, could I ask you to do this one?

**Comment by hitenkoku** [comment]
Thanks for creating issue.

Now, To get MITRETactics Data, %MitreTactics% should exist in using profile.

**Comment by YamatoSecurity** [comment]
@hitenkoku What about the following logic:
If the user specifies a profile with %MitreTactics%, then we output the MITRE tactics. If not, we write in the HTML report an error message saying `You need to specify a profile with %MitreTactics% in order to get a summary of MITRE ATT&CK tactics`?
