### ISSUE TITLE
Output Mitre Tactics and Tags in an array of strings in JSON

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1230]
In the JSON output, MITRE ATT&CK tactics and tags get outputted in an array but they are not an array of strings, but a string inside an array that is separated by the broken pipe symbol. It would be nice to output in an array of strings instead so it is easier to parse.

Now:
```
  "MitreTactics": [
    "Exec ¦ Disc"
  ],
  "MitreTags": [
    "T1482 ¦ T1087 ¦ T1087.001 ¦ T1087.002 ¦ T1069.001 ¦ T1069.002 ¦ T1069 ¦ T1059.001"
  ],
```

@hitenkoku Is this something easy to do? or will it take time?

**Comment by hitenkoku** [comment]
@YamatoSecurity Thanks for your issue.
I will implement it.
