### ISSUE TITLE
Add support for Linux aarch64

### ISSUE THREAD

**Issue by jw4n6** [Yamato-Security/hayabusa#1238]
I was able to compile hayabusa  from source code for Debian 12.4 arm64.
Any plans to include a "hayabusa-*-lin-gnu-arm" version in future releases?

**Comment by YamatoSecurity** [comment]
@jw4n6 Thanks for the suggestion. We will try to start supporting linux and windows arm binaries.

**Comment by YamatoSecurity** [comment]
@jw4n6 I added linux aarch64 binaries
