### ISSUE TITLE
Github action: auto build release packages

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1239]
It would be nice to be able to manually build release packages with github actions for the following architectures:
+ Intel Mac 64 bit (`hayabusa-x.x.x-mac-intel`)
+ Arm Mac 64 bit (`hayabusa-x.x.x-mac-arm`)
+ Intel Win 32 bit (`hayabusa-x.x.x-win-x86.exe`)
+ Intel Win 64 bit (`hayabusa-x.x.x-win-x64.exe`)
+ Arm Win 64 bit (`hayabusa-x.x.x-win-arm.exe`)
+ Intel Linux 64 bit GNU (`hayabusa-x.x.x-lin-intel-gnu`)
+ Intel Linux 64 bit MUSL (`hayabusa-x.x.x-lin-intel-musl`) 
+ Arm Linux 64 bit GNU (`hayabusa-x.x.x-lin-arm-gnu`)
+ Arm Linux 64 bit MUSL (`hayabusa-x.x.x-lin-arm-musl`)

After compiling with `cargo build --release`, I rename `target/release/hayabusa-hogehoge.exe` to the executable names listed above, then run `cargo clean` to delete the unneeded files. I then run the `update-rules` command to get the latest rules and config files.
After that, I delete the following files and directories as they are not needed to run:
+ `.cargo/`
+ `.github/`
+ `doc/`
+ `screenshots/`
+ `src/`
+ `test_files/`
+ `.codecov.yml`
+ `.env.example`
+ `.gitignore`
+ `.gitmodules`
+ `Cargo.lock`
+ `Cargo.toml`
+ `CHANGELOG*`
+ `README*`
+ `logo.png`
+ `LICENSE.txt`

After that we would need to zip up the directory into the following zip files to make available for release:
+ Intel Mac 64 bit (`hayabusa-x.x.x-mac-intel.zip`)
+ Arm Mac 64 bit (`hayabusa-x.x.x-mac-arm.zip`)
+ Intel Win 32 bit (`hayabusa-x.x.x-win-intel-32-bit.zip`)
+ Intel Win 64 bit (`hayabusa-x.x.x-win-intel-64-bit.zip`)
+ Arm Win 64 bit (`hayabusa-x.x.x-win-arm.zip`)
+ Intel Linux 64 bit GNU (`hayabusa-x.x.x-lin-intel-gnu.zip`)
+ Intel Linux 64 bit MUSL (`hayabusa-x.x.x-lin-intel-musl.zip`) 
+ Arm Linux 64 bit GNU (`hayabusa-x.x.x-lin-arm-gnu.zip`)
+ Arm Linux 64 bit MUSL (`hayabusa-x.x.x-lin-arm-musl.zip`)

For embedded Windows builds (meant for live response):
+ Intel Win 32 bit (`hayabusa-x.x.x-win-intel-32-bit-live-response.zip`)
+ Intel Win 64 bit (`hayabusa-x.x.x-win-intel-64-bit-live-response.zip`)
+ Arm Win 64 bit (`hayabusa-x.x.x-win-arm-live-response.zip`)

The `config` and `rules` folders should be deleted as well as the `config` folder files are embedded and the `rules` folder config files and rules are replaced by the following two files:
- https://raw.githubusercontent.com/Yamato-Security/hayabusa-encoded-rules/refs/heads/main/rules_config_files.txt
- https://github.com/Yamato-Security/hayabusa-encoded-rules/raw/refs/heads/main/encoded_rules.yml

These two files need to be placed in the root directory.

**Comment by YamatoSecurity** [comment]
@hitenkoku Do you mind if I re-assign this to @fukusuket ? He has done the auto-build release for Takajo so is familiar with it and also wants to add some integration tests for the live response builds.

**Comment by hitenkoku** [comment]
@YamatoSecurity I am very sorry that I have not been able to work on it.
I do not think I am capable of contributing to your project in the future, so please remove me as a member in group.

I have already been reassigned.
