### ISSUE TITLE
`update-rules` does not update rule files if only `status` field is updated

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1243]
**Describe the issue**
This is not a bug, but `update-rules` does not update rule files when `status` is updated.

According to the Sigma spec below, the `modified` field is not updated when the `status` changes(except `deprecated`).
https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md#modified-optional

The current `update-rules` command is designed to only update files where the `modified` field has been updated, so changes like the commit below will not be reflected in the rules.
https://github.com/SigmaHQ/sigma/pull/4651/files

As a result, the rules classified by the `scan-wizard` below do not match the latest classifications in the Sigma repository
https://github.com/Yamato-Security/hayabusa?tab=readme-ov-file#scan-wizard

**Step to Reproduce**
(As of 2024/1/3)
1. download hayabusa 2.12.0
2. hayabusa update-rules

**Actual behavior**
(As of 2024/1/3)
`Updated Sigma rules: 2`

**Expected behavior**
The `status` field will be updated as in the commit below.
https://github.com/SigmaHQ/sigma/pull/4651/files

Personally, I think the above specifications are better, but what do you think?🤔

**Environment**
- OS: macOS Sonoma version 14.0
- hayabusa version: 2.12.0

**Comment by YamatoSecurity** [comment]
Thanks for pointing this out. Maybe we should update the files if there are any differences in the text (like the `diff` command) instead of checking fields? @hitenkoku What do you think?
