### ISSUE TITLE
Add remote connection path to HTML output

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#1244]
To check easily remote connection, I think better adding network graph  to remote connection path(SSH, WInRM, RDP, URL in Powershell Script) in HTML output.

@YamatoSecurity How about this feature? The crate in Rust did not exist to create images, but it may be possible to add javascript in the HTML to handle this.

**Comment by YamatoSecurity** [comment]
Visualization of lateral movement would be great but I think it could get too messy with JS and HTML output. It would probably be better with Neo4j. Matt Seyer did a youtube video a while ago about visualizing alerts with it: https://www.youtube.com/watch?v=7sQqz2ek-ko

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment.

I got it. I close this issue.
