### ISSUE TITLE
ログファイル未指定の場合にライブ調査する

### ISSUE THREAD

**Issue by itiB** [Yamato-Security/hayabusa#125]
`-f` オプションで調査するログを指定しているがこれがなかった際にWindows のデフォルトで設定されているログファイルのありかを見に行く
`C:¥Windows¥System32¥winevt¥Logs`

**Comment by hitenkoku** [comment]
-Live調査オプションをつけるとそのマシンの direcorty指定 `C:¥Windows¥System32¥winevt¥Logs` を対象とするという仕様
OS確認の処理をつけないといけない(Windows限定/管理者権限をチェック)

**Comment by hitenkoku** [comment]
SYSTEM32の環境変数を確認する

**Comment by hitenkoku** [comment]
確認したところ管理者権限のチェックでは https://crates.io/crates/deelevate/0.1.1 が活用できそう。

**Comment by hitenkoku** [comment]
closed via #398
