### ISSUE TITLE
Remove new line characters in search output

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1253]
When outputting in the `search` output, the screen will be filled with return characters in some logs:
<img width="1250" alt="Screenshot 2024-01-20 at 08 22 30" src="https://github.com/Yamato-Security/hayabusa/assets/71482215/22cd280f-40ef-4645-b243-0bb04abd1690">
For standard output and when writing to a file, it would be easier to read if all of these return characters would be replaced by a single space like Hayabusa does in the CSV timeline.
@hitenkoku Since you know how to do this, could you look at this when you have time?

You can use the following command to test: `./target/release/hayabusa search -d ../hayabusa-sample-evtx -r ".*" -F EventID:"5145"`

**Comment by hitenkoku** [comment]
Thanks for issue.
I will fix it.
