### ISSUE TITLE
Low memory mode option

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1254]
Under `General Options`, I want to add an `-L, --low-memory-mode` option in `csv-timeline` and `json-timeline`. When enabled, Hayabusa will free memory after detecting and outputting data (either standard output or saving to a file). The downside is that results will not be sorted and it will not be possible to count statistics.

**Comment by YamatoSecurity** [comment]
If possible, it would be nice to also support this for the `search` command as well or at least plan for future support. If the code is completely separate, then we can support this in the `search` command later in a different issue.

**Comment by fukusuket** [comment]
@YamatoSecurity @hitenkoku 
It is expected that there will be a large number of changes ... 😇
I think changing it all at once will cause a regression, so I'll create several PRs for small refactoring (to make it easier to handle Channels) before starting implementation.

**Comment by YamatoSecurity** [comment]
@fukusuket Ok, in that case several small refactoring PRs does sound better. Slow and steady wins the race. :slightly_smiling_face:

**Comment by fukusuket** [comment]
### Design(draft) memo
#### Background
When using Hayabusa as an agent such as Velociraptor, the load average is too high, so we want to reduce memory usage.

#### Purpose
Write detection results to Channel (in parallel with Read) to reduce memory usage.

#### Target of change
- [main.rs](https://github.com/Yamato-Security/hayabusa/blob/main/src/main.rs)
- [afterfact.rs](https://github.com/Yamato-Security/hayabusa/blob/main/src/afterfact.rs)
- [detections/config.rs](https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/configs.rs)
- [detections/detection.rs](https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/detection.rs)
- [detections/message.rs](https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/message.rs)

#### What to change
- When in low-memory-mode, use `Channel` to store detection results
  - Create a Channel(`ch`) in `main`
  - Start a thread from `main`
    - Write detection results to `ch` in parallel with analysis_file 
    - When all analysis threads are finished, send a  `finish flag` to `ch`    
  - Check the results stored in `ch` in `main` (using a while loop) write them out each time
    - Processing ends when the `finish flag` is found in `ch`

#### Sequence
![memo](https://github.com/Yamato-Security/hayabusa/assets/41001169/8e342982-e11c-41ac-b235-e2bfcc93e0e1)

#### Restrictions
It will probably be a limited function such as:
- not sorted
- not counted

**Comment by YamatoSecurity** [comment]
@hach1yon As we talked about a little bit in the meeting, could you explain what you think might be an easier or more efficient way to do this? (Ideally it would be nice to still support `count`)

**Comment by YamatoSecurity** [comment]
By the way, I was thinking about the progress bar. When outputting to standard output, it does not make sense to have a progress bar and we should just output the results to the screen as soon as something is detected. However, when `-o` is specified we should still keep the progress bar and just save results to a file as soon as something is detected.

**Comment by YamatoSecurity** [comment]
I talked with @fukusuket and we think it would be easier if @hach1yon implements this, if you are interested in this.

**Comment by hach1yon** [comment]
> I talked with @fukusuket and we think it would be easier if @hach1yon implements this, if you are interested in this.

Okay, I'll work on this issue after #787 .

**Comment by hach1yon** [comment]
@YamatoSecurity @hitenkoku 
I have a few questions about the current source code before I proceed with implementing the low memory mode option. Since the code is somewhat complex, I'd like to ensure my understanding is accurate.

**Comment by YamatoSecurity** [comment]
@hach1yon Sounds good. Let's talk about this on Thursday night at the meeting. @fukusuket has some suggestions too.
One thing that I think might lower some memory would be to not store statistic information when `--no-summary` is used. From my understanding, it is not possible at the moment because that info is stored in DetectInfo so refactoring is needed in order to separate them.

**Comment by hach1yon** [comment]
> @hach1yon Sounds good. Let's talk about this on Thursday night at the meeting. @fukusuket has some suggestions too. One thing that I think might lower some memory would be to not store statistic information when `--no-summary` is used. From my understanding, it is not possible at the moment because that info is stored in DetectInfo so refactoring is needed in order to separate them.

Thanks. I'll check the source code before the next meeting.

**Comment by fukusuket** [comment]
My suggestions is ...(It may be easier said than done, but...😇)  whether it is possible to reduce the number of fields that DetectInfo (= detection result) has? When I was previously investigating performance, DetectInfo's field reduction had the following effects:
https://github.com/Yamato-Security/hayabusa/blob/main/doc/RustPerformance-Japanese.md#%E5%AF%BF%E5%91%BD%E3%81%AE%E9%95%B7%E3%81%84%E6%A7%8B%E9%80%A0%E4%BD%93%E3%81%AE%E4%B8%8D%E8%A6%81%E3%81%AA%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%82%92%E5%89%8A%E9%99%A4%E3%81%99%E3%82%8B


I hope we can discuss it at MTG on Thursday night :)
