### ISSUE TITLE
Add back -h, --help option to General Options

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1255]
I think in the past we removed the -h, --help option from General Options because we could check the help menu by specifying no arguments (Example: `hayabusa.exe csv-timeline`). However, with https://github.com/Yamato-Security/hayabusa/issues/1235 , we now check to see if the user specifies one of the required input options (-d, -f or -l), so now we get an error instead of the help screen get displayed. If it is not possible to show the help screen when only typing the subcommand and no options, then I would like to add a `-h, --help show the help menu` option to easily show the help menu instead of having to type `hayabusa.exe help csv-timeline`, etc...)

**Comment by YamatoSecurity** [comment]
Yes, the `help <command>` syntax works but not `<command> -h`.
So:
```
./target/release/hayabusa csv-timeline -h
error: unexpected argument '-h' found

Usage: hayabusa csv-timeline [OPTIONS] <--directory <DIR>|--file <FILE>|--live-analysis>
```

Adding a `-h` to get the help menu is much more convenient than having to delete all the options and scroll back and add `help`. It is now a bit cumbersome when I need to constantly look up the help menu.

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thanks for your comment. I got it. I will fix it.
