### ISSUE TITLE
`--no-color` not working for progress bar and scan wizard

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1256]
When `--no-color` is specified, the progress bar and scan wizard are still displayed in color:

<img width="811" alt="Screenshot 2024-01-24 at 07 21 10" src="https://github.com/Yamato-Security/hayabusa/assets/71482215/9a3f9b47-791c-4d0a-89c3-22ddb49e992c">
<img width="719" alt="Screenshot 2024-01-24 at 07 20 33" src="https://github.com/Yamato-Security/hayabusa/assets/71482215/d2c14b39-0dcb-41b2-a917-87f8bf4737c0">

**Comment by hitenkoku** [comment]
@YamatoSecurity  thanks for your issue.
I will check it. it's output is outputted via other crate. So may not be fix.

**Comment by YamatoSecurity** [comment]
@hitenkoku I see. If it is not possible to output without color using the crate then no problem. If that is the case, what about creating an issue in the crate's project to ask if they can support an option to not use color?
