### ISSUE TITLE
not to use replacen() in ConditionCompiler.tokenize() function 

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#1277]
This issue is a sub issue of #787 .

ConditionCompiler.tokenize() function utilizes replacen() in the while loop. A new string instance would be created in hhe function replacen() so we can reduce memory usage if we replace replacen() with something.

ConditionCompiler.tokenize() use replacen() in order to memorize how far the tokenization has progressed. I think this can be replaced with index access.

**Comment by YamatoSecurity** [comment]
@fukusuket is interested in this issue so I have assigned him.
