### ISSUE TITLE
Allow `-d` to be specified multiple times

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1335]
In relation to this issue: https://github.com/Yamato-Security/hayabusa/issues/1299 it would be nice the user could specify multiple directories to scan with `-d` so that they can specify directories in volume shadow copies and then remove any duplicate entries for live investigations.
@fukusuket Would you be interested in this?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for mention :) Yes! I would love to implement it💪
