### ISSUE TITLE
Display `Data` fields in indexed string

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1371]
@fukusuket Sorry I think this is going to be a difficult issue, but I think you will like it. 😉 Please let me know if you are interested in implementing it.

Right now, all of the unnamed `Data` fields get outputted as the same `Data` so first it is hard to tell which position they are in without looking up the original XML data in Event Viewer, etc... Second, using arrays will cause problems when importing into Elastic and maybe other SIEMs. Third, the position will change depending on whether fields are defined in `Details` or not, making extraction difficult as the index number may change suddenly.

To fix these problems, I want to output the `Data` fields like they are used for when extracting data.

For example: `./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r rules/hayabusa/builtin/System/Sys_6009_Info_ComputerStartup.yml`

This rule uses `details: 'MajorVer: %Data[1]% ¦ BuildNum: %Data[2]%'` so only will get data from the first and second fields.
However, there is more data:
```
        <EventData>
            <Data>10.00.</Data>
            <Data>19044</Data>
            <Data />
            <Data>Multiprocessor Free</Data>
            <Data>0</Data>
        </EventData>
```

Right now, the output looks like this:
```
2016-09-20 22:07:41.000 +09:00 · Computer Startup · info · IE10Win7 · Sys · 6009 · 8273 · MajorVer: 6.01. ¦ BuildNum: 7601 · Data: 17514 ¦ Data: Multiprocessor Free ¦ Data: Service Pack 1
```
But I want to change it to:
```
2016-09-20 22:07:41.000 +09:00 · Computer Startup · info · IE10Win7 · Sys · 6009 · 8273 · MajorVer: 6.01. ¦ BuildNum: 7601 · Data[3]: 17514 ¦ Data[4]: Multiprocessor Free ¦ Data[5]: Service Pack 1
```

For JSON timelines (Example: `./target/release/hayabusa json-timeline -d ../hayabusa-sample-evtx -w -r rules/hayabusa/builtin/System/Sys_6009_Info_ComputerStartup.yml`)

Before:
```
{
    "Timestamp": "2016-09-20 22:07:41.000 +09:00",
    "RuleTitle": "Computer Startup",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 6009,
    "RecordID": 8273,
    "Details": {
        "MajorVer": "6.01.",
        "BuildNum": 7601
    },
    "ExtraFieldInfo": {
        "Data": ["17514", "Multiprocessor Free", "Service Pack 1"]
    }
}
```

After:
```
{
    "Timestamp": "2016-09-20 22:07:41.000 +09:00",
    "RuleTitle": "Computer Startup",
    "Level": "info",
    "Computer": "IE10Win7",
    "Channel": "Sys",
    "EventID": 6009,
    "RecordID": 8273,
    "Details": {
        "MajorVer": "6.01.",
        "BuildNum": 7601
    },
    "ExtraFieldInfo": {
        "Data[3]": "17514", 
        "Data[4]": "Multiprocessor Free", 
        "Data[5]": "Service Pack 1"
    }
}
```

What do you think?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Yes I like this :) www 
I would love to implement it💪

Depending on the difficulty of implementation, I may create separate pull requests for csv and json!

**Comment by fukusuket** [comment]
## Current impl memo:
### Related Struct
- [options/profile.rs#Profile](https://github.com/Yamato-Security/hayabusa/blob/v2.16.0/src/options/profile.rs#L21)
- [detections/detections#EvtxRecordInfo.rs](https://github.com/Yamato-Security/hayabusa/blob/efaca57e93c6e298a3f2afcd9dbbad93e545dff8/src/detections/detection.rs#L45-L51)
- [detections/message.rs#DetectInfo](https://github.com/Yamato-Security/hayabusa/blob/efaca57e93c6e298a3f2afcd9dbbad93e545dff8/src/detections/message.rs#L33-L44)

### Related Sequence
- TODO
