### ISSUE TITLE
Dynamically create a table of supported field modifiers

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1406]
@fukusuket Could I ask you to do this one?
I would like a markdown table of all of the field modifiers used in Sigma rules ranked by usage and an indicator of whether Hayabusa supports it or not.

So in a daily github action, we download the upstream sigma rules and check the different field modifiers and output the following table to `/docs/SupportedSigmaFieldModifiers.md`

| Count | Field Modifier  | Hayabusa Support |
|-------|-----------------|------------------|
| 100   | \|contains      | Yes              |
| 50    | \|contains\|all | Yes              |
| 30    | \|all           | Yes              |
| 20    | \|re            | Yes              |
| 10    | \|newmodifier   | No               |

This will be useful to check if any new modifiers are being used that Hayabusa does not support and also when learning how to write Sigma rules it is good to know which modifiers are most common, etc...

**Comment by fukusuket** [comment]
Sounds good! Yes, I would love to implement it!💪

**Comment by hitenkoku** [comment]
FYI: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html
