### ISSUE TITLE
[bug] musl packages created by Release Automation failed with `/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.38 not found`

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1431]
https://github.com/Yamato-Security/hayabusa/pull/1430#issuecomment-2403610756

**Comment by YamatoSecurity** [comment]
Humm, this is weird. MUSL binaries should not be using GLIBC so it looks like it is not being correctly compiled to MUSL

**Comment by fukusuket** [comment]
I see... it still doesn't seem to compile to the expected binary... :(

I am compiling with `x86_64-unknown-linux-musl` specified below, but this does not seem to be working. I will try it on my local Ubuntu!
- https://github.com/dtolnay/rust-toolchain?tab=readme-ov-file#inputs
- https://github.com/Yamato-Security/hayabusa/blob/main/.github/workflows/release.yml#L47
- https://doc.rust-lang.org/rustc/platform-support.html#tier-2-with-host-tools

The following issues could have the same cause ... 🤔
- https://github.com/Yamato-Security/hayabusa/issues/1332

**Comment by fukusuket** [comment]
I was able to create musl binaries in local, so it may be an actions issue ...

### Ubuntu 22.04 LTS local build

```
$ rustup target add x86_64-unknown-linux-musl
$ cargo build --target=x86_64-unknown-linux-musl --release
$ ldd hayabusa
	statically linked
```

### Ubuntu 22.04 LTS Actions build
```
 $ ldd hayabusa-2.18.0-lin-intel-x64-musl
./hayabusa-2.18.0-lin-intel-x64-musl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by ./hayabusa-2.18.0-lin-intel-x64-musl)
./hayabusa-2.18.0-lin-intel-x64-musl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./hayabusa-2.18.0-lin-intel-x64-musl)
	linux-vdso.so.1 (0x00007ffd052c9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007faae5a0a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faae59ea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faae5903000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faae56da000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faae68ab000)
```
