### ISSUE TITLE
Implement `utf16/utf16be/utf16le/wide` modifiers

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1432]
Although not used in any rules yet, we would like to support the following modifiers for sigma support completeness:

- `utf16|base64offset|contains`
- `utf16be|base64offset|contains`
- `utf16le|base64offset|contains`
- `wide|base64offset|contains`

Probably no need to support as `base64offset` is usually used instead of `base64`:
- `utf16|base64|contains`
- `utf16be|base64|contains`
- `utf16le|base64|contains`
- `wide|base64|contains`

Example:
```
detection:
  selection:
    CommandLine|wide|base64offset|contains: "ping"
```

Info: https://sigmahq.io/docs/basics/modifiers.html#wide

Prepends a byte order mark and encodes UTF16, (only used in combination with base64 modifiers)

Don't end with utf16, utf16le, utf16be or wide

The value modifier chain must not end with character set encoding modifiers (utf16, utf16le, utf16be and wide). The resulting values are internally represented as byte sequences instead of text strings and contain null characters which are usually difficult to handle in queries. Therefore the should be followed by an encoding modifier (base64, base64offset)

I think we should implement `utf16` to check both `utf16be` and `utf16le` variants.
`wide` should be an alias for `utf16le` in Windows.

We should probably investigate if these encodings are being used inside base64 encoded payloads to begin with. If not, then it probably is not worth implementing.

**Comment by hitenkoku** [comment]
> The value modifier chain must not end with character set encoding modifiers (utf16, utf16le, utf16be and wide). The resulting values are internally represented as byte sequences instead of text strings and contain null characters which are usually difficult to handle in queries. Therefore the should be followed by an encoding modifier (base64, base64offset)
> Usually it doesn't makes sense to combine the re type modifier with any other modifier.
> 

https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks for the information! I was mistaken on how it was being used. I updated the specifications.

**Comment by fukusuket** [comment]
### memo:
```
jq 'select((.EventID == 1 and .Channel == "Sysmon") or (.EventID == 4688 and .Channel == "Security")) | .Details.Cmdline' timeline.json | sort | uniq
```

**Comment by fukusuket** [comment]
First of all, I'll create a simple checking tool!💪 (I'm still not certain if this can be easily checked)

**Comment by fukusuket** [comment]
@YamatoSecurity 
I created simple check tool for records matching the following conditions!
- https://github.com/fukusuket/base64-check
```Rust
            if ch == "Security" && id == 4688 {
                value = data["Event"]["EventData"]["CommandLine"].clone();
            }
            if ch == "Microsoft-Windows-Sysmon/Operational" && id == 1 {
                value = data["Event"]["EventData"]["CommandLine"].clone();
            }
            if ch == "Microsoft-Windows-PowerShell/Operational" && id == 4103 {
                value = data["Event"]["EventData"]["Payload"].clone();
            }
            if ch == "Microsoft-Windows-PowerShell/Operational" && id == 4104 {
                value = data["Event"]["EventData"]["ScriptBlockText"].clone();
            }
```

According to the results of the tool execution, in `hayabusa-sample-evtx`, the following three files seem to contain base64 data to be decoded into UTF-16 LE strings🤔 (There does not appear to be any UTF-16 BE data in `hayabusa-sample-evtx`)
```
Possible Base64 + UTF-16 LE(powersploit-security.evtx): ...
Possible Base64 + UTF-16 LE(many-events-security.evtx): ...
Possible Base64 + UTF-16 LE(discovery_sysmon_1_iis_pwd_and_config_discovery_appcmd.evtx): ...
```

**Comment by YamatoSecurity** [comment]
@fukusuket I checked and found all three types in my logs, including Possible Base64 + UTF-16 BE (although most is either UTF-8 and UTF-16LE). So we should probably support each type. Can you do this one?

**Comment by fukusuket** [comment]
Interesting! Yes, I would love to implement it!💪
