### ISSUE TITLE
Create `fieldref|endswith` alias for `endswithfield`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1435]
@fukusuket Sorry, could I ask you to do this one?
In the latest sigma specification, `|fieldref` is now an alias to `|equalsfield` and in the future we will deprecate `equalsfield` and use the official sigma modifier. I want to create `|fieldref|endswith` as an alias to the current `|endswithfield` modifier as that is more in line with the official sigma specification. In the future we can deprecate `|endswithfield` and use `|fieldref|endswith` instead.

**Comment by fukusuket** [comment]
Yes, I would love to implement it!💪

**Comment by YamatoSecurity** [comment]
Thanks so much!
