### ISSUE TITLE
Support `fieldref|startswith` and `fieldref|contains`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1439]
In the Sigma discord channel, other users are reporting that they want to write rules with `|fieldref|startswith` and `|fieldref|contains` so we might as well start supporting it in v2.18.0.
@fukusuket Since you did that `endswith` version, could I ask you to support these as well?

**Comment by fukusuket** [comment]
Sounds good! Yes, I would love to implement it!💪
