### ISSUE TITLE
Field information is not outputted when the profile is `all-field-info`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1450]
@fukusuket Sorry for the many issues! I noticed there is a bug in both the correlation rules and the old `count` aggregation rules.
When using the `all-field-info` and `all-field-info-verbose` profiles which use the original field names, the field information does not get outputted.

Example:
```
./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r ../hayabusa-rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml
```
gives the output:
```
2016-09-20 01:50:06.513 +09:00 · PW Guessing · med · DESKTOP-M5SN04R · Sec · 4625 · - · Count: 3558 ¦ TargetUserName: Administrator ¦ TargetDomainName: . ¦ IpAddress: 192.168.198.149 ¦ LogonType: 3 ¦ ProcessName: - ¦ LogonProcessName: NtLmSsp · -
```

However,
```
./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -r ../hayabusa-rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml -p all-field-info
```

gives:
```
2016-09-20 01:50:06.513 +09:00 · PW Guessing · med · DESKTOP-M5SN04R · Sec · 4625 · - · - · Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml · ../hayabusa-sample-evtx/DeepBlueCLI/smb-password-guessing-security.evtx
```

Same thing happens when using the `../hayabusa-rules/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt_Deprecated.yml` rule.

I would like to output the same regardless of what profile is being used. 
These are the original field names and no name conversion is done so they are expected when `all-field-info` profiles are used. 
In the future, I want to rename the fields like we do in `details`, etc.. but that will take some planning.
(See issue: https://github.com/Yamato-Security/hayabusa/issues/1445)

**Comment by fukusuket** [comment]
I see, it seems to be an omission in the implementation...😇 I'll fix it!💪
