### ISSUE TITLE
Call hayabusa from other programming  languages?

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#148]
# 概要
* hayabusaの実装を活かしたまま、今までよりカスタマイズしやすくするための開発。
* Rustは実装が大変なので他の言語でカスタマイズできるようにする。

# やること
* 何をカスタマイズできるようにするか仕様を決める
    * ルールかな?
* どんな言語でカスタマイズできるにするか考える。
    * Golangは早いし、文法も簡単で良さそう
        * https://qiita.com/momotaro98/items/92e39e214b0e92f454a7
    * pythonはちょっと遅いけど、セキュリティエンジニアは大体使える言語なので良さそう。
        * https://thinkami.hatenablog.com/entry/2020/08/16/201426

# 注意点
* 可能ならプラットフォーム(Windows/Linux/Mac)に依存しない方法にしたい。
* hayabusaの利点の一つは速度なので、その速度は落とさないようにしたい。
* https://blog.alprosys.com/2020/08/30/rust-script-binders-exercise/

**Comment by hitenkoku** [comment]
ルール作成状況に応じて必要であれば対応する

**Comment by YamatoSecurity** [comment]
There does not seem to be a need for this for now so I will close this issue for now.
We can reopen if we want to implement it.
