### ISSUE TITLE
Add opening and closing messages

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1492]
For all commands, I want to add a random opening message picked from this file: https://github.com/Yamato-Security/hayabusa-rules/blob/main/config/opening_messages.txt

and display it after the logo and before `Start time:`

Example: 
```
┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Elevating Windows DFIR to new heights~

Start time: 2024/11/13 14:35
```

Also, at the end of each command, I want to add a random message from: https://github.com/Yamato-Security/hayabusa-rules/blob/main/config/closing_messages.txt

Ex:
```
./target/release/hayabusa update-rules

┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
   by Yamato Security

Elevating Windows DFIR to new heights~

Start time: 2024/11/13 14:35


You currently have the latest rules.

日々是好日 - Nichinichi Kore Koujitsu - Everyday is a good day.

$
```

If the `-q, --quiet` option is enabled, then I want to hide these messages. 

These files also should be added to the https://github.com/Yamato-Security/hayabusa-encoded-rules/blob/main/rules_config_files.txt file and loaded from there if this file is present (for live response mode). If there is no `rules_config.txt` file then load it from the normal `rules/config` directory.

@fukusuket could I ask you to do this one?

**Comment by fukusuket** [comment]
Sounds Good! Yes, I would love to implement it!💪
