### ISSUE TITLE
Output error message in red

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1505]
<img width="860" alt="Screenshot 2024-11-24 at 10 22 09" src="https://github.com/user-attachments/assets/ed812e66-80af-45b6-8933-6bdf7aebe55c">

@fukusuket Could I ask you to output the `Errors were generated.` message in red?

**Comment by fukusuket** [comment]
Sounds good! Yes I would love to implement it!💪
