### ISSUE TITLE
Add evtx file size to csv output result of `log-metrics` command

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#1528]
The current implementation of the csv header is as follows. I think it would be useful to add file size to the last column.🤔
```
Filename,Computers,Events,First Timestamp,Last Timestamp,Channels,Providers
```
For example, it would be a good guideline for setting the appropriate log file size for the evtx file after incident response or threat hunting. The Start Timestamp and Last Timestamp on the eventlog will be output in the results of the `log-metrics` command, which can be used as a guide for setting an appropriate log size in the future.

@YamatoSecurity 
What do you think?

**Comment by YamatoSecurity** [comment]
@fukusuket I think that's a good idea!
