### ISSUE TITLE
SIGMAルール更新

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#156]
これもバージョン２で良いと思います。
--sigma-updateオプションでSIGMAレポを更新して、hayabusaルールに変換する。

**Comment by hitenkoku** [comment]
このissueは https://github.com/Yamato-Security/hayabusa-rules/issues/3 でSIGMAルールへの最新化対応をしていく想定なので、hayabusa側にこの機能をつける必要はないと考えています。やったとしてもreadmeでルールの更新方法を記載するくらいで十分かと思っています

**Comment by YamatoSecurity** [comment]
sigmaの自動更新はitiBさんがhayabusa-rulesのgithub actionsで対応してくれています。
--update機能はDさんが機能を実装してくれています。
このissueが２つの他のissueで解決しているため、closeします。
