### ISSUE TITLE
Customize columns with output profiles

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#165]

**Comment by hitenkoku** [comment]
説明文がわからなかったので、質問したいのですが、
`--list-profiles` オプションはprofiles.txtのパスを指定するオプションでデフォルトは`config//profiles.txt`を利用するということであってますか？

**Comment by YamatoSecurity** [comment]
デフォルトプロファイルを変える`--set-default-profile minimal`等とうオプションもあった方が便利かも。
（人・シナリオによって欲しい情報が変わって、毎回プロファイルを設定するのが手間なので）

**Comment by hitenkoku** [comment]
デフォルトのプロファイル情報をオプションで指定して、永続的に持つ（以降の実行でもそのプロファイルを適用する）のでしたら、その情報をどこかのファイルに持っておかないといけないですが、それでもよろしいでしょうか。

**Comment by YamatoSecurity** [comment]
それが良さそうですね。`config/default_profile.txt`で良いと思います。
デフォルトで`default`が書かれていますが、プロファイルを変えると更新されて、次からその別のプロファイルを使うイメージです。
