### ISSUE TITLE
Field data mapping

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#177]
substatusのコードマッピングについて以下の例のように変換をして出力できるようにしてほしい
マッピングはハードコーディングではなくymlなどで対応できるようにしたほうがよい

例：
0XC000005E ->	There are currently no logon servers available to service the logon request.
0xC0000064	-> User logon with misspelled or bad user account
0xC000006A	-> User logon with misspelled or bad password

**Comment by hitenkoku** [comment]
変換の仕様をまず決める必要があり

**Comment by YamatoSecurity** [comment]
@fukusuket Are you interested in implementing this?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for the mention :) Yes, I would love to implement it!💪

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much! Then I will assign you to this issue.

**Comment by YamatoSecurity** [comment]
@fukusuket As we discussed in the last meeting, the field data conversion will most likely cause a slight slowdown so we should add a `-F, --no-field-data-mapping` option under `Output` in the `csv-timeline` and `json-timeline` commands to turn it off just in case a user wants to process as fast as possible.

**Comment by fukusuket** [comment]
Yes! I will implement the -F option!💪

**Comment by hitenkoku** [comment]
@fukusuket  @YamatoSecurity 

The display order of the display is controlled by display_order, which assigns numbers in the order of dictionary expressions of long option.

After checking `-F --no-field-data-mapping`, I think it would be better if you could create the following in OutputOptin.

https://github.com/Yamato-Security/hayabusa/blob/18943650b47d403545a7bb47083afeac15de695c/src/detections/configs.rs#L997-L998

```
    /// Disable field data mapping output
    #[arg(help_heading = Some("Output"), short = 'F', long = "no-field-data-mapping", display_order = 400)]
    pub no_field: bool,

```

**Comment by fukusuket** [comment]
@hitenkoku 
I see, thank you for the information :) I'll implement with display_order above!💪
