### ISSUE TITLE
Change regex engine?

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#191]
SIGMAルールの正規表現とRustの正規表現に違いがあって、パースできないケースがある。というか、Rustの正規表現エンジンはちょっと特殊で細かいルールが普通の正規表現エンジンとちょっと違う。例えば、`\/r`という正規表現はSIGMAルール的にはOKだが、Rustではパースエラーになってしまう。他にも`.*{`という正規表現もSIGMAルール的にはOKだが、Rustではパースエラーになってしまう。

今は小手先の修正で対応しているが、結構怪しい実装になっているので他の正規表現エンジンを使いたい。他の正規表現のクレートを探すか、Rustから他の言語(例えばGolangとか)の正規表現エンジンを呼び出すような実装にしておいた方が無難。

現状での候補
* https://github.com/Project-Dream-Weaver/Python-Regex/tree/main/src
* Golangとかは速度も速いので、RustからGolangを呼び出してその正規表現を使うのもありかも

**Comment by kazuminn** [comment]
#148 でいっぺんにやっちゃう感じになるかな。と思いました。

**Comment by hach1yon** [comment]
ちょっと、どうするのが良いのか話す必要が有りますねー

**Comment by hitenkoku** [comment]
Rustでなければokかもしれないが、基準となるルールがわからない状態

**Comment by YamatoSecurity** [comment]
主なregexエンジンがrustのデフォルトcrate、hyperscan、PCRE2のようです。(参考: https://sr.ht/~pierrenn/ripgrep/)
hyperscanが昔から一番速いので、そちらに変えた方が速くなる可能性があります。
参考: https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/

SigmaがPCRE2を使っている情報は見つからなかったけど、昔から人気な正規表現なので、もしかしてPCRE2を使ったら、より多く検知できるかもしれません。実装してみないとなんともいえませんが。とりあえずhyperscanに変えてみましょう。

@kazuminn さんがやりたいと仰っているので、アサインします。

**Comment by kazuminn** [comment]
ありがとうございます。

現在、sigmaは、ElasticSearchの正規表現だけをサポートしており、それはjavaで実装されており、ライブラリはjava.util.regexのようです。
java.util.regexのexpressionを調べてみると、公式に
```
Perlに似た文字列形式で指定します。
```
と書いてありました。
https://docs.oracle.com/javase/jp/17/docs/api/java.base/java/util/regex/package-summary.html

Perlなので、PCRE2があってるかもしれませんが、perlと"似た"なので、何とも言えません。

とりあえず、hyperscanで実装してみます。

**Comment by YamatoSecurity** [comment]
なるほど、調べてくれてありがとうございます！
コンパイルが少し面倒になりますが、HyperscanのChimera APIを使ったら、PCRE2も使えるみたいですね。
https://crates.io/crates/hyperscan

**Comment by kazuminn** [comment]
hyperscanのPCREを使ったhayabusaをコンパイルできましたが、リンクできませんでした。
git2ライブラリの方にも、PCREが使われており、リンク時に「二個あるのだめ」と怒られます。
どちらかに統一させようとしましたが、方法が提供されておらず、できませんでした。
hyperscanのPCREは、個別でビルドしており、依存関係の考慮に入らないようです。

@YamatoSecurity どうしましょうか？
1. git2を別のに変える（いや、まぁ無理か
2. PCREなしのhyperscanを実装
3. PCRE2

**Comment by YamatoSecurity** [comment]
@kazuminn 
ありがとうございます！
最近のバージョンのPHP等はPCRE2を使っているので、その実装が良さそうですが、Sigmaの運営者に聞いてみました：
[https://github.com/SigmaHQ/sigma-specification/issues/25](https://github.com/SigmaHQ/sigma-specification/issues/25)
返事が返ってきたら、ご連絡します。

**Comment by kazuminn** [comment]
うっ。私も二日前に質問していました。報告漏れてすみません。
https://github.com/SigmaHQ/sigma/discussions/3658

このまま両方残しておいて、レスポンスの遅い方をdeprecatedってことで閉じるのでいいかなとおもいます。

**Comment by YamatoSecurity** [comment]
なるほど、決まっていないっぽいので、返事は少し時間がかかるかもしれません。。（作者によって正規表現の書き方が違う気がします・・）
そうですね。このまま両方を残しておいて、レスポンスを待ちましょう。
PCREとPCRE2は書き方が若干違うみたいです: https://stackoverflow.com/questions/70273084/regex-differences-between-pcre-and-pcre2

こちらで、Python等でルールの正規表現を抽出して、PCREとPCRE2で書き方が正しいかどうかチェックするしかないかもしれません。

**Comment by YamatoSecurity** [comment]
@kazuminn こちらで確認しました。Sigmaルールの正規表現はPCREでもPCRE2でもパースエラーが出ませんでした。
ということで、PCRE2での実装をお願いできますか？

**Comment by kazuminn** [comment]
@YamatoSecurity 承知しました。

**Comment by YamatoSecurity** [comment]
@kazuminn 
sigmaの人から返事が返ってきました。 ( [https://github.com/SigmaHQ/sigma-specification/issues/25#issuecomment-1312845459](https://github.com/SigmaHQ/sigma-specification/issues/25#issuecomment-1312845459) )
やはり、ちゃんと定義されていないようです。正規表現をそのままバックエンドに渡しているので、一番よく使われているPCREの正規表現だったら問題がないはずだけど、高度な正規表現だと、うまくいかない可能性があるので、以下の条件に絞った方が良いんじゃないかな〜？て言っています.

> It's indeed not specified and currently existing conversion logic (pySigma, sigmac) passes it through to the query. I think PCRE is currently most prevalent in most query languages and other software, but usage of advanced features in rules could cause incompatibilities. Therefore I suggest to restrict to a basic subset of features, more specific:

```
    . placeholder
    [a-z] character sets with negation syntax [^...] but no character class syntax like [:...:].
    *, ? and + quantifiers.
    {min,max} repetition syntax.
    Grouping with (...), omitting all modifiers like lookahead/behind etc.
    OR operator | inside of groups.
```

**Comment by YamatoSecurity** [comment]
@kazuminn 
PCREで実装するのは、代わりありません。
条件は気にしなくて良いと思います。Sigmaのドキュメンテーションに書くものなので。
実装が終わったら、「HayabusaはPCRE2を使っています」とHayabusa-rulesのreadmeに書こうと思っています。

**Comment by YamatoSecurity** [comment]
@kazuminn 実装はどこまで進んでいますか？

**Comment by kazuminn** [comment]
@YamatoSecurity 今、一度コンパイルが成功しましたが、テストとclippyが通らない状況です。
思った以上にコンパイルを通すのに、疲れたので、少し作業を休憩していますが、年内リリースの意気込みです。

**Comment by YamatoSecurity** [comment]
@kazuminn ありがとうございます！
了解です。無理しないようにね！年内で大丈夫です。

**Comment by YamatoSecurity** [comment]
@kazuminn まだテストとclippyに失敗しても良いので、コンパイルできる状態だったら、こちらでどのぐらい速くなっているか等検証したいのですが、ドラフトのPRを上げて頂けますか？

**Comment by kazuminn** [comment]
@YamatoSecurity 上げましたー。#821

**Comment by YamatoSecurity** [comment]
参考: hscheckツールでsigmaの正規表現をPCREなしのHyperscanで使えるかどうかチェックできるようです: https://intel.github.io/hyperscan/dev-reference/tools.html

**Comment by YamatoSecurity** [comment]
今更気づいて、申し訳ございませんが、hyperscanはIntelが作っているせいかARMに対応していないようなので、そもそも使えないです。。(MAC M1にも対応したいので・・）

PCRE-JITはMac M1に対応しているかな？(ARM v5, v7, and Thumb2に対応しているようですが）
リンク： https://www.pcre.org/original/doc/html/pcrejit.html

**Comment by YamatoSecurity** [comment]
メモ：
https://github.com/rust-lang/regex/issues/501#issuecomment-1333797955
regexの焼き寿司さんがデフォルトのunicode対応要らないんじゃない？というコメントを頂いたので、なしでコンパイルして比較してみました。
14GBに対して、unicode ONの場合はメモリが14GB、OFFの場合は13.7GBで約300MBメモリが減りました。また、約32分のスキャンが6秒速くなりました。検知数は同様でした。フィールドに日本語を探す場合があって、メモリ使用＋スキャン時間は対して変わらないので、今のままデフォルトのunicode ONの設定にしようと思います。
