### ISSUE TITLE
一つのルールにconditionが複数書いてあるSIGMAルールの対応

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#223]
なんか、ひとつのルールにconditionが複数定義されることがあるらしい。よく見ると仕様書に書いてある。
```If multiple conditions are given, they are logically linked with OR.```

https://github.com/SigmaHQ/sigma/wiki/Specification

**Comment by hitenkoku** [comment]
今後このようなルールが増えたら対応する
