### ISSUE TITLE
Remove unsafe code

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#255]
マルチスレッドの為にunsafeキーワードを一部使っているが、できれば無くしたい。
方法を検討する。

**Comment by hitenkoku** [comment]
#256 をやれればunsafeを削除することができるかもしれないので#256の調査で確認をする

**Comment by YamatoSecurity** [comment]
@hach1yon 

@kazuminn がhttps://github.com/Yamato-Security/hayabusa/issues/256 でunsafeを色々調べて下さって、結局unsafeは消せなさそうなので、このissueをクローズしますか？

**Comment by hach1yon** [comment]
ちょっと自分でも確認してみます

**Comment by YamatoSecurity** [comment]
There should be no security risk in the limited use of unsafe code we use in order to enable multi-threading so will probably leave it as it is. Someday in the future we may be able to get rid of all unsafe code if we can complete https://github.com/Yamato-Security/hayabusa/issues/256 .

**Comment by YamatoSecurity** [comment]
As there seems to be no security risk and we are not going to replace the trait usage with enum due to performance degradation I am going to close this issue.
