### ISSUE TITLE
re-implement selection nodes with enum

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#256]
traitからenumに変更する。そうすると、unsafeキーワードも消せそう。

**Comment by kazuminn** [comment]
これ私やりたいです。

**Comment by kazuminn** [comment]
と思いましたが、
 #148 を考えると、このissueはやらなくていいんじゃないかと思いました。

**Comment by hitenkoku** [comment]
前提として速くなるかを検証する必要がある。
ただ、既存のソースコードを大きく変えるので他の実装を止める必要がある。

**Comment by kazuminn** [comment]
ザックさんに「このissueやらないか」と提案されましたが、今私の持ってる知見を共有しておきます。
（事の発端が分からないなりに）

まず、
unsafe == 危ない　->  消そう
ってのは、結構短絡的です。

unsafeは、プログラマーによって安全性が保障されているものです。
Hayabusaでは、syncとsendのトレイト実装しかしておらず、空の実装なので、ポインターなどを使っていないので、このunsafeは保証されています。全く未定義な動作は、起こらないでしょう。
https://doc.rust-jp.rs/rust-by-example-ja/unsafe.html

空の実装 == {}
```
unsafe impl Sync for RuleNode {}
```

次に、enumをつかっても、結局、syncとsendトレイトを実装するのに、unsafeが必要になってきます。
また、sync sendはderiveが提供されていません。

以上で、やらないじゃなくて、できないと思います。できなくてよいので、言語側がそうしていると思います。
私の知見が間違っているかもしれないので、何かあれば、突っ込みが欲しいです。

**Comment by kazuminn** [comment]
あ、

```
enum RuleNode implements sync, send {}
```

みたいに、できるのかな。
ちょっと、小さなコード書いて、できるか確認してみます。

**Comment by kazuminn** [comment]
> ちょっと、小さなコード書いて、できるか確認してみます。
できませんでした。

unsafe、仕方がないかと。

**Comment by YamatoSecurity** [comment]
@kazuminn 情報ありがとうございます！
unsafeの使用は仕方ないですね。
traitからenumに変更すると、早くなるかどうか分かりますか？

**Comment by kazuminn** [comment]
@YamatoSecurity ググると、早くなる情報がでてきますが、Hayabusaでどれぐらい早くなるかは検証実装してベンチマークを取らないとわかりませんね。

検証実装するのは、「やりたいな」と思っていますが、「以下を待ってからの方がいいかな？」と思っています。
https://github.com/Yamato-Security/hayabusa/issues/255#issuecomment-1221697931

**Comment by YamatoSecurity** [comment]
@fukusuket 宜しくお願いします〜

**Comment by fukusuket** [comment]
調査めも:

[trait SelectionNode](https://github.com/Yamato-Security/hayabusa/blob/v2.2.0/src/detections/rule/selectionnodes.rs#L11-L27)の動的ディスパッチが一番多く発生する(ログ1件, 1ルール毎に発生)箇所は以下と推測
- https://github.com/Yamato-Security/hayabusa/blob/v2.2.0/src/detections/rule/mod.rs#L232-L233

[こちらの記事](https://github.com/Yamato-Security/hayabusa/issues/256#issuecomment-1000726688)によると、関数呼び出し時のオーバヘッドはざっくり以下
- `trait 12ms/100万回`
- `enum   3ms/100万回`

理論値計算式で、関数呼び出し時にかかるオーバヘッドの総時間を↓と仮定した場合、
- `オーバヘッドの総時間 = ログ総数　x ルール総数 x 動的ディスパッチ1回にかかる時間 / 並列処理数？`

ありそうなユースケース（5百万ログ※、3500ルール）を↑式に当てはめると、オーバヘッドの総時間は以下の見込み
- `trait = 5百万ログ x 3500ルール x 12ms/100万回 / 並列処理数10 ≒ 21秒` 
- `enum  = 5百万ログ x 3500ルール x  3ms/100万回 / 並列処理数10 ≒ 5秒`

上記踏まえると、`enum`改善効果を十分出せる実装にできた場合は、↑ケースでは`21秒 - 5秒  = 16秒`くらい速くなりそう

※ [いつもの6.1 GBデータ](https://github.com/NextronSystems/evtx-baseline/releases/download/v0.7/all-evtx.tgz)がだいたい5百万ログ

**Comment by fukusuket** [comment]
[こちらのブランチ](https://github.com/Yamato-Security/hayabusa/compare/main...improve-speed-by-changing-trait-to-enum)でtrait SelectionNodeを Enumに置き換えた実装を試してみました！
Enum置き換え版のほうが性能が劣化するという結果でした😢 

修正前
```
Elapsed time: 00:06:25.167
Rule Parse Processing Time: 00:00:00.903
Analysis Processing Time: 00:06:19.334
Output Processing Time: 00:00:04.929

Memory usage stats:
heap stats:    peak      total      freed    current       unit      count
  reserved:    3.8 GiB    3.8 GiB   83.0 MiB    3.7 GiB
 committed:    3.4 GiB   57.8 GiB   54.4 GiB    3.3 GiB
```

修正後
```
Elapsed time: 00:06:49.137
Rule Parse Processing Time: 00:00:00.911
Analysis Processing Time: 00:06:43.338
Output Processing Time: 00:00:04.886

Memory usage stats:
heap stats:    peak      total      freed    current       unit      count
  reserved:    3.9 GiB    3.9 GiB   83.0 MiB    3.8 GiB
 committed:    3.5 GiB   60.1 GiB   56.6 GiB    3.4 GiB
```

今回は以下条件でenum置き換え実装をしてみました。
- `dyn SelectionNode` を全て `SelectionNodeEnum`に置き換え
  - (なので、`trait SelectionNode`の動的ディスパッチは修正後発生していない想定)
- 処理ロジックは各`SelectionNode`の実装をそのまま何も変えずに呼び出す
- 処理の分岐(修正前は、`trait`の動的ディスパッチにより実現)は、`Enum`のパターンマッチにより実現

上記結果を踏まえると、単純なtrait -> enum置き換えだけではパフォーマンス改善しないようです。

よりEnumの効果を発揮する実装があると思うのですが、、、🤔
いまのところ改善点がわからないので、また何かわかったら調査結果を追記します！

**Comment by YamatoSecurity** [comment]
おっと！逆に遅くなってショックですね。調査ありがとうございました！
また新しい情報が出てきたら、ご共有下さい。
最近Rustは色々進化しているので、もしかして変わってきたかもしれません。(最新の情報では、regexクレートよりpcre2の方が速いって書いてあったのに、それも逆でしたね）

**Comment by YamatoSecurity** [comment]
traitのままの方が良さそうなので、取り敢えずこのissueをクローズします。
