### ISSUE TITLE
同条件で実行しても、処理時間におおきなバラツキがある。

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#262]
同じルール/同じイベントログを解析しても処理時間にバラツキが出る。
心当たりはあって、マルチスレッドのスレッドの作り方微妙で処理時間にバラツキが出ているような気がする。

処理時間に大きなバラツキがあることは下記のISSUEを見ればわかる。
https://github.com/Yamato-Security/hayabusa/issues/253

**Comment by hitenkoku** [comment]
測定した担当者が開発しながら測定していたため、マシン負荷で計測時間が大きく変動してしまった可能性があります。
一旦このissueは複数人で同様な事象が見られたら対処とさせてください

**Comment by hitenkoku** [comment]
問題解消のためclose
