### ISSUE TITLE
-R --rule-file=というオプションでディレクトリ指定ではなく、一つのルールファイルだけを使うオプション

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#311]
## 概要

ルールテストやチューニングでかなり手間がかかっているので（ルールファイルを毎回一時的に新しいディレクトリに移動して、また戻さないといけないので）-R --rule-file=というオプションでディレクトリ指定ではなく、一つのルールファイルだけを使うオプションが欲しい。
(同じ-r --rules= オプションでファイル名もしくはディレクトリ名のどちらでも対応できたら、一つのオプションで済むので、それが理想の気がしますが、実装が楽の方で良いと思います）

## 仕様
- -Rの指定もしくは --rulesで1つのymlファイルのみを指定するオプションを作成する

**Comment by kazuminn** [comment]
冬休みに実装してました。同一オプションでファイルとディレクトリを指定できます。

**Comment by hitenkoku** [comment]
@kazuminn 対象となるリモートブランチが見当たりません。実装完了している場合はpull requestを出しておいてください
