### ISSUE TITLE
First runtime on Windows is slow due to Defender

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#355]
よくわからないけど、初回は遅い。
自分の環境だと1回目は13secで、2回目以降は5sec

**Comment by kazuminn** [comment]
pc再起動後ではないですけど、初回実行遅いですね。コンパイルしての初回のような気がする。

時間はわからないですけど、Ctrl-Cで一度止めて、もう一度実行すると、早い。

**Comment by YamatoSecurity** [comment]
@hach1yon 昔、共有ライブラリを使っていたので、それが原因かもしれません。今は完全に静的にコンパイルしているので、最新版でも初回だけ遅いかどうか試して頂けますか？
（時間がある時で大丈夫です）

**Comment by hach1yon** [comment]
@YamatoSecurity @hitenkoku 

修正するかどうは置いておいて、とりあえず再現は出来ました。
何回か試しましたが、似たような結果になります。

1回目
```
C:\Users\takai\dev\git\hayabusa>hayabusa.exe --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -o hajime.csv

Elapsed Time: 00:00:15.215
```

2回目
```
C:\Users\takai\dev\git\hayabusa>hayabusa.exe --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -o hajime2.csv

Elapsed Time: 00:00:11.827
```

**Comment by hach1yon** [comment]
macは分からないですが、windowsで再現できる人は他にいないですか?

**Comment by hach1yon** [comment]
もうひとつ持っている別のPCで試したら、計測毎に時間が違いすぎてちょっとよくわからなかったです。

**Comment by hitenkoku** [comment]
明こちらも計測ごとに時間が大きく変わるのであんまりわからないです。

**Comment by YamatoSecurity** [comment]
検証ありがとうございます！原因はなんでしょう。。
私の環境では、1回スキャンしたら、CPUが熱くなって、しばらく待たないとその後のスキャンが遅くなることが多いです。Windows端末でも１回目が遅くて、その後早くなる現象はまだ見ていないです。もう少し調べてみます。

**Comment by YamatoSecurity** [comment]
Windows端末で再現できました。
再起動後に、初回のライブスキャンは47.5秒で、その後は大体35秒です。
原因はWindows Defenderのリアルタイムスキャンのようです。
[https://github.com/rust-lang/cargo/issues/5028](https://github.com/rust-lang/cargo/issues/5028) 等で文句言っている人がいて気づきました。
リアルタイム保護を無効にしたら、起動後の初回でも35秒でした。

@hach1yon さんの環境でリアルタイム保護を無効にしたら、どうなりますか？

**Comment by hitenkoku** [comment]
ありがとうございます。それではドキュメント修正のpull-requestを出しておきます。
調査完了でドキュメント対応のみにするのでタグを少し変えておきます。
