### ISSUE TITLE
指定时间段取日志，不准确

### ISSUE THREAD

**Issue by linuxdy** [Yamato-Security/hayabusa#356]
以下取的开始时间为2021/12/29 23:15:00 +09:00，结束时间为2021/12/29 23:16:00 +09:00，可是结果打印出来的不是我取的时间段的数据
![image](https://user-images.githubusercontent.com/50064309/148195360-23011b8b-30f0-4a69-b9c6-0da1411acdf1.png)

**Comment by kazuminn** [comment]
@linuxdy 
Thank you for issue.

It would be helpful if you could write in English

**Comment by kazuminn** [comment]
@linuxdy 
Take a closer look at +09: 00 and +08: 00.
There is a time difference, so I think it is included.
If you try it at +08: 00, you will get the correct result.

**Comment by hitenkoku** [comment]
@linuxdy 
You haven't replied for a week, has the issue been resolved? If not, please ReOpen the issue and leave a comment!
