### ISSUE TITLE
detailsが定義されていなくても、detailsを出力する

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#359]
outputに記載がなければ出力するデフォルト出力としてイベントIDをキーとして、
他設定ファイルで指定したフィールド値を取得できるようにしたい

**Comment by kazuminn** [comment]
ザックさんあたりが仕様を考え中。

**Comment by hitenkoku** [comment]
仕様検討中のため担当者を変更しました

**Comment by YamatoSecurity** [comment]
`details`フィールドが定義されていない場合は、[`rules/config/default_details.txt`](https://raw.githubusercontent.com/Yamato-Security/hayabusa-rules/main/config/default_details.txt)を参照にして、ProviderとイベントIDで`details`を出力したいです。`Application`ログ等の場合は、様々な`Provider`が同じ`EventID`を使うことがあるので、`Channel`と`EventID`の組み合わせではく、`ProviderName`と`EventID`にしています。
