### ISSUE TITLE
evtxライブラリの--features fast-allocの検証

### ISSUE THREAD

**Issue by kazuminn** [Yamato-Security/hayabusa#367]
最新evtxライブラリにおいて、--features fast-allocオプションを付けてコンパイルすると、早くなるみたい。

検証しましょう。

**Comment by kazuminn** [comment]
00:00:00.315
00:00:00.149
00:00:00.152
00:00:00.177

**Comment by kazuminn** [comment]
hayabusa-rulesを全部使いましたが、以下の結果になりました。

`.\target\release\hayabusa.exe  -D -n -r C:\Users\warug\hayabusa-rules\ -f 'C:\Users\warug\hayabusa-sample-evtx\YamatoSecurity\T1218.004_Signed Binary Proxy Execution InstallUtil\sysmon.evtx'`

now -> fast-alloc
00:00:01.634 -> 00:00:01.661
00:00:01.931 -> 00:00:01.721
00:00:01.655 -> 00:00:01.780
00:00:01.682 -> 00:00:01.597
00:00:01.746 -> 00:00:01.679

**Comment by kazuminn** [comment]
@YamatoSecurity 以上の結果になりました。速くなったり、遅くなったりします。
1/2の確率で、そうなりそうです。なので、--features fast-allocはつけてもつけなくてもよい気がしますが、
ほかに、ベンチマークが必要でしょうか？

**Comment by YamatoSecurity** [comment]
検証ありがとうございます！
もう少しでかいevtxファイル、また多くのevtxファイルに対してもベンチマークを取りたいです。こちらでやっておきますね。
結局どうやって`--features fast-alloc`でコンパイルできました？

**Comment by YamatoSecurity** [comment]
数GBのデータセットに対してベンチマークを取ってみました。
デフォルトの設定では、こちらも特に差がありませんでしたが、スレッド数を減らしたら少し早くなりました。
Windowsの場合はfast-allocを有効にすると、rpmallocが使用されるようです。
https://github.com/mjansson/rpmalloc　のグラフを見るとスレッド数が1~5個の場合はパフォーマンスが特に良くなるので、fast-allocを有効にしたいと思います。

スレッド数を３個した場合は、処理時間が15分57秒から15分22秒になりました。(約4%早い）

**Comment by YamatoSecurity** [comment]
有効にしました。
