### ISSUE TITLE
Windows Terminalで異常な文字がある場合、途中で出力されなくなる

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#382]
Windows Terminalで異常な文字が結果にある場合、途中で出力されなくなって、CTRL+Cを押して強制終了する必要があります。
デフォルトルールとサンプルEVTXファイルで再現できます。Windows 10のWindows Terminalで検証しています。
`./target/release/hayabusa -d ../hayabusa-sample-evtx -r ../hayabusa-rules`
因みに、カラー出力する際は無事に出力されます。

![Windows Terminal Output Bug](https://user-images.githubusercontent.com/71482215/151685614-677aa4be-a4e3-4783-84e2-e56d5e25a1b4.jpg)

`2019-07-20 00:11:26.852 +09:00,MSEDGEWIN10,1,informational,Process Creation,"Command: ""C:\Windows\system32\cmd.exe"" /c ""ntdsutil â€œac i ntdsâ€ â€œifmâ€ â€œcreate full C:\Atomic_Red_Team q q""  :  Path: C:\Windows\System32\cmd.exe  :  User: MSEDGEWIN10\IEUser  :  Parent Command: powershell",../hayabusa-rules/hayabusa/sysmon/events/1_ProcessCreation.yml,../hayabusa-sample-evtx/EVTX-ATTACK-SAMPLES/AutomatedTestingTools/PanacheSysmon_vs_AtomicRedTeam01.evtx`
の行で出力が止まってしまいます。

コントロールコードのHex: 0x9Dが問題っぽいです。

**Comment by hitenkoku** [comment]
この内容は正直、Windows Terminal側の問題なので、同様の事象がないかどうか確認してみます

**Comment by YamatoSecurity** [comment]
もう少し調べました。コントロール文字が原因のようです。
https://github.com/microsoft/terminal/commit/6742965bb89f1391f4ac036e52bcf68f7db305f6
で修正しているけど、いつTerminalをアップデートしたら直るか分かりません。（fixはまだdevブランチにしかないようです）
（修正されるまでにworkaroundないかな？　因みにhttps://github.com/microsoft/terminal/issues/10310　で議論されていました。）

取りあえずReadmeで「Terminalはまだバグっているので、現在使えない可能性がある。」
1.1が出た時に「カラー出力したら無事に出力されるので、出力が途中で止まる場合は`-c`を付けてください」という風に説明しましょうか？

**Comment by hitenkoku** [comment]
一応　https://github.com/microsoft/terminal/blob/main/doc/terminal-v2-roadmap.md　でロードマップは出てますが……そのときに入るんでしょうかね……

ひとまずReadmeの方は、ご指摘の通り、修正をかけて、対応する形を取ったほうが良さそうですね(流石にterminalをdevからもってこいとは言えない……)

**Comment by hitenkoku** [comment]
こちらの対応ですが、 #378 で対応をさせていただこうと思います

**Comment by hitenkoku** [comment]
closed via #378

**Comment by hitenkoku** [comment]
Windows Terminal v1.12.1073 でもこの事象は解決していないことを確認したのでメモ代わりにコメントしておきます

**Comment by hitenkoku** [comment]
https://github.com/Yamato-Security/hayabusa/issues/481#issuecomment-1088253217 の記載にある通り、文字列からコントロール文字列を削除することで対応することが可能であるかを検討するため本issueをreopenします

ref #468  #464
