### ISSUE TITLE
オプションがない場合は -h と同じようにヘルプメニューを出力したい

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#387]
> 動作確認してみたのですが、./hayabusaだけでは`-h`のヘルプメニューが表示されませんでした。
> できれば、hayabusaのみ（オプション無し）を実行したら、「HAYABUSA」ロゴの後に`-h`の同じヘルプメニューを出力したいですね。
> 

_Originally posted by @YamatoSecurity in https://github.com/Yamato-Security/hayabusa/issues/378#issuecomment-1025562151_

**Comment by hitenkoku** [comment]
@YamatoSecurity  確認してみましたが、利用しているClapというライブラリが3.x系であれば、文字列としての出力もできるのですが、現在利用しているClapは以下のビルドエラーが出ることがわかっているので、こちらについてはmilestoneとしてはv1.2以降での検討事項とさせてください

https://github.com/Yamato-Security/hayabusa/issues/370#issuecomment-1023112135

**Comment by hitenkoku** [comment]
Clap3.x系に置き換えて修正ができないか確認したが、大幅な修正が必要となり、かつ得られる効果が少ないので一旦保留

**Comment by kazuminn** [comment]
@hitenkoku 
こちら確認したいのです。mainブランチで以下のコードのようにして実装してありますが、v3.xにすれば、v3.xで新しく追加された方法で対応できるという話でよろしいでしょうか？
もしそうであれば、その別の方法を教えてもらってもよろしいでしょうか？チェンジログ見てみましたが、いまいち見つかりませんでした。

#413 を今対応していますが、以下のコードが動かなくなるので(usage()がなくなった）、一緒にやってしまったほうが都合よさそうな気がしたので、質問しました。
https://github.com/Yamato-Security/hayabusa/blob/main/src/main.rs#L91-L102

**Comment by hitenkoku** [comment]
@kazuminn はい、その想定です。

**Comment by hitenkoku** [comment]
本件 #413 の対応が私の方で完了し、こちらの対応も完了したので担当者を変更します。
