### ISSUE TITLE
ルールlevelのチューニング設定ファイル

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#390]
沢山のsigmaルール作者が居るため、アラートの深刻度(`level`)が人によって大きく変わります。
また、ルールは環境によって深刻度が変わってくるので、hayabusaルール班とユーザがsigmaのデフォルトレベルをチューニングできるようにしたいです。
./config/rule_levels.txtファイルで
<ルールID>, <新しいレベル> #コメント
という形式でルールチューニングします。

例：
b20f6158-9438-41be-83da-a5a16ac90c2b, low # ./rules/sigma/other/taskscheduler/win_rare_schtask_creation.yml
7b449a5e-1db5-4dd0-a2dc-4e3a67282538, critical # ./rules/sigma/builtin/security/win_hidden_user_creation.yml
等々

設定ファイルにある`level`が優先されます。

**Comment by kazuminn** [comment]
ルールを直接編集する感じではダメなんでしょうか？
他の項目も同じような感じでチューニングしたい、などが後から出てきそうな気がします。

**Comment by YamatoSecurity** [comment]
Hayabusaルールなら、直接編集できるけど、Sigmaルールは編集できないため、この機能が欲しいです。
(編集したとしても、ルール更新で上書きされてしまいます。）
他の項目のチューニングは不要だと思いますが、何かないか考えてみます。

**Comment by hitenkoku** [comment]
pythonとかで別添えのツールとして作成して、yamlファイルを上書きするようにする形で合意

**Comment by YamatoSecurity** [comment]
昨日、議論したらデフォルトでルールレベルを勝手に変えるといろんな問題が発生しそうなので、それをやめようと思っています。
sigmaルールを更新した後に、**別のツールで**levelを書き換えるようにしようと思っていたのですが、環境依存になってしまう(例: 端末にpython等が入っていなかったら使えないので）この機能をhayabusaで実装したいです。
ルールチューニングしたいユーザは
./hayabusa.exe --update-rulesでルールを更新した後に
./hayabusa.exe --level-tuning ./config/rule_levels.txtコマンドでルールファイルのレベルを直接書き換えるイメージです。
