### ISSUE TITLE
-u --update機能

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#391]
rulesフォルダが空の場合は、ユーザがhayabusa-rulesリポからルールをダウンロードしていない可能性が非常に高いです。`git submodule update --init`コマンド等でダウンロードできますが、gitをインストールしていないユーザも多いので、`--update`機能で最初のルールダウンロードもできると便利です。

まず、hayabusaを`--rules`と`--update`オプション指定なしで実行した際に(通常のスキャンの際に)、rulesフォルダが空の場合は以下のエラーを出力します：
"You currently do not have any rules in your rules folder.
You can download them from https://github.com/Yamato-Security/hayabusa-rules or run the -u / --update command to get the latest rules."

--updateコマンドを実行する場合：
まず、他のオプションがあるかどうかチェックし、他のオプションが指定された場合（例: hayabusa.exe --update -d sample/ -o hoge.csv等々）は、コマンドオプションがおかしいので、エラーメッセージを出力します：
"You cannot specify any other options when using -u / --update"

rulesディレクトリ配下にhayabusaとsigmaディレクトリが無い場合は、https://github.com/Yamato-Security/hayabusa-rulesからルールをダウンロードして、./rules配下にルールを置きます。

rulesディレクトリ配下にhayabusaとsigmaディレクトリがある場合は、まず以下の警告を出力します：
"All of your rule files in the rules folder will be deleted and replaced by the latest rules https://github.com/Yamato-Security/hayabusa-rules. Is this ok? (y/N)"

ユーザが"y"を入力すると、hayabusaとsigmaルールディレクトリを消して、新しいルールをダウンロードします。(rsyncのように差分だけをダウンロードできたら理想です。）
ユーザが例えば、`rules/testing`や`rules/my-rules`というhayabusaとsigmaディレクトリ以外のフォルダがある場合は上書きされないようにしたいです。

後で、Readmeで自分のルールが上書きされないように、別のディレクトリ(/rules/my-rules等)に置いて下さいというように記載しておきます。

**Comment by hitenkoku** [comment]
https://docs.rs/git2/latest/git2/ を使って対応できないか確認する。

**Comment by hitenkoku** [comment]
`git clone [hayabusa-rules] rules` でrulesフォルダをクローンする機能をつける。rulesフォルダで重複した場合はエラーが出るはず(ライブラリの実装を確認する)

**Comment by hitenkoku** [comment]
close by #425 merged
