### ISSUE TITLE
Bug: Detection and display not working in fields with invisible tabs and enter characters

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#395]
フィールドに`%`があると、正しく検知できないようです。
再現方法：添付した4674ルールで`#AccessMask: "%%1539"`のコメントを消したら検知できなくなります。(添付するために.txtのファイル拡張子を追加する必要があったので、消して下さい。）
DeepblueCLIの`eventlog-dac.evtx`ファイルで検証できます。
`.\target\release\hayabusa.exe -r ..\hayabusa-rules\hayabusa\default\alerts\Security\4674_PossibleHiddenServiceAttempt.yml -f ..\..\test\DeepBlueCLI-master\evtx\eventlog-dac.evtx`

[4674_PossibleHiddenServiceAttempt.yml.txt](https://github.com/Yamato-Security/hayabusa/files/8028565/4674_PossibleHiddenServiceAttempt.yml.txt)

**Comment by hitenkoku** [comment]
@YamatoSecurity 一旦確認します。こちらでも確認しますが、このAccessMaskですが、ダブルクォーテーションではなく、シングルクォートにしたら動作するか確認してもらってもよろしいでしょうか

**Comment by hitenkoku** [comment]
シングルクォートにしても本事象が発生することを確認しました

**Comment by hitenkoku** [comment]
見てみたのですが、ACCESSMASKというエイリアスが存在していないように見えます。

一旦私の方でエイリアスを追加してみて対応できないか確認します

**Comment by hitenkoku** [comment]
eventkey_alias.txtに対応するAccessMaskが登録されていることを確認しました。

**Comment by YamatoSecurity** [comment]
そうです、イベントキーが登録されていても駄目でした。
detailsの出力では「%%1539」が無事に出力されますが、なぜかフィールドでは使えませんでした。

**Comment by hitenkoku** [comment]
少しデバッグコードを入れ込んでどのように処理されているか確認します

**Comment by hitenkoku** [comment]
@YamatoSecurity  原因がわかりました。
原因はイベント側で入っている \r\n等の情報が原因かと思われます。
\r\n\tを削除することで対応が可能ので少々お待ち下さい

> debug:keyname/"AccessMask" | value:Some("%%1539\r\n\t\t\t\t")

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応が完了しました。 ご指定いただきましたymlで問題なく検出できることを確認しました
#396 でpull requestを出しましたのでご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
close by #425 merged
