### ISSUE TITLE
Visual C++ 再頒布可能パッケージがインストールされていないと実行できない

### ISSUE THREAD

**Issue by matcha-shake** [Yamato-Security/hayabusa#404]
## 利用環境
- OS: Windows 10 21H2 x64
- hayabusa: v1.0.0 Initial Public Release 2の[hayabusa-1.0.0-windows-x64.zip](https://github.com/Yamato-Security/hayabusa/releases/download/v1.0.0-R2/hayabusa-1.0.0-windows-x64.zip)

## 発生事象
当該OS上でhayabusaを実行した際に、下記の様にVisual C++ 再頒布可能パッケージがないと実行エラーが発生します。
![スクリーンショット 2022-02-22 11 35 48](https://user-images.githubusercontent.com/2188383/155054509-84cf892c-d6cd-42e6-9ad1-58e33a58fa84.png)

下記URLで公開されているVisual Studio 2015、2017、2019、および2022の Microsoft Visual C++ 再頒布可能パッケージのx64バージョンをインストール後に、再度hayabusaを実行したところ、エラーなく実行できました。
https://docs.microsoft.com/ja-JP/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

## 提案内容
Rustのビルド周りについて知らないため内容が正しくないかもしれないですが、exeのリリースバージョンを公開される場合は、ランタイムの静的リンクを実行していただくことは可能でしょうか。  
もしくは、readmeにhayabusa実行時にはVisual C++ 再頒布可能パッケージのインストールが必要である旨の記載があれば良いと思います。

**Comment by hitenkoku** [comment]
@matcha-shake ご連絡ありがとうございます。その際に実行した際のコマンドなどがあればいただければ大変助かります。

hayabusaで利用しているwinapiというライブラリを用いており、そこでvcruntime140.dllを参照する可能性があります。

**Comment by matcha-shake** [comment]
@hitenkoku 実行状況としては下記のとおりです。

1. powershellプロンプトから`> .\hayabusa-1.0.0-windows-x64.exe -f ..\file.evtx`や`> .\hayabusa-1.0.0-windows-x64.exe`を実行したがプロンプト上では何も表示されず実行終了した。この際は、エラーウィンドウの表示もなかった。
2. exeファイルを直接ダブルクリックして実行したところ、smart screenで実行ブロックされたので実行を許可した
3. ランタイムのエラーウィンドウが表示された
4. Visual C++ 再頒布可能パッケージパッケージをインストール
5. powershellプロンプトから再度exeファイルを実行したところバナー等が表示されて実行が成功した。

**Comment by hitenkoku** [comment]
ありがとうございます！
hayabusaで呼び出しているライブラリ関連だと思いますが、利用しているライブラリを独自に修正するのは管理の観点から厳しいので、ドキュメントでWindows版はVisual C++ 再頒布可能パッケージをインストールするように修正させていただきます。

**Comment by hitenkoku** [comment]
#408 でVisual C++の再頒布パッケージがない環境でも動作できるようにしました。
developブランチにはマージ済みですが、現在はmainブランチへのマージ待機中です。

**Comment by hitenkoku** [comment]
close by #425 merged
