### ISSUE TITLE
T1036.003に関連するsigmaルールで検知されない

### ISSUE THREAD

**Issue by matcha-shake** [Yamato-Security/hayabusa#405]
## 発生事象
直近のEmotet感染において、ATT&CK T1036.003に関連する、リネームされた`certutil.exe`の実行が確認されています。  
Sigmaルール及びHayabusaルールには上記アクティビティを検知するルールは存在します。
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_renamed_binary.yml
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_renamed_binary_highly_relevant.yml
https://github.com/Yamato-Security/hayabusa/blob/fddcbc7e7d5c96cb2e35efe5d401549eab997f0a/rules/sigma/process_creation/win_renamed_binary.yml
https://github.com/Yamato-Security/hayabusa/blob/fddcbc7e7d5c96cb2e35efe5d401549eab997f0a/rules/sigma/process_creation/win_renamed_binary_highly_relevant.yml

しかし、実際の感染端末から収集したSysmonのイベントログをhayabusaでスキャンしたところ、上記ルールでの検知がされませんでした。気になり、検証端末で実験してみたところ、Sysmonのイベントログでリネームされた`certutil.exe`の実行は記録されていますが、上記ルールでの検知がされていません。  
そのため、hayabusa内のスキャン処理に何かしらの不具合があるのではないかと思い、Issueを作成します。本件について調査していただけますと幸いです。

## 利用環境
OS: Windows 10 21H2 x64
Sysmon: 導入済み
hayabusa: v1.0.0 Initial Public Release 2の[hayabusa-1.0.0-windows-x64.zip](https://github.com/Yamato-Security/hayabusa/releases/download/v1.0.0-R2/hayabusa-1.0.0-windows-x64.zip)
比較検証用のchainsaw: v1.1.6の[chainsaw_x86_64-pc-windows-msvc.zip](https://github.com/countercept/chainsaw/releases/download/v1.1.6/chainsaw_x86_64-pc-windows-msvc.zip)

## 検証内容
1. コマンドプロンプト上で下記コマンドを実行して、リネームされた`certutil.exe`を実行
```
copy %SystemRoot%\System32\certutil.exe %SystemRoot%\Temp\renamed.exe
%SystemRoot%\Temp\renamed.exe
```
2. Symonで収集された実行イベントログが下記ファイルです。evtxファイルが直接添付できないためzipで圧縮しています。
[renamed_certutil.zip](https://github.com/Yamato-Security/hayabusa/files/8113465/renamed_certutil.zip)

3. 上記evtxファイルに対して、`.\hayabusa-1.0.0-windows-x64.exe -f ..\renamed_certutil.evtx -v`を実行しましたが、期待した上記ルールで検知されませんでした。実行時のログは下記ファイルです。期待した上記ルールのloadは確認しました。
[hayabusa_log_verbose.txt](https://github.com/Yamato-Security/hayabusa/files/8113498/hayabusa_log_verbose.txt)

4. 比較検証として、同様の機能を持つchainsawで上記evtxファイルをスキャンしたところ、期待した上記ルールでの検知がされました。実行時のログは下記ファイルです。
[chainsaw_log.txt](https://github.com/Yamato-Security/hayabusa/files/8113499/chainsaw_log.txt)

そのため、sigmaルール自体の問題ではなく、hayabusa内のスキャン処理に何かしらの不具合があるのではないかと思いIssue作成。

## メモ
ルールを編集して見た限り、condition周り (`SELECTION_1`だけだと検知する、`SELECTION_1 and SELECTION_2`にすると検知しない)かとも思いますが、コードレベルで調査したわけではありません。

**Comment by hitenkoku** [comment]
@matcha-shake  ご指摘ありがとうございます。確認が取れました。
原因はSELECTION2に設定されたOriginalFileNameのエイリアス設定がなされていないことが原因でした。

次のpull requestで対応をしていきます。少々お待ち下さい。

**Comment by hitenkoku** [comment]
エイリアス設定を修正することで以下のように検知することを確認しました。

> Timestamp,Computer,EventID,Level,RuleTitle,Details,RulePath,FilePath
> 2022-02-22 11:20:37.317 +09:00,DESKTOP-8UT7PUM,1,informational,Process Creation,"Command: C:\Windows\Temp\renamed.exe  :  Path: C:\Windows\Temp\renamed.exe  :  User: DESKTOP-8UT7PUM\test  :  Parent Command: ""C:\Windows\system32\cmd.exe"" ",../hayabusa-rules\hayabusa\sysmon\events\1_ProcessCreation.yml,.\no_add!_test-folder\renamed_certutil\renamed_certutil.evtx
> 2022-02-22 11:20:37.317 +09:00,DESKTOP-8UT7PUM,1,high,Highly Relevant Renamed Binary,,../hayabusa-rules\sigma\process_creation\win_renamed_binary_highly_relevant.yml,.\no_add!_test-folder\renamed_certutil\renamed_certutil.evtx
> 2022-02-22 11:20:37.317 +09:00,DESKTOP-8UT7PUM,1,medium,Renamed Binary,,../hayabusa-rules\sigma\process_creation\win_renamed_binary.yml,.\no_add!_test-folder\renamed_certutil\renamed_certutil.evtx
>

**Comment by hitenkoku** [comment]
#406 のようにconfig/eventkey_alias.txtに以下1行を追加していただければ、https://github.com/Yamato-Security/hayabusa/issues/405#issuecomment-1047408699 のように検知するようになりますので、確認をしたい場合はどうぞ

> OriginalFileName,Event.EventData.OriginalFileName

**Comment by matcha-shake** [comment]
@hitenkoku 
調査及び修正ありがとうございます。
こちらでも、#406 での`eventkey_alias.txt`修正を取り込んだv1.0.0 Initial Public Release 2で再スキャンしたところ、本Issueに添付したevtxファイルと実際の感染端末から回収したsysmonイベントログともに、期待したルールで検知されることを確認しました。

直近はこの変更で対応させていただき、メインブランチへのマージ及びリリースバージョンの公開を待ちたいと思います。

**Comment by hitenkoku** [comment]
close by #425 merged
