### ISSUE TITLE
ルールに関係する設定ファイルをhayabusa-rulesレポジトリに移動する

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#409]
rulesをhayabua-rulesレポジトリにするタイミングで同時にルールに関係する設定ファイルもhayabusa-rulesレポジトリにした方が良さそうです。(ルール更新で同時に設定ファイルも更新しないと、ルールが正しく動かない可能性があるため。）
`./config/`配下の
```
eventkey_alias.txt
exclude-rules.txt
noisy-rules.txt
regex/*
```
をhayabusa-rulesレポジトリの`config`フォルダに置いて、Hayabusaで`./rules/config`フォルダにある設定ファイルを読み込む。

※ついでにexclude-rules.txtをexclude_rules.txtのアンダーバーに合わせる？
それか、他のルール名のようにCamel CaseのExcludeRules.txt、TargetEventIDs.txt等にする？(個人的に一番読みやすい）

level_color.txt、target_eventids_sample.txt、target_eventids.txt、timeline_event_info.txtの設定ファイルをHayabusaのconfigファイルののままにします。

**Comment by hitenkoku** [comment]
ファイルの読み込み箇所を修正することは必要になります。一応対応はしておきます。あとはexclude-rules.txtもハイフンはアンダーバーに合わせるようにします。

**Comment by hitenkoku** [comment]
hayabusa-rulesへの移動は https://github.com/Yamato-Security/hayabusa-rules/pull/7 で実施。

**Comment by hitenkoku** [comment]
close by #425 merged
