### ISSUE TITLE
--updateの結果表示で更新されたファイルの一覧を出力する

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#410]
あともう一つの(もっと簡単な？)方法として、(詳細は分からないけど)、例えばルールファイルにあるmodified_dateを比較するのはどうですか？
全てのmodified_dateをチェックして、一番最新の日付で以下のように出力する：
```
Current latest rule: 2020/02/22
Updated rules successfully.
Current latest rule 2022/02/23
```
等にしたら、ユーザがどのぐらい古いルールを使っていたか、現在の最新のルール等が分かります。
ま、優先度は低で良いと思います。

_Originally posted by @YamatoSecurity in https://github.com/Yamato-Security/hayabusa/pull/401#issuecomment-1048522624_

**Comment by hitenkoku** [comment]
方針としてはrules配下のファイルの、ファイル名とmodified_dateの組の情報を取得し、
update後に再度取り直して比較することで対応をするようにする。ファイル名としてパイプを使うことはあまりないからHashSetでそのようにつなげてしまったほうが検索としては早いかも。

**Comment by YamatoSecurity** [comment]
追加：ルール数も入れましょう。(rules/配下のymlファイルのcount)
例：
```
Number of Hayabusa rules: 200
Number of Sigma rules: 1000
Current latest rule: 2020/02/22
Updated rules successfully.
Number of Hayabusa rules: 400
Number of Sigma rules: 1500
Current latest rule: 2022/02/23
```

**Comment by hitenkoku** [comment]
@YamatoSecurity  ymlファイルのカウントはできますが、念のため既存のyamlファイル読み込み処理のところが、ファイルパスを取得出来ているか確認させてください。

また、ルール数を入れるという話ですが、これは更新対象のルール数の話ではなく、対象フォルダ配下に存在するymlファイルのルール数ということでよろしいでしょうか。

表示方法についてですが、どのファイルが更新されたかを明らかにするため表示方法として以下のような形はいかがでしょうか。
Current latest ruleはファイルの最も新しい更新日時を出すというロジックならばできますが、hayabusa-rulesのgitの最新コミット日とはずれる可能性がありますが問題ないでしょうか。

> [Rule Updated] {ファイル名}
>...
> Updated number of xxx rules: 100
> Current latest rule: YYYY/MM/DD

**Comment by YamatoSecurity** [comment]
お返事が遅くなって、ごめんなさい！
上記のようにrulesフォルダ配下に存在するymlファイルのルール数を出したいです。その差分(例：Updated rules: 100)も入れた方がどれぐらい更新されたか分かりやすいので、それもあると良さそうですね。

更新されたルールの一覧表示については、それもmodifiedフィールドを確認して出力するのはどうですか？
例えば、更新前のmodified日付が2022/02/22で更新後の最新のmodified日付が2022/03/1だったら、modified日付が2/22~3/1の間のルールのtitleフィールドを出力します。(ファイル名より、タイトル名の方が分かりやすいため）

**Comment by hitenkoku** [comment]
承りました。それでは頂いた仕様で対応できるかは確認してみます。

タイトル名だけを出してもわかりづらいとは思いますので、
タイトル名の後ろにカッコ書きで末尾にファイル名をつけるようにしたいと思います。
