### ISSUE TITLE
ルール設定におけるワイルドカードがcase-insensitiveである旨を記載する

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#411]
https://github.com/Yamato-Security/hayabusa/blob/main/doc/AboutRuleCreation-Japanese.md の ワイルドカードにて、SIGMAルールに準拠するという記載の身になっていますが、SIGMAルールはcase-insensitive となっているので、その旨を記載する

**Comment by YamatoSecurity** [comment]
case sensitiveのaggregator (startswith, containsなど）はcase-sensitiveであることも明記しましょう。

**Comment by hitenkoku** [comment]
close by #425 merged
