### ISSUE TITLE
clapのバージョンアップ

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#413]
clap がv2.xを利用しているが、v3.xを使うようにしたい。

**Comment by hitenkoku** [comment]
@YamatoSecurity  確認をしたところ evtx crateがclap 2,x系を利用していることがわかりました。それが原因でclap の参照ミスが発生しているようです。方針としては別のcrateを探すか、evtxをフォークしてclapv3対応依頼をしていくかのどちらかになりそうです。

**Comment by kazuminn** [comment]
> evtxをフォークしてclapv3対応依頼をしていく

そんなに修正箇所がなかったので、慣れでさくっとプルリクしてみました。
https://github.com/omerbenamram/evtx/pull/217

**Comment by hitenkoku** [comment]
他のcrateを参考にして、私の方で対応が完了しましたので、担当者を変更します。
