### ISSUE TITLE
hayabusa-sample evtxをスキャンしたら、4688のイベントの%CommandLine%が半分正しく変換されているが、半分は%CommandLine%のまま出力している

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#416]
いつのタイミングで調子悪くなっているか分かりませんが、hayabusa-sample evtxをスキャンしたら、4688のイベントの%CommandLine%が半分正しく変換されますが、半分は%CommandLine%のまま出力してしまいます。
`./target/release/hayabusa -d ../../hayabusa-sample-evtx -o sample.csv`

<img width="1436" alt="Screen Shot 2022-02-26 at 5 51 16" src="https://user-images.githubusercontent.com/71482215/155801310-db1ed811-62ae-4ad9-a532-249f775d3299.png">

この原因は何でしょう・・
イベンドID 4688だけなので、もしかして以前に発生したalias変換問題でイベントログのバージョンが違う(形式が違う）から？

(この件は別のissueにしましょうか？）

_Originally posted by @YamatoSecurity in https://github.com/Yamato-Security/hayabusa/issues/392#issuecomment-1051261759_

**Comment by hitenkoku** [comment]
調査ログ：
- fb007ee3a65d4b881c582c0ca03937c628f91223 (develop/HEAD)→ 🙅 
- ecc8828921ae9c875fc98362a01903ed860f200a → 🙅 
- 46b0594150f79a15992cc451384f4e204c673dd3(v.1.0.0-r2) → 🙅

**Comment by hitenkoku** [comment]
@YamatoSecurity 確認したところ、v.1.0.0-r2の段階でこの事象は発生していました。
ただ、テストで%CommandLine%の変換を行うテストはいままでpullrequestの際に行われていた(そもそも通らないとマージできない)ようですので、イベントログと突合して調査を続けます

**Comment by hitenkoku** [comment]
@YamatoSecurity  イベントログを確認したところ、そもそもCommandLineが対象のログに無いことが原因のようです。おそらく、これは作成の際に仕様として話をしていた内容だったと理解しています(イベントレコード内に対象のじょうほうがなかったらそのままの文字列として表示)

また、一部NewProcessNameやNewProcessIDについても同様の現象が発生していることを確認しています。

**Comment by hitenkoku** [comment]
alias側に記載がないことが原因のようですね……eventkey_alias.txt側に追加してみます。

**Comment by YamatoSecurity** [comment]
調べて下さって、ありがとうございました。
DeepBlueCLIのsample evtのmany-evtx-security.evtxを見ています。
確かにCommandLineというフィールドが無いログもありました！ (2016年8月18日あたりのログ）その場合は無事に%CommandLine%が空に変換されています。ログのVersionが0です。
しかし、2016年9月のログ(Version 1)では、コマンドラインも記録されています。
(作者は恐らく途中でコマンドラインも記録するように設定を変えたと思われます）
Version 1ではCommandLineというフィールドがありますが、変換されません。

<img width="1073" alt="Screen Shot 2022-02-28 at 7 04 32" src="https://user-images.githubusercontent.com/71482215/155902343-96179098-e466-40ef-b9a6-c9453d90b573.png">

[4688-Not-Converting-CommandLine.csv](https://github.com/Yamato-Security/hayabusa/files/8149515/4688-Not-Converting-CommandLine.csv)

**Comment by YamatoSecurity** [comment]
Aliasを確認しましたが、CommandLine,Event.EventData.CommandLineなので、問題ないですよね？

**Comment by hitenkoku** [comment]
はい、aliasは問題ないです。

**Comment by hitenkoku** [comment]
詳細な情報をご提示いただき誠にありがとうございます。2016/8/18のログのみをみていました。Version1のところだと確かにCommandLineがログの中にあることを確認しました。

また、いただきましたcsvで2016年9月のログに限って確認してみましたが、%CommandLine%という文字列が存在していませんでした……

一旦csvを出力して全体の情報を洗い出しておきます。

**Comment by YamatoSecurity** [comment]
<img width="1487" alt="Screen Shot 2022-02-28 at 11 02 41" src="https://user-images.githubusercontent.com/71482215/155912241-06220542-1e00-45a9-b49d-0e0ee26dd8e2.png">
<img width="1060" alt="Screen Shot 2022-02-28 at 11 02 14" src="https://user-images.githubusercontent.com/71482215/155912248-b464c728-29bd-484e-ad19-8ff8b3fbf53a.png">

すみません、%CommandLine%が出力されているのは、2016/8/18です。

**Comment by hitenkoku** [comment]
情報提供ありがとうございます。それでは内部でのデバッグとかをしてみようと思います。

**Comment by YamatoSecurity** [comment]
大変失礼しました！
タイムスタンプをよく確認したら、原因が分かったと思います。
%CommandLine%が空に変換されたいる行は恐らくVersion 1でコマンドライン情報が無いため、空です。
<img width="1079" alt="Screen Shot 2022-02-28 at 11 15 34" src="https://user-images.githubusercontent.com/71482215/155913306-2840c4a4-689b-46ea-90b0-3e2ad9d58fd9.png">

2016/8/18のログを確認したら、%CommandLine%になっている行はVersion 0 でそもそもフィールドが無いため、%CommandLine%のままになっています。（正しい動きです）

<img width="1067" alt="Screen Shot 2022-02-28 at 11 14 26" src="https://user-images.githubusercontent.com/71482215/155913467-b7611174-ea62-4098-9f37-050ffb93a631.png">

Hayabusa側では問題が無いので、4688のルールをVersion 1用とVersion 0用の２つを用意して対応したいと思います。

**Comment by hitenkoku** [comment]
連絡が遅くなってしまい申し訳ございません。YamatoSecurityさんの言っている通り、やはりCommandLineという要素が存在しているかというところだったようでhayabusa側では問題がないようでよかったです。それではこのissueはcloseさせていただこうと思います。
