### ISSUE TITLE
-u オプションで更新されない

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#422]
Expected Behavior:
hayabusa -uした後に設定ファイルが更新されるはずですが、更新されません。
(Code block driver loadのexclude rule等が反映されない）

<img width="1105" alt="Screen Shot 2022-02-27 at 7 44 10" src="https://user-images.githubusercontent.com/71482215/155863324-34117da4-1c7a-4cb5-8d8e-5d620b61232d.png">

最新のdevelopブランチで検証しています。
`git clone https://github.com/Yamato-Security/hayabusa.git --recursive`
で最初にレポジトリをクローンしました。その後hayabusa-rulesレポジトリが更新されていますが、hayabusa -uを実行しても更新されません。

**Comment by hitenkoku** [comment]
git2-rsを確認したところ、ローカル側で所持している対象のコミットに合わせるように更新するのがsubmodule.updateのようです。

gitでは`git submodule --remote`でリモートレポジトリ側の最新コミットを取得して更新することができるので、同様のことがgit2-rsでできるかどうか確認してみます。

**Comment by hitenkoku** [comment]
備忘メモ:以下のようなオプションを付けても更新はされなかった。パスからRepositoryとして取り込み実行する形を試してみます

```Rust
        let hayabusa_repo = open_result.unwrap();
        let submodules = hayabusa_repo.submodules()?;
        let mut update_opts = SubmoduleUpdateOptions::new();
        let mut checkout_opts = CheckoutBuilder::new();
        let fetch_opts = FetchOptions::new();
        update_opts.allow_fetch(true);
        checkout_opts.force();
        checkout_opts.recreate_missing(true);
        checkout_opts.allow_conflicts(true);
        update_opts.checkout(checkout_opts);
        update_opts.fetch(fetch_opts);


```

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応が完了しました。 #424 でレビュー依頼を出しているのでご確認のほどよろしくお願いいたします。

今回の事象の原因は「そもそも、submodule自体は特定のコミットを指すものであり、git submodule update自体はリモートを見ないと最新のコミットに合わせるということはしない」でした。

例えば、hayabusaで、あるときにA時点でのsubmoduleを参照していて
hayabusa側のリモートレポジトリでその参照を変更した(B時点)という場合には今までのupdateオプションでも対応できていました。

今回の場合はhayabusa-rulesの最新版のコミットを見に行くことになるため、更にmergeの処理が必要でした。

ひとまず、ユーザが特に修正をしていないという前提でfast-forwardのmergeのみで対応をするようにしてみました。ご確認のほどよろしくお願い致します。

**Comment by hitenkoku** [comment]
close by #425 merged
