### ISSUE TITLE
Clippyの導入

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#428]
Rust Report Cardのスコアを上げるためにClippyを導入する。
https://rust-reportcard.xuri.me/report/github.com/Yamato-Security/hayabusa

https://qiita.com/msakuta/items/db0ad407ff39b649a9a6

**Comment by hitenkoku** [comment]
@YamatoSecurity Clippyは標準で実行できるので、push時に以下のgithub actionを入れることでよろしいでしょうか。(各個人で実行するのは前提として……)

https://github.com/actions-rs/clippy-check

**Comment by YamatoSecurity** [comment]
まず警告が出ないようにソースコードを修正してから、github action等でPRをマージする前にclippyチェックを行うのはどうですか？

**Comment by hitenkoku** [comment]
承りました。いったんソースコードの修正は #430 で対応します。
とはいえ、指摘内容によっては関数の型などを変えなければならないため　hach1yon さんにもご確認いただきたいところではあります。特にSelectionNodeとかのBoxの取り扱いについては自信がないです……

**Comment by hach1yon** [comment]
@hitenkoku 
v1.1のリリースに間に合うかは微妙ですが、みておきます。今週会議出ます。

**Comment by hitenkoku** [comment]
@hach1yon  ありがとうございます！

@YamatoSecurity  v1.1に急いで投入するかどうかは、ちょっと会議で話をさせてもらいながら決めさせていただけると大変助かります。

**Comment by hitenkoku** [comment]
#430 は対応完了したため、CIに投入できるかどうかを検討します。

**Comment by hitenkoku** [comment]
CIへの投入が #429 で対応しました。mainブランチに投入完了次第このissueはcloseします
