### ISSUE TITLE
[bug] --update-rulesが2回目で失敗する

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#432]
**Describe the bug**
hayabusa -uを２回実行すると失敗してしまう。

**Step to Reproduce**
hayabusa -uを２回実行する

**Expected behavior**
ルールが更新される

**Screenshots**
![Update](https://user-images.githubusercontent.com/71482215/155937881-0b4e18b4-bcba-4a38-afa2-c48cd65851f0.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - hayabusa version [e.g. v1.1.0 release candidate]

**Additional context**
最初のダウンロードも更新時も`[ERROR] Failed to open the git repository`というエラーが表示されますが、必要ですか？無くせますか？
何が失敗しているのかよく分かりません。

**Comment by hitenkoku** [comment]
最初の「Failed to open the git repository」はそのフォルダ内に.gitフォルダがないかを確認して、なければそのままgit cloneを行おうとするという流れになります。
今回のrelease用を作成するために.gitフォルダや.gitmoduleファイルを除外とかはしておりませんでしょうか。

以下の件は削除しておきます。

> 最初のダウンロードも更新時も[ERROR] Failed to open the git repositoryというエラーが表示されますが、必要ですか？無くせますか？
> 何が失敗しているのかよく分かりません。

**Comment by hitenkoku** [comment]
hayabusaフォルダ配下に.gitがある前提で作成をしており、.gitがない場合はhayabusa-rulesをgit cloneするというロジックになっている。
Release用に.gitフォルダを削除しているため、常にこのcloneを行おうとしてしまう。
git cloneの条件を修正し、submoduleへの対応も修正するように対応します。

**Comment by hitenkoku** [comment]
@YamatoSecurity #433 で対応が完了しました。私の方で2回実施してもエラーが出ないことを確認しました。ご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
close by #425 merged
