### ISSUE TITLE
Investigation: Does openssl crate need to be statically compiled?

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#438]
https://blog.davidvassallo.me/2021/06/10/lessons-learned-building-statically-linked-rust-binaries-openssl/

macOS/Linuxではopensslを静的にコンパイルする必要がある？
Windowsは？

**Comment by hitenkoku** [comment]
利用しているのはgit2-rs(update機能で利用しているcrate)ですが、以下ソースコードに記載がありました。
SSL対応のためにOpenSSLをLinux/MacOSでは利用しており、Windowsでは必要ないようですね。

- https://github.com/rust-lang/git2-rs/blob/64d849b8436a6b77a2636693a7523b5cac9cd993/src/lib.rs#L722

**Comment by hitenkoku** [comment]
MacOSについてですが、OpenSSLを利用していることで色々と問題が起きているようです……

- https://github.com/rust-lang/git2-rs/issues/540
- https://github.com/rust-lang/git2-rs/issues/229
- https://github.com/kbknapp/cargo-outdated/issues/187

他レポジトリでの対応
- https://github.com/arxanas/git-branchless/commit/43c1f64df16b6c8f3a97e0e2cf7c24b42d768b38

**Comment by YamatoSecurity** [comment]
なるほど、情報ありがとうございます！
後で古いmacOSとか他のLinuxディストロで実行できるかどうか試してみます。
Windowsは大丈夫そうで良かったです。

**Comment by YamatoSecurity** [comment]
<img width="1032" alt="Screen Shot 2022-03-10 at 18 14 13" src="https://user-images.githubusercontent.com/71482215/157632738-c3aee497-ef82-4ebd-8031-aeed80521701.png">

SSLを静的にコンパイルする必要がありました。　（T_T）

**Comment by YamatoSecurity** [comment]
Fixed in https://github.com/Yamato-Security/hayabusa/pull/437
