### ISSUE TITLE
#395 #396の実装のチューニング

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#440]
#396 (issueとしては #395 )の実装でチューニングできる個所がないか確認する

**Comment by hach1yon** [comment]
@hitenkoku 
これはチューニングというより、そもそも対応不要な開発項目に見えます。次回ミーティングで相談させてください。

**Comment by hach1yon** [comment]
調査したところ、検知する際にタブ等を削除する処理でパフォーマンスが低下しているようです。
CSV出力する際の処理はあまり関係なさそうです。

**Comment by hitenkoku** [comment]
検知をする際に、evtxから取得したデータの中にタブや改行が入っているものがあるため検知が一致しないという問題があったのでこのように対応しています(#395)

パフォーマンスへの影響を少なくするため、置換対応を行うキーを設定することで、なるべく削除を行う回数は減らしています。

**Comment by YamatoSecurity** [comment]
`./target/release/hayabusa -r ../hayabusa-rules/hayabusa/default/alerts/Security/4674_PossibleHiddenServiceAttempt.yml -d ../hayabusa-sample-evtx`
という風に検証できるevtxを調べました。
AccessMaskが１つの場合はタブ・改行等がありません。（ないと思います）
例：https://github.com/Yamato-Security/hayabusa-sample-evtx/blob/main/DeepBlueCLI/eventlog-dac.evtx

問題は複数がある場合です。
例：https://github.com/Yamato-Security/hayabusa-sample-evtx/blob/main/EVTX-to-MITRE-Attack/EVTX_full_APT_attack_steps/ID5145-4624-DonPAPI%20full%20extraction.evtx

別の問題で、`AccessMask: %%1537%%1538%%1539%%7184%%7185%%7186%%7187%%7188%%7189%%7190%%7191%%7192`という風に出力されますが、読みにくいのでできればAccessMaskの間にスペースを入れたいです。

**Comment by hach1yon** [comment]
@hitenkoku 
ちょっと説明が少ないので会議で話し合ったことを書いておきます。

## 現状コードの障害
現状のコードではAccessMaskをはじめとする、フィールドの値にタブや改行が含まれるケースで、想定通りに検知できないケースがあります。

### 検知できないケース
現状のコードでは下記のようなケースで検知できない。上記の通り、AccessMaskに複数のコード値が設定されるケースはあるらしい。
* EventLogのAccessMaskの値
    * `AccessMask: "%%3333 %%4444"`
* ルールファイルのselectionの設定
    * `AccessMask: "*3333*"`

### 原因
wildcardの`*`を使用した場合、内部的には`.*`という正規表現で置き換えられる。上記のルールでは`.*3333.*`という正規表現に置き換えられる。正規表現の`.`はタブ文字や改行文字にHitしないので、正しく検知できない

### 解決策
wildcardの`*`を`[\s\S]*`に置き換える。containsやstartswith、endswithも同様。

## タブ文字削除のパフォーマンス影響
現状ではAccessMask等の一部のフィールドの値について、検知する際に空白やタブ文字等を削除している。これによって、実行時間が3割程度増えてしまっている。

### 問題点
現在は検知する際に毎回空白文字等の削除を行っている。このロジックだと、Evtxが1レコードのみであっても、ルールが1000ファイルある場合、同じ削除処理が1000回実行されてしまう。

### 改善策
Evtx1レコードに対して削除処理が1回しか実行されないように修正する。

**Comment by hach1yon** [comment]
なんか、Rustの正規表現だとRegex::new("[\s\S]*")がすごく遅い。\Sというパターンが入るとすごく遅いので、[.|/s]*に変更

**Comment by hach1yon** [comment]
Rustだと/sが使えないことに気づいたので、(.|\\a|\\f|\\t|\\n|\\r|\\v)*に変更。

**Comment by hitenkoku** [comment]
説明ありがとうございます。理解できました。それでは #396 はrevertしておきましょうか？

**Comment by hach1yon** [comment]
もうプルリク作ってしまったので、そちらを確認してもらえれば大丈夫です。

**Comment by hach1yon** [comment]
AccessMaskが１つの場合でも、最後にタブ文字等が入るらしい。下記evtxをxml形式で出力すると確かに入っている。

https://github.com/Yamato-Security/hayabusa-sample-evtx/blob/main/DeepBlueCLI/eventlog-dac.evtx
