### ISSUE TITLE
rules/configではなく、./config/regexとエラーログが出る。

### ISSUE THREAD

**Issue by kazuminn** [Yamato-Security/hayabusa#443]
最新のdevelopを実行すると、以下のように、エラーログが出る。

本来なら、rules/config...とならないといけないと思うのに、./config/rege...となってる。
また、エラーが出ちゃうのがおかしい。

windows11

```
[WARN] Cannot open file. [file:./config/regex/detectlist_suspicous_services.txt]
[WARN] Cannot open file. [file:./config/regex/allowlist_legitimate_services.txt]
```

ちらっと、コードを見たけど、分からない。

**Comment by hitenkoku** [comment]
#441 でmain側で対応していた内容をdevelopブランチに対応していないことが原因です。私が対応します。

**Comment by hitenkoku** [comment]
#445 で対応完了のためcloseします。
