### ISSUE TITLE
-Cオプションでのrulesのconfigフォルダの指定

### ISSUE THREAD

**Issue by kazuminn** [Yamato-Security/hayabusa#456]
/rules/...の設定ファイルを見に行くように決め打ちされてるところがありますが、/rules/を完全に無視で、-rオプションの設定ファイル使いたい時があるので、「-rのパス/config」を見に行かないといけないと思う。

https://github.com/Yamato-Security/hayabusa/blob/main/src/filter.rs#L27

とか。

他にもあるかを探す必要がある。

**Comment by hitenkoku** [comment]
本件実装するかどうか打ち合わせで確認の上対応しましょう

**Comment by itiB** [comment]
単純にはいかない
ex. `./hayaubsa-rules/sigma/sysmon` だけを試そうと思ったとき、`./hayaubsa-rules/sigma/sysmon/config` がないためバグる

→ Configとルールを混ぜてしまったのが問題だった、、、
→ 設定ファイルの置き場所を再考する必要あり

**Comment by YamatoSecurity** [comment]
指摘ありがとうございます！
確かにルールの検証で`-r`を指定した時に(例：`-r ../hayabusa-rules`)、`./rules/config/`配下の設定ファイルではなく、`../hayabusa-rules/rules/config`の設定ファイルを使いたいです。

一番注意しないと行けないのは、rulesのルートフォルダを指定しない場合です。例えば、hayabusaのルールだけ検証したい時は`-r ../hayabusa-rules/hayabusa`や`-r ./rules/hayabusa`を指定しますが、このディレクトリにconfigディレクトリが無いので、エラーになると思います。なので、再帰的にconfigフォルダを探す必要が出てくる気がします。
例えば`-r ../hayabusa-rules/hayabusa/events/Security`が指定されたら、
`../hayabusa-rules/hayabusa/events/Security/config` -> ない
`../hayabusa-rules/hayabusa/events/config` -> ない
`../hayabusa-rules/hayabusa/config` -> ない
`../hayabusa-rules/config` あった！ -> 使う
という風に探さないといけないのでは？

ややこしくなりそうのであれば、新しい`-C --config 'Specify the config folder.'`オプションを追加するのはありかもしれません。(オプションが増えてしまうデメリットがあるけど）

あと、Clap version 3にアップデートすることで解決できるそうだけど、Clap v3のアップデートは大きな修正が必要があるので、今回のv1.2のリリースに入れるのは厳しいです。取り敢えずv1.3のmilestoneに設定しました。

もし、誰かがもっと良い案があれば、ぜひ情報共有して下さい。
@kazuminn さんは、直せそうですか？

**Comment by hitenkoku** [comment]
@YamatoSecurity  @itiB コメントありがとうございます。

仕様として再帰的に探索をすることはやめて、最初のissueに記載した通り-rで選択したフォルダの直下にconfigフォルダを指定するか、YamatoSecurityが書いていた通り他のオプションで直接configフォルダを指定するの2択になると思います。再帰的な探索はやると処理に大きな影響を与える可能性もあるのでかなり厳しいと思います。

個人的には-cオプションで指定するのが一番わかりやすいかなぁと思っています。

@itiB 
ClapをVer3で解決するという話がありますが、これってどのような機能を利用するのでしょうか？少し想像がつかなかったので教えていただけると助かります

**Comment by itiB** [comment]
@hitenkoku Clapはバージョンアップでデフォルト値を柔軟に使えるようになり
ルールディレクトリをデフォルト値として./rulesにできるから定数で持たなくて良くなると思います！
という話でした、しかしながら上記のコメントの問題がありここはそういった対処では解決しない深い問題だ…となり1.3に入りました

**Comment by kazuminn** [comment]
@YamatoSecurity 

> @kazuminn さんは、直せそうですか？

マイルストーンv1.3なので、できると思います。

私も-cオプションで指定するのがいいと思います。

**Comment by hitenkoku** [comment]
@YamatoSecurity  ` -C ` オプションを追加して対応する形で実施するのであれば、現在手が空いている私の方で対応しますがいかがでしょうか。

**Comment by kazuminn** [comment]
Dさんに譲ってOKです。

**Comment by hitenkoku** [comment]
@YamatoSecurity  Rust側の実装はおおむね作成が完了したのですが、1点確認をしたいです。

今回のissueではrulesフォルダのconfigをオプションで指定をするという話でしたが、
rules側で指定されているregex関係はrules側(ymlファイル)の方で指定をしているのですが、どうしましょうか。

ymlファイルの読み込んだものを置き換えるような処理を含めますか？
