### ISSUE TITLE
multi mapping to one alias in eventkey_alias.txt

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#460]
## Expected feature

- enable setting same alias (but another value) in eventkey_alias.txt

``` csv
A, Event.EventData.xxx
A, Event.EventData.yyy
```

ex.`Query, Event.UserData.Query `(built-in WMI log) , `Query,Event.EventData.Query`(sysmon Event ID 19)

**Comment by YamatoSecurity** [comment]
相談したら、複数のaliasを設定したら良いという結論になりました。
SigmaのWMIルールを確認したら、
Sysmonの場合は`query`、ビルトインログの場合は`Query`を使っているので、
```
query,Event.EventData.Query
Query,Event.UserData.Query
```
という風に設定しておきます。

**Comment by hitenkoku** [comment]
ありがとうございます。キーは大文字小文字を区別するので、それであれば問題ないと思います。
それでは、特に対処は不要と判断しましたので、このissueは閉じておきます。
もし大文字小文字も含めてキーが一致してしまっているケースがあればまた別途issueを立てて対策をしていく形にさせてください。
