### ISSUE TITLE
Change yaml-rust crate to serde-yaml or yaml-rust2

### ISSUE THREAD

**Issue by itiB** [Yamato-Security/hayabusa#461]
Now Hayabusa using [yaml-rust](https://github.com/chyh1990/yaml-rust) to read YAML files.
We want to change this crate to [serde-yaml](https://github.com/dtolnay/serde-yaml)

- Reason
  - yaml-rust can't write yaml file.
  - yaml-rust' latest update is a long time ago

**Comment by itiB** [comment]
https://serde.rs/examples.html

**Comment by hitenkoku** [comment]
メモ: 構造体にする必要があり、修正コスト大

**Comment by YamatoSecurity** [comment]
`yaml-rust` is lower-level so may provide petter performance and lower memory usage than serde. the serde crate is supposed to be easier to program with though.
I just noticed that there is a newer more maintained version of `yaml-rust` called `yaml-rust2`, so it might be better to upgrade to this than `serde-yaml`

https://crates.io/crates/yaml-rust2

**Comment by YamatoSecurity** [comment]
`serde-yaml` has been deprecated all of a sudden and it is recommended to upgrade to `yaml-rust2`

https://users.rust-lang.org/t/serde-yaml-deprecation-alternatives/108868/19
