### ISSUE TITLE
timeline_event_infoの不要なコードの削除とファイル名の変更

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#462]
developブランチでhttps://github.com/Yamato-Security/hayabusa/blob/develop/config/timeline_event_info.txt を更新しました。
detect_flgとcommentの維持が大変なので、消したいです。
ついでに「timeline_event_info.txt」を「statistics_event_info.txt」に名前変更をお願いします。

**Comment by hitenkoku** [comment]
detect_flgとcommentは今 timeline_event_info.txtでは使われていなさそうなので、
Rust側の処理を修正してしまえば対応できると思います。

@garigariganzy  もし、わからないことがあったら連絡してくれればこちらでも確認します。

**Comment by garigariganzy** [comment]
＠YamatoSecurity さん ＠hitenkoku さん　了解しました。確認します。
