### ISSUE TITLE
Check Channel as well in Metrics feature

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#463]
複数のChannelが同じイベントIDを使うので、イベントタイトルを調べる時にChannelも確認する必要があります。
Channel情報が書いてあるCSVを用意しました。（添付しました。)
今後これを使いたいです。
また、もしpretty tables等でよりきれいに表示できそうでしたら、それもお願いしたいです
[EID Mappings.csv](https://github.com/Yamato-Security/hayabusa/files/8348646/EID.Mappings.csv)
。

**Comment by YamatoSecurity** [comment]
@garigariganzy ChannelとEIDマッピングの設定ファイルをhayabusa-rulesレポジトリの`config/rules/channel_eid_info.txt`というファイルに置きました。`-u`を実行したら、ダウンロードされると思います。ご利用ください。現在、`-M`はEIDしか見ていないので、誤った結果が沢山出ています。早めに修正したいのですが、いつごろできそうですか？（遅くても10/9までに修正しておきたいので、もし間に合わなさそうでしたら、こちらも @hitenkoku  にお願いして良いですか？）

**Comment by YamatoSecurity** [comment]
別件ですが、`./hayabusa-1.7.0-mac-intel -d ../hayabusa-sample-evtx -M`を実行したら
<img width="1087" alt="Screen Shot 2022-10-02 at 4 14 37" src="https://user-images.githubusercontent.com/71482215/193424835-8265a5d1-f5ac-44bb-82cc-f7ef6f06a036.png">

上位２件のChannelがnullになっていますが、空のチャンネル名は無いはずです。（私の認識では）
このEIDは何なのか分かりますか？ @hitenkoku

**Comment by garigariganzy** [comment]
> @garigariganzy ChannelとEIDマッピングの設定ファイルをhayabusa-rulesレポジトリの`config/rules/channel_eid_info.txt`というファイルに置きました。`-u`を実行したら、ダウンロードされると思います。ご利用ください。現在、`-M`はEIDしか見ていないので、誤った結果が沢山出ています。早めに修正したいのですが、いつごろできそうですか？（遅くても10/9までに修正しておきたいので、もし間に合わなさそうでしたら、こちらも @hitenkoku にお願いして良いですか？）

返信遅れて申し訳ございません。
Channelを含めて集計し、Eventtileを付与する処理は作成しましたので
-Mで見ているconfigファイルを「statistics_event_info.txt」から「channel_eid_info.txt」を見るように修正して動作を確認いたします。少々、お待ちください。

**Comment by hitenkoku** [comment]
`
本件確認します。

> 別件ですが、`./hayabusa-1.7.0-mac-intel -d ../hayabusa-sample-evtx -M`を実行したら <img alt="Screen Shot 2022-10-02 at 4 14 37" width="1087" src="https://user-images.githubusercontent.com/71482215/193424835-8265a5d1-f5ac-44bb-82cc-f7ef6f06a036.png">
> 
> 上位２件のChannelがnullになっていますが、空のチャンネル名は無いはずです。（私の認識では） このEIDは何なのか分かりますか？ @hitenkoku

**Comment by hitenkoku** [comment]
@YamatoSecurity  別件の内容は #727 で調査内容を記載しました。お手数ではございますが、内容が違う場合はできれば別issue対応をさせていただきます(重複したissueの作成を防ぐため)
