### ISSUE TITLE
[bug] .gitディレクトリにあるYMLが読み込まれてしまう

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#472]
**Describe the bug**
.gitディレクトリにあるYMLが読み込まれてしまって、パースエラーが発生します。

**Step to Reproduce**
hayabusa-rulesのレポジトリでブランチ名に.ymlが入っているのが原因っぽいです。
hayabusa-rulesをテストする際に`-r ../hayabusa-rules`等を指定すると、パースエラーが起こってしまいます。

**Expected behavior**
可能であれば、.gitにある.ymlファイルを無視したいです。

**Screenshots**
<img width="1121" alt="Screen Shot 2022-03-30 at 15 15 06" src="https://user-images.githubusercontent.com/71482215/160764734-478cc2a7-6909-45b4-9477-6638c92cc1e2.png">

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa develop with hayabusa-rules repo

**Comment by hitenkoku** [comment]
承りました。対応としてはパスの中に `/.git/` が入っている場合は無視をするように処理を追加するようにしておきます。

**Comment by YamatoSecurity** [comment]
助かります！ありがとうございます！
