### ISSUE TITLE
Mitre Attackの詳細なTactic番号を出力しない

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#477]
https://github.com/Yamato-Security/hayabusa/pull/469 のPRでアラートレベルとタイトルの間にMitre Attack Tacticが入るようになっています。それで良いのですが、attack technique IDが沢山あると、とても長くなって、ID番号をパッと見ても誰も分からないので、ID番号を無しにして、省略しながら以下のtacticだけを出力したいです：
```
attack.impact -> Impact
attack.initial_access -> Init. Access
attack.execution -> Exec.
attack.lateral_movement -> Lat. Movement
attack.persistence -> Persistence
attack.privilege_escalation -> Priv. Esc.
attack.reconnaissance -> Recon.
attack.collection -> Collection
attack.command_and_control -> C2
attack.credential_access -> Cred. Access
attack.defense_evasion -> Evasion
attack.discovery -> Discovery
attack.exfiltration -> Exfil.
attack.resource_development -> Resource Dev.
```

また、ルールのdetailsのところで、区切りを`  :  `から` | `に変えているので、区切りを合わせて頂けますか？

**Comment by hitenkoku** [comment]
@YamatoSecurity  この処理ですが、別のコンフィグファイルを参照する形にしますか？それともハードコーディングで対応するようにしますか？
attckにかぎらず他のタグの変換を想定するのであれば場合、コンフィグファイルを参照して取る形をおすすめします。

**Comment by hitenkoku** [comment]
#483 で別途コンフィグファイルを利用してフィルタリングする方法で実装しました。

**Comment by YamatoSecurity** [comment]
<img width="1729" alt="Screen Shot 2022-04-14 at 16 05 54" src="https://user-images.githubusercontent.com/71482215/163332387-7eb0377d-5ff3-4f9d-bba7-dfd80dd532fc.png">

@hitenkoku Countルールはタグのままになっていますが、countルールも設定ファイルに書いてあるMitre Attack Tacticだけにできますか？

**Comment by hitenkoku** [comment]
対応可能かと思われます。確認します
