### ISSUE TITLE
[bug] 64ビットシステム上で32ビットバイナリを使うと分かりにくいエラーで失敗する

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#478]
**Describe the bug**
64ビットシステム上で32ビットバイナリを実行すると、`No evtx found`や`An error occurred while trying to read input.`という不思議なエラーメッセージが出力され、解析が失敗します。
例えば、`hayabusa-1.1.0-windows-x86.exe -l `を実行すると、`No evtx found`というエラーが返ってきます。

**Step to Reproduce**
`hayabusa-1.1.0-windows-x86.exe -l`や`hayabusa-1.1.0-windows-x86.exe -f c:\Windows\System32\winevt\Logs\System.evtx`

**Expected behavior**
勉強会で64x端末で間違えてhayabusa-1.1.0-windows-x86.exeを使っていた人が何名か居て、変なエラーが出ていたので、困っていました。
可能であれば、64システムでhayabusa-1.1.0-windows-x86.exeを実行すると、「Please run the x64 binary on 64-bit systems.」というエラーメッセージを表示してあげた方が良さそうです。

**Screenshots**
<img width="691" alt="Screen Shot 2022-04-03 at 6 13 34" src="https://user-images.githubusercontent.com/71482215/161401698-3793b28e-467c-4845-8492-2e74aa9f6c6c.png">

<img width="1099" alt="Screen Shot 2022-04-03 at 6 24 57" src="https://user-images.githubusercontent.com/71482215/161401718-6e7b379c-1367-4d7e-b639-2e2854a7a852.png">

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - hayabusa version v1.1.0

**Comment by hitenkoku** [comment]
本件、ファイル名と実行端末のアーキテクチャの組み合わせが一致しない場合にエラー表示を出して返すようにします。
(exeファイルのアーキテクチャを判定する方法がファイル名のみしかなさそうなので)
