### ISSUE TITLE
remove -c --color

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#481]
## log

colorオプション付けているのはcmd.exeやpowershell.exeで動作しない。現状の実装だとcolorオプション付けないとまずい。
ただ、color対応していると見せかけて、一番用途の多いcmd.exeやpowershell.exeでは使えないのはバグに近いので、こういう対応をしたうえでcolorオプションを消すorデフォルトで色を付けるのがベスト。 (by hach1yon )

**Comment by hitenkoku** [comment]
colorオプションについては一応但し書きでtruetype 対応のものにかぎるという記載をしています。rustのコンパイル時などにカラー表示で利用している機能を活用できないかの検討もありましたが、最初の要望として色はコンフィグで好きに設定できるという要求を対応するために今のcrateで対応をしていた

**Comment by hitenkoku** [comment]
https://github.com/rust-lang/cargo/blob/9d754ed085a97d486cda45308a3c749c818305a5/src/cargo/core/shell.rs でcargoコマンドの際に色がつけられる。

cargoで利用している crateの色指定は https://docs.rs/termcolor/latest/termcolor/enum.Color.html で指定されており、rgbでの指定はWindowsは対応していない旨が明記されている。

**Comment by hach1yon** [comment]
[shell.rs](https://github.com/rust-lang/cargo/blob/9d754ed085a97d486cda45308a3c749c818305a5/src/cargo/core/shell.rs )で使われている、termcolorは全8色で白と黒を除いても6色あります。levelは全部で5つしかないので、この中から適当なものを選べばいいと思いますが、どう思います。
termcolorを使うとrgbを自由に選べるという今の機能はなくなりますが、それよりもWindowsのコマンドプロンプトで動作させる方が優先順位が高いように思えます。

あと、colorオプションの有無というより、デフォルトでcolorが付いてほしいという気持ちの方が強いです。色を付けるのに毎回colorオプションを付けるのは面倒なので。

**Comment by hitenkoku** [comment]
もともとの要望としてターミナル等の背景色が人によって異なるため自由に変更できるようにしたいという話を @YamatoSecurity からもらっていたので、実施するかの判断を一旦打ち合わせで決めさせてください。

作った後に「やっぱりこっちのほうが」と言われても厳しいので。

**Comment by hach1yon** [comment]
分かりました、打ち合わせできめましょう。

ターミナルの背景色は殆どのツールが黒とか白であることを前提に作られていると思うので、そういうが理由なら殆ど考慮する必要はなさそうですね。

**Comment by hitenkoku** [comment]
コマンドプロンプト等の背景色を取るのは無理があるので、1パターンだけでよいかとも思っています。ダークモードと背景白の場合とか考えるとオプションが増えるので、できれば避けたいと思っています

**Comment by YamatoSecurity** [comment]
デフォルトでカラー出力するのであれば、実装する前にデフォルトのWin 7でも無事に表示されることを確認したいです。
PowershellとCommand Promptの背景はデフォルトで黒なので、カラーの選択はダークモード前提で良いと思います。
環境によってカラー出力で見づらくなる可能性があるので、--no-colorのカラー無しのオプションを追加する必要が出てきます。
また、Windows Terminalのバグで出力が途中で止まってしまっているけど、True Color出力でそれを暫定的に回避しています。
True Colorじゃなくなったら、出力が止まってしまうバグで出てくるので、その対応も考えないといけません。

**Comment by hach1yon** [comment]
まず、--no-colorは不要です。毎回オプションで指定するのは面倒なので、設定ファイルで色を付けるかどうか指定できるようにした方が、毎回オプション指定する手間が減るので、そちらの方が良いです。

windows terminalについては、現在は--colorで回避してますが、--outputでも回避できないですか?
それか、windows terminalはどちらにしてもバグがあるので、windows標準のwindows console hostを使用して下さいという回避方法で問題ありません。

**Comment by hach1yon** [comment]
win7で正しく動作するかは不明ですが、設定で変更できることを明記しておけば、そこまで問題ではないです。

**Comment by hitenkoku** [comment]
> windows terminalについては、現在は--colorで回避してますが、--outputでも回避できないですか?
はい --outputでも回避できます

**Comment by hach1yon** [comment]
あと、これとは別ですが、windows terminalで出力が止まる問題については、改行コード等をスペースに置換する対応をしたと思いますが、それと同じような対応をすれば解決できます。
rust標準のcharにis_controlという関数があるので、その関数を使ってコントロールコードの判別も簡潔にできそうなので、対応も容易だと思います。

**Comment by hitenkoku** [comment]
以下の件は #485 で対応しました。

> あと、これとは別ですが、windows terminalで出力が止まる問題については、改行コード等をスペースに置換する対応をしたと思いますが、それと同じような対応をすれば解決できます。 rust標準のcharにis_controlという関数があるので、その関数を使ってコントロールコードの判別も簡潔にできそうなので、対応も容易だと思います。

**Comment by hitenkoku** [comment]
本件、--colorを削除しtermcolorから選定する形で対応する。

**Comment by hitenkoku** [comment]
現在のlevel_color.txtの内容から以下の色で固定します。

Critical: Red
High:Yellow
Medium: Cyan
Low: Green
Informational: White

**Comment by hitenkoku** [comment]
termcolor crateのBufferWriterがio:Writeを所持していないため、現在のemit_csvの関数の引数として適用ができない問題が発生中。
