### ISSUE TITLE
Channel列の追加

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#504]
イベントIDだけでは、どのログなのか分からないので、イベントID列の左側にChannel列を追加したいです。
(標準出力＋ファイル保存)
チャンネル名がかなり長い場合もあるので、設定ファイルで省略します。
主なログの省略を添付しました。

[ChannelAbbreviations.txt](https://github.com/Yamato-Security/hayabusa/files/8499185/ChannelAbbreviations.txt)

**Comment by hitenkoku** [comment]
closed due to resolve merge develop
