### ISSUE TITLE
[bug] ルールを更新できない

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#507]
**Describe the bug**
`-u`を実行したら、以下のエラーで失敗します：
```
./hayabusa-1.2.0-mac-intel -u -q
Attempting to git clone the hayabusa-rules repository into the rules folder.
[ERROR] Failed to git clone into the rules folder. Please rename your rules folder name. 'rules' exists and is not an empty directory; class=Invalid (3); code=Exists (-4)
[ERROR] Failed to update rules. Error { code: -1, klass: 0, message: "" }
```

**Step to Reproduce**
v.1.2.0のリリース.zipをダウンロードして、そのまま更新しようとしています。

**Environment (please complete the following information):**
 - OS: macOS
 - hayabusa version 1.2.0

**Comment by hitenkoku** [comment]
rulesフォルダがすでに存在している場合のclone失敗のエラーのようです。確認します

**Comment by hitenkoku** [comment]
rulesフォルダがすでに存在している場合のclone失敗のエラーのようです。確認します

**Comment by YamatoSecurity** [comment]
前のバージョンではv1.1.0.zipをダウンロードして、そのままルールを更新できた気がします。
もしかして私が.zipを作った時にgit --recursiveでルールを取得したせいかもしれません。
でしたら、--recursiveを使わないで、rulesは最初から`-u`で取得する必要があるかもしれません。
v1.2.0のzipを作り直してみます。

**Comment by YamatoSecurity** [comment]
.zipを作り直しました。これで直ったと思いますが、念の為そちらの環境でも確認をお願いできますか？
これでいけたのであれば、ドキュメンテーションの方では--recursiveの手順を削除して、コンパイルした後、-uでルールと設定ファイルを取得するように手順を更新しておきます。

**Comment by hitenkoku** [comment]
ありがとうございます。今から.zipの確認をしますが、バグと言っている事象についてはこちらでも確認しました。
原因はrulesフォルダに.gitフォルダはない状態なのでgit cloneを実施しようとするのですが、
rule関連のファイルがいることでgit cloneを実行しようとしてすでにファイルがあるのでNGを出して今回の事象になっているようです。

**Comment by hitenkoku** [comment]
@YamatoSecurity ご対応ありがとうございます。新たに作成されたzipファイルでエラーが発生せずに -u が実行できることを確認しました。ドキュメントの修正をしていただけるとのことでありがとうございます。ぜひよろしくお願いいたします。

**Comment by YamatoSecurity** [comment]
<img width="1549" alt="Screen Shot 2022-04-22 at 10 13 35" src="https://user-images.githubusercontent.com/71482215/164578456-93601b28-f2ba-48b7-87bf-eda3e7dfbe29.png">

hard resetの修正で逆に--recursiveだとupdateできますが、--recursiveオプションを付けない場合は上記のエラーが出てしまいます。
急ぎではないので、時間がある時に見て頂けますか？--recursiveを忘れる人も多そうなので、以前のように--recursiveを付けなかった場合でも、更新できたら嬉しいです。少なくても、もっと分かりやすいエラーメッセージを出した方が良さそうです。(Please add --recursive when performing a git cloneとか）

**Comment by hitenkoku** [comment]
@YamatoSecurity  失礼致しました。エラーの原因はrulesフォルダにレポジトリがない(--recursiveがないとこうなる)ときに誤ってreset --hardをするためにrulesのレポジトリを参照しようとしたことでした。

#516 で対応を冴えていただきましたのでお手数をおかけしてしまい申し訳ございませんがご確認のほどよろしくお願いいたします。
