### ISSUE TITLE
level_tuning.txtをhayabusa-rulesレポジトリで管理したい

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#511]
今気づいてすみません。。
level_tuning.txtはルールと一緒に頻繁に更新したいので、hayabusa-rulesの方で管理したいです。
今https://github.com/Yamato-Security/hayabusa-rules/pull/51 でそちらのconfigディレクトリにlevel_tuning.txtを置きます。

**Comment by hitenkoku** [comment]
ファイルの参照先を変える必要が出てくるのでこちらの方も修正を書けておきます。

**Comment by hitenkoku** [comment]
closed due to resolve merge develop
