### ISSUE TITLE
[bug] rules/.git配下のymlファイルがパースエラーを起こしている

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#524]
**Describe the bug**
1. `rules/config/noisy_rules.txt`等が存在するのに、存在しないというエラーが記録される。
2. `hayabusa-1.2.2-win-x64.exe -d c:¥yamatosecurity¥hayabusa-sample-evtx`を実行したのに、エラーログに`user input: hayabusa-1.2.2-win-x64.exe -L -d c:¥yamatosecurity¥hayabusa-sample-evtx`と書いてある。 (なぜか`-L`が書かれている）
3. `-d`の普通スキャンオプションだけで、`rules¥.git`配下のルールパースエラーが起こる。

**Step to Reproduce**
1. 今のmainブランチをコンパイルする。
2. `-u`オプションでルールをダウンロードする。
3.` -L -d <dir> `の２つのオプションでスキャンする。
4. `-d <dir>`の普通スキャンをする。

**Expected behavior**
エラーが出ないはず。

**Screenshots**

![hayabusa-1 2 2-error-2](https://user-images.githubusercontent.com/71482215/168934413-3438909e-3521-43bf-bce8-ca3e4a8e233a.png)

![hayabusa-1 2 2-error-1](https://user-images.githubusercontent.com/71482215/168934419-2ddb7e34-6ada-41b6-b276-57c01023ba23.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - hayabusa version v1.2.2 main branch pre release

**Comment by hitenkoku** [comment]
提示された手順で実施をしてみましたが、こちらの開発環境(Windows10)ではエラーが発生しませんでした。mainブランチを再度cloneしてみて対応します

**Comment by hitenkoku** [comment]
改めてmainブランチをcloneして実行してみましたが、エラーログは出力されませんでした環境は以下のとおりです

OS: Windows 10
hayabusa version:  b47561a79c063955ff468c9acd826014d2e08eb4 (mainブランチ最新版。 v1.2.2. mainbranch)

**Comment by YamatoSecurity** [comment]
なるほど、検証ありがとうございました。
もう一回こちらで確認してみます。

**Comment by YamatoSecurity** [comment]
確認しました。noisy_rules.txtのエラーはアップデート前のエラーなので、無視して良いです。
また、ユーザ入力の間違いの疑いは`-L`を実行した時のエラーなので、勘違いでした。

ただ、もう一回確認したら`.git`配下のパースエラーがまだ発生しているので、コンパイルしたものをslackで送ります。

**Comment by hitenkoku** [comment]
原因がわかりました。原因は一部のWIndows環境ではパス区切りの考慮漏れです。
一部WIndowsは/が区切りではなく\を区切りとしており、rustはそれをそのまま扱っていました。
.gitフォルダのフィルタリングは ”/.git/”としていたためこのフィルタリングにかかっていませんでした。

**Comment by hitenkoku** [comment]
@YamatoSecurity 修正完了しました #526 でpull requestを出しましたのでご確認のほどよろしくお願いいたします。
