### ISSUE TITLE
Cannot start Hayabusa 

### ISSUE THREAD

**Issue by scotrod** [Yamato-Security/hayabusa#527]
Pardon me for the strange question, but how do you even start this bird?

I downloaded the x64 package and when I try to run it via CMD all I get is:
[ERROR] Cannot open file. [file:config/statistics_event_info.txt]                                                       
[ERROR] Cannot open file. [file:config/target_eventids.txt] 

Windows 10 pro x64 21h2 patch

I tried multiple x64 releases - same results. I tried doing it on another Windows VM without change

![image](https://user-images.githubusercontent.com/45900128/169393289-83833b2c-8cc2-4a44-80b8-2e47a792a8ba.png)

Thank you!

**Comment by YamatoSecurity** [comment]
@scotrod Thank you for reporting this to us. We have just release 1.2.2 with some bug fixes.
Could you download from [https://github.com/Yamato-Security/hayabusa/releases/download/v1.2.2/hayabusa-1.2.2-all-platforms.zip](https://github.com/Yamato-Security/hayabusa/releases/download/v1.2.2/hayabusa-1.2.2-all-platforms.zip) and try running the `hayabusa-1.2.2-win-x64.exe` binary from there? It should work.

**Comment by scotrod** [comment]
> @scotrod Thank you for reporting this to us. We have just release 1.2.2 with some bug fixes. Could you download from https://github.com/Yamato-Security/hayabusa/releases/download/v1.2.2/hayabusa-1.2.2-all-platforms.zip and try running the `hayabusa-1.2.2-win-x64.exe` binary from there? It should work.

Worked like a charm!

Thank you for the awesome product!
