### ISSUE TITLE
Enhancement: 出力時にTimeline Histogramを出力する

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#533]
[krapslog](https://github.com/acj/krapslog-rs)のコードが使えそうだったら、Elastic Stackの一番上にあるTimeline histogramのように出力したいです。(いつ多くのイベントがあったかのspikeをすぐ特定できるため）

Screenshot:
<img width="977" alt="Screen Shot 2022-05-21 at 7 38 44" src="https://user-images.githubusercontent.com/71482215/169639762-477dc105-1a7d-4164-bd9e-5aca9f03aeaf.png">

```
Total detections: 18145
Total critical detections: 163
Total high detections: 1951
Total medium detections: 1330
Total low detections: 6350
Total informational detections: 8351
Total undefined detections: 0
Unique detections: 496
Unique critical detections: 36
Unique high detections: 203
Unique medium detections: 138
Unique low detections: 71
Unique informational detections: 48
Unique undefined detections: 0

Elapsed Time: 00:00:18.021
```

`Unique undefined detections`と`Elapsed Time`の間で出力するイメージです。ターミナルの幅に自動的に調整するようです。
取り敢えず`--markers 10`ハードコーディング？

**Comment by hitenkoku** [comment]
@YamatoSecurity 読み込んで処理自体を行うことは可能だと思いますが、以下2つを確認させてください。

- 出力はoutputを指定していないときも行いますか？
- この処理はオプションを付けてオン・オフできるようにしますか？

**Comment by YamatoSecurity** [comment]
@hitenkoku 
標準出力時も`-o`のファイル保存時もデフォルトで出力したいです。
重くなるんだったら、オプションでオフにできるようにしたいが、krapslogを使ったら一瞬で処理終わるので、多分パフォーマンスが落ちないと思います。ので、取り敢えずオプションなしでデフォルトで出力してみましょうか？

**Comment by hitenkoku** [comment]
コメントありがとうございます。
出力のオンオフの作成はそこまで難しくないので、pull request内で、処理速度も合わせて確認するようにしましょうか。
