### ISSUE TITLE
Enhancement: display logo in green

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#537]
カラー対応がデフォルトで可能になったので、ロゴをグリーン色で出力したいです。
--no-colorオプションでカラーなし。

@hitenkoku 細かいenhancementですみませんが、お願いできますか？

**Comment by hitenkoku** [comment]
@YamatoSecurity  #552 で対応完了しました。ご確認のほどよろしくお願いいたします。
