### ISSUE TITLE
[bug] main panic crash

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#541]
**Describe the bug**
`./target/release/hayabusa -f ../hayabusa-sample-evtx/DeepBlueCLI/disablestop-eventlog.evtx`を実行したら、以下のエラーでクラッシュします：

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/krapslog-0.4.0/src/lib.rs:82:24
stack backtrace:
   0:        0x10e3387c6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
   1:        0x10e1d7b8b - core::fmt::write::hb68c3045179d0cad
   2:        0x10e3371d0 - std::io::Write::write_fmt::haf84c797e63d79f0
   3:        0x10e33c1b2 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
   4:        0x10e33d1dc - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
   5:        0x10e33cc44 - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
   6:        0x10e33cbb9 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
   7:        0x10e33cb75 - _rust_begin_unwind
   8:        0x10e549ac3 - core::panicking::panic_fmt::hf7d6e5207e013f69
   9:        0x10e549a86 - core::panicking::panic_bounds_check::h4dad0bcdf31bc1e8
  10:        0x10e22f8c4 - hayabusa::afterfact::emit_csv::hd5bbb1bf5a0a95e0
  11:        0x10e1720c6 - hayabusa::App::analysis_files::h4e0876ecbb399a55
  12:        0x10e15bde4 - hayabusa::App::exec::h5684ddb963c4acea
  13:        0x10e155cbb - hayabusa::main::h885300da9a6f19e7
  14:        0x10e28e1f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::he0780667e9ddf0b7
  15:        0x10e17a06d - _main
```

**Step to Reproduce**
`./target/release/hayabusa -f ../hayabusa-sample-evtx/DeepBlueCLI/disablestop-eventlog.evtx`を実行する。

**Screenshots**

<img width="1607" alt="Screen Shot 2022-05-24 at 18 52 49" src="https://user-images.githubusercontent.com/71482215/170004527-546a058b-5448-449d-8167-07ce1dc5614f.png">

**Environment (please complete the following information):**
 - OS: macOS, iTerm2
 - hayabusa version: main branch 1.3.0-dev

**Comment by hitenkoku** [comment]
内容としてはkrapslogのエラーとなります。内容としては利用しているライブラリ側の問題になりますのでkrapslogの方に修正と合わせて提示するしかないと思います。確認します。

**Comment by hitenkoku** [comment]
@YamatoSecurity  原因がわかりました。理由としては対象の検知数が2件なのに対して、下側のmarkerが2つ利用しようとしていたのが原因です。

markerが2つであればkrapslogの仕様では最低3つのレコードが無いといけないことになります。
本来であればmarkerが出力するログより多い場合はmarker自体を出力しないという処理になります。

1つ相談なのですが、detectionが2件以下であればfrequencyを表示しないというのはどうでしょうか。
例えば "Event Frequency Timeline output is more than 3 detection."のような表示をするとかで対応すれば良いと考えています(正直3件でもいらない気がしています。分布が取れて嬉しいのはx件以上というのを決めてもらえればそれに合わせて作ることは可能です)

例えば今回のファイルを対象にして、マーカーを1とした場合は以下の図のような出力になってしまいます
marker自体を出力しない場合だと以下のような出力になってしまうことを確認しています。

![image](https://user-images.githubusercontent.com/2350416/170042715-a6073e29-042d-4ab8-893b-26146c9d4a10.png)

**Comment by YamatoSecurity** [comment]
なるほど。では、3件以上の場合だけタイムラインを出力しましょうか？
2件以下の場合はタイムラインの必要性が特に無いと思います。
3件とか数件だけの場合も不要かもしれないけど、「なんで出ないの？」と混乱するユーザがいそうだし、まれに場合によって役立つかもしれないので、適当にxx件以上を決めるより取り敢えず最低限の3件で良いかなと思います。

**Comment by hitenkoku** [comment]
承りました。3件以上であれば出力するように対応をしてみます
