### ISSUE TITLE
[bug] -f オプションを指定すると、Event Frequency Timelineの色が変わる

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#542]
**Describe the bug**
main branch 1.3.0-devで、`-f`指定で単体のイベントログを解析する際にEvent Frenquency TimelineのタイトルからData reductionの行まで、最後に出力されていた色で色が変わります。
例えば、最後のアラートの色がlevel: lowだった場合は、緑色になる。最後のアラートの色がlevel: mediumだった場合は、青色になる。

**Step to Reproduce**
`./target/release/hayabusa -f ../hayabusa-sample-evtx/DeepBlueCLI/metasploit-psexec-powershell-target-system.evtx`等

**Expected behavior**
`-d`と同じように、色が変わらない。

**Screenshots**
`level: low`の場合：
<img width="1608" alt="Screen Shot 2022-05-24 at 18 42 16" src="https://user-images.githubusercontent.com/71482215/170005767-e00f6e58-f6ff-4b73-a71f-b32be81b4601.png">
`level: medium`の場合：
<img width="1556" alt="Screen Shot 2022-05-24 at 18 41 27" src="https://user-images.githubusercontent.com/71482215/170005781-39d7acd9-c481-4a92-b6b9-1a96976d58a1.png">

**Environment (please complete the following information):**
 - OS:  mac iterm2
 - hayabusa version: main branch 1.3.0-dev

**Comment by hitenkoku** [comment]
こちらは対応可能です。大変失礼いたしました。
