### ISSUE TITLE
[bug] --start-timeline and --end-timeline do not work

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#546]
**Describe the bug**
--start-timeline と --end-timeline が使えない

**Step to Reproduce**
```
./target/release/hayabusa -d ../hayabusa-sample-evtx --start-timeline "2014-11-28 21:00:09 +09:00"
./target/release/hayabusa -d ../hayabusa-sample-evtx --end-timeline "2014-11-28 21:00:09 +09:00"
```

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version [e.g. v1.3.0-dev]

Additional:
` --start-timeline "2021-11-228 21:0dfd0:09d +09:00"`などの間違っている日付や時間を指定してもエラーが出ないので、形式が間違っている場合はエラーが出した方が良さそうです。

**Comment by hitenkoku** [comment]
対象の処理内容を確認しましたが、ご指摘いただいた間違っている日時や時間を指定した場合はエラーが出力されるように作成しています。データを記載しておきます。

**Comment by hitenkoku** [comment]
確認しましたが、実装はされていますが、mainでの読み込みが行われていないようでした。
組み込んで実行できるかどうか確認します。
