### ISSUE TITLE
Enhancement: Display Record ID

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#548]
ユーザ（松井さんのところのSOCチーム)からのリクエストですが、`--display-record-id / -R`オプションでレコードIDを出力したいです。
Splunkで解析しているけど、元のイベントログにすぐ飛べるようにレコードIDが必要だそうです。
取り敢えず、一番右側の列に入れたら良いかな？

**Comment by hitenkoku** [comment]
レコードIDと言っているのは、evtxファイル内のEvent > System > EventRecordID であってます？

**Comment by YamatoSecurity** [comment]
はい、Event > System > EventRecordID です。
一応コンソール出力も対応した方が良さそうです。

**Comment by hitenkoku** [comment]
現在の状態だと、作れなくはないのですが、afterfactで作っているFormatの数が増えることになってしまうのでできればオプション無しで出力という形にしたいのですがいかがでしょうか。

**Comment by hitenkoku** [comment]
承りました。
表示場所なのですが `--full-data`と合わせて使った際にRecordIDが見づらくなってしまうので RecordInformationの1つ右に出力するようにしてみました。pull request内でご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
#549 で作成が完了しました。ご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
@YamatoSecurity  https://github.com/Yamato-Security/hayabusa/pull/549 で作成が完了しました。ご確認のほどよろしくお願いいたします。
