### ISSUE TITLE
[bug] Problem with fields with spaces in them.

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#554]
**Describe the bug**
フィールドにスペースがある時に発生するバグです。
例えば、`rules/hayabusa/default/alerts/WindowsDefender/1116_WindowsDefenderAlert.yml`の`details`で`%SeverityName`を出力したい場合は、`rules/config/eventkey_alias.txt`で`SeverityName,Event.EventData.Severity Name`という風に定義する必要があります。

が、selection conditionでスペースが入っているフィールド(Provider Name等々)を使いたい場合は、`Provider_Name,Event.System.Provider_attributes.Name`という風に定義する必要があります。(READMEにも書いてあります。）
※今まで`Provider_Name,Event.System.Provider_Name`という風に定義していましたが、正しく検知していませんでした。
`Provider_Name,Event.System.Provider Name`も駄目です。

問題はaliasを`details`出力でも`condition`の`selection`でも使う場合があるので、どちらにも対応する必要があります。

`SeverityName,Event.EventData.Severity_attributes.Name`と定義したら、conditionが使えるようになるけど、`details`出力では`%Event.EventData.Severity_attributes.Name%`が出力されてしまいます。

多分eventkey_alias.txtでスペース対応するより、`details`出力で`n/a`という風に定義されているフィールドが正しく変換されるように修正した方がラクかな？

**Step to Reproduce**
1. `eventkey_alias.txt`で`SeverityName,Event.EventData.Severity Name`を`SeverityName,Event.EventData.Severity_attributes.Name`に変える。
2. `./target/release/hayabusa -d ../hayabusa-sample-evtx  -r rules/hayabusa/default/alerts/WindowsDefender/1116_WindowsDefenderAlert.yml`等を実行する。
3. `details`出力で`Severity:`をチェックする。

**Expected behavior**
%SeverityName%が正しく変換されるはず。

**Screenshots**
<img width="1668" alt="Screen Shot 2022-05-31 at 20 04 20" src="https://user-images.githubusercontent.com/71482215/171159457-656c11e7-1326-458a-a5c6-48ceeed3e168.png">

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version 1.3.0-dev

**Comment by hach1yon** [comment]
本件調査しましたが、対応不要でそもそもバグではなく想定通りの動作をしています。

まず、


```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Events>
	<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
		<System>
			<Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
		</System>
		<EventData>
		</EventData>
	</Event>
</Events>

```

**Comment by hach1yon** [comment]
次に`Severity Name`ですが、これも想定通りの動作をしています。

```
-
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	-
	<System>
		<EventID>
			1116
		</EventID>
		<TimeCreated SystemTime="2020-12-11T12:28:44.3178756Z" />
		<EventRecordID>
			177
		</EventRecordID>
	</System>
	-
	<EventData>
		<Data Name="Severity Name">
			High
		</Data>
	</EventData>
</Event>
```

**Comment by YamatoSecurity** [comment]
@hach1yon ご確認ありがとうございました！
前はなぜか`%SeverityName%`を片方しか使えなかったが、今はconditionもdetailsも無事に使えているので、大丈夫です。
問題なさそうなので、issueをクローズします。
