### ISSUE TITLE
Enhancement: output Saving results message

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#561]
結果が沢山ある場合は、数分以下の画面で止まってしまって、フリーズしているように見えてしまうため、ユーザが心配しないようにプログレスバーが100%になったら、`Analysis finished. Please wait while the results are being saved.`を出力したい。
※`-o`オプションが指定された時だけ。
<img width="1666" alt="Screen Shot 2022-06-03 at 4 30 54" src="https://user-images.githubusercontent.com/71482215/171724524-61c829d3-da6a-45aa-9b37-ba966f80c3ff.png">

また、`Event Frequency Timeline`の前に`Results Summary:`を入れましょうか？ 

`-o`指定時:
```
4892 / 4892 [===============] 100.00 %

Analysis finished. Please wait while the results are being saved.

Results Summary:

                          Event Frequency Timeline
```

標準出力時:
```
4892 / 4892 [===============] 100.00 %

<タイムライン>

Results Summary:

                          Event Frequency Timeline
```

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応完了しました。ご確認のほどよろしくお願いいたします。
