### ISSUE TITLE
[bug] Event Frequency Timelineの文字化け

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#566]
**Describe the bug**
今更気づいて申し訳ございません。ちょうどリリース前にデフォルトのCommand Promptで試したら、タイムラインが文字化けされていることが分かりました。(T_T) デフォルトのPowershellでも駄目でした。(Win. TerminalならOKです）

![krapslog-cmd-pwsh](https://user-images.githubusercontent.com/71482215/172028459-b8a98f82-319c-4ca8-8e47-22e2123610c8.png)

デフォルトのWindows Command Promptでは使えなさそうなので、デフォルトで表示しないで、`-V, --visual-timeline`オプションでONにできるようにした方が良いと思いますが、お願いできますか？

因みに、フォントをインストールしたり、文字化けされないように何か方法をご存知ですか？

**Environment (please complete the following information):**
 - OS: Windows 10 Command Prompt and Powershell Prompt
 - hayabusa version [e.g. v1.3.0 RC1]

**Comment by hitenkoku** [comment]
@YamatoSecurity 実行前にchcp 65001 と打ってもらってutf8での表示にしてもらっても同様の文字化けは起こりますでしょうか？

**Comment by hitenkoku** [comment]
@YamatoSecurity  #567 でオプションを追加させていただきました。ご確認のほどよろしくお願いいたします。また、rulesも6/5現在での最新版に紐づけするように変更しておきました。
