### ISSUE TITLE
Update insecure crates

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#570]
Githubが脆弱なRustクレートをアラートしてくれるようになりました。
https://github.com/Yamato-Security/hayabusa/security/dependabot
<img width="893" alt="Screen Shot 2022-06-07 at 17 02 18" src="https://user-images.githubusercontent.com/71482215/172331645-9328a08c-1dc6-49d2-b167-0af5505cf6ea.png">

エクスプロイトしにくいとは思いますが、念のために早めに直した方が良さそうです。

**Comment by hitenkoku** [comment]
一旦確認します

**Comment by hitenkoku** [comment]
対象のURLですが、私の方からは見れませんでした……

**Comment by YamatoSecurity** [comment]
まだセキュリティ警告が全部消えていないので、reopenします。
1. Data races in lock_api 
Cargo.lockを見ると、tokio-reactorのdependencyに"parking_lot 0.9.0"があります。"parking_lot 0.9.0"のdependencyに"lock_api 0.3.4"があるため、警告が出ていると思います。（しかし、なぜ３件？）
問題はtokio-reactorは２年間維持されていなくて、deprecatedになっています。どうしたら良いかな？

2. Type confusion in failure
パッチが無いそうです。「Type confusion can occur when private_get_type_id is overridden.」と書いてあるので、もしprivate_get_type_idをoverrideしていないのであれば、「関係ない」という理由でissueをdismissしたいと思います。

**Comment by hitenkoku** [comment]
1.については複数のcrateから呼び出しを受けている可能性がありえそうです。tokioを使って並列処理しているところを最新版のtokio crateで作成するというのが一番の方法のように思えます。

2. こちらについてはprivate_get_type_idはoverrideすることはしていないと思います。

**Comment by YamatoSecurity** [comment]
tokioは最新版を使っています。原因分かった（と思います）。slack-hookは古くて、古いtokioを使っているreqwest 0.9.xを使っているので、slack通知の機能を導入するのであれば、もっと維持されているslack-hook3を使う必要があります。取り敢えず、セキュリティアラートは問題なさそうなので、Closeします。

**Comment by hitenkoku** [comment]
失礼いたしました。slack機能の削除の際にcrateの削除までお個あっていなかったので一旦crate.tomlから外しても良いでしょうか
