### ISSUE TITLE
Enhancement: add more timestamp format options

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#574]
1. --rfc-3339の修正
`2006-08-07T12:34:56.485214 -06:00`の日付と時間の間の`T`は不要で読みにくいのと時間とタイムゾーンの間にスペースを入れないようなので、`2006-08-07 12:34:56.485214-06:00`に修正したい。
2. --US-timeの追加
`mm-DD-YYYY HH:MM:SS.fff AM/PM -06:00`
3. --US-military-timeの追加 (24時間)
`mm-DD-YYYY HH:MM:SS.fff -06:00`
4. --European-time (24時間)
`DD-mm-YYYY HH:MM:SS.fff +02:00`

**Comment by hitenkoku** [comment]
今回追加するtimeの3つはtimezoneの前に半角スペースが入っています。
rfc-3339の方では半角スペースはつけていませんが、問題ないですか？

**Comment by YamatoSecurity** [comment]
> 今回追加するtimeの3つはtimezoneの前に半角スペースが入っています。 rfc-3339の方では半角スペースはつけていませんが、問題ないですか？

はい、何かのRFCに合わせるより、一番読みやすい形式にしたいので、スペースを入れたいです。

**Comment by hitenkoku** [comment]
承りました。回答有り難うごございます。それでは現在の仕様のまま作成しましたので #576 のマージで対応します。
