### ISSUE TITLE
[bug] Version placeholder not working

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#575]
**Describe the bug**
4688のルール(`rules/hayabusa/non-default/events/Security/4688_ProcessCreationWithCommandLine.yml`が使えなくなりました。
`Version: 1`でフィルタしているが、detailsで`%Version%`を出力してみても`n/a`が出力されてしまいます。
コメントアウトしたらルールがヒットするので、%Version%をうまく変換できていないようです。
eventkey_alias.txtを確認したら、`Version,System.Version`という風に定義されているので、合っているはずです。

**Step to Reproduce**
`./target/release/hayabusa -d ../hayabusa-sample-evtx -r rules/hayabusa/non-default/events/Security/4688_ProcessCreationWithCommandLine.yml`

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version: 1.3.1-dev

**Comment by YamatoSecurity** [comment]
ごめんなさい！自己解決しました。
`Version,System.Version`ではなく、`Version,Event.System.Version`が正しいです。
後でhayabusa-rulesのレポの方で修正します！
m(__)m

**Comment by hitenkoku** [comment]
ご確認いただきありがとうございます。hayabusa-rulesのpull-requestマージが完了しました。こちらの修正は早めに対応したほうが良さそうなので、 #574 でアップデート対応を行います
