### ISSUE TITLE
Enhancement: Output Processing Rules msg and rule status metrics

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#583]
２点あります。

１点目：Hayabusaを使う際に以下の画面で若干フリーズします。（ま、フリーズではなく、バックグラウンドでルールをロードしていると思いますが、フリーズしているように見えてしまいます。(私の環境では３秒程度))

<img width="551" alt="Screen Shot 2022-06-10 at 10 25 41" src="https://user-images.githubusercontent.com/71482215/172972031-332f672a-f580-419c-9494-93ada5c22260.png">

ので、
```
Analyzing event files: 574
Total file size: 148.0 MB
```
の後に`Processing detection rules. Please wait.`を入れたいです。

例：
```
Analyzing event files: 574
Total file size: 148.0 MB

Processing detection rules. Please wait.

Deprecated rules: 0
Excluded rules: 59
Noisy rules: 17
Rule parsing errors: 0
```

2点目：ルールの`status`がバラバラでどれぐらいが`stable`で安定しているのか、どのぐらい`experimental`で実験的なのか把握した方が良いので、以下のように`status`統計情報を出力したいです：

```
Deprecated rules: 0 (0.0%)
Excluded rules: 59 (3.3%)
Experimental rules: 300 (40.2%)
Noisy rules: 17 (3.0%)
Rule parsing errors: 0
Stable rules: 400 (30.5%)
Test rules: 30 (10.4%)
```

**Comment by hitenkoku** [comment]
以下の機能ですが、記載された形だとDeprecated, Excluded, Noisyは各種statusと重複する形になってしまいます。Deprecated のルールでstatusではexperimentalと書いてあるなどの場合、Deprecatedにもカウントされますし、expreimentalにもカウントされると思われるので以下のように%の集計対象は各種statusのみとするのはいかがでしょうか

```
Deprecated rules: 0
Excluded rules: 59
Noisy rules: 17
Rule parsing errors: 0

Experimental rules: 300 (40.2%)
Stable rules: 400 (30.5%)
Test rules: 30 (10.4%)
```


> 2点目：ルールの`status`がバラバラでどれぐらいが`stable`で安定しているのか、どのぐらい`experimental`で実験的なのか把握した方が良いので、以下のように`status`統計情報を出力したいです：
> 
> ```
> Deprecated rules: 0 (0.0%)
> Excluded rules: 59 (3.3%)
> Experimental rules: 300 (40.2%)
> Noisy rules: 17 (3.0%)
> Rule parsing errors: 0
> Stable rules: 400 (30.5%)
> Test rules: 30 (10.4%)
> ```

**Comment by hitenkoku** [comment]
`Processing detection rules. Please wait.` だと ruleに直接の処理を加えているように見えそうですが大丈夫でしょうか。実際の処理に合わせた英語だと`Loading detection rules. Please wait.` を表示する形でいかがでしょうか。

> ```
> Analyzing event files: 574
> Total file size: 148.0 MB
> ```
> 
> 
>     
>   
> 
> の後に`Processing detection rules. Please wait.`を入れたいです。
