### ISSUE TITLE
Evtx files with different extension

### ISSUE THREAD

**Issue by jurelou** [Yamato-Security/hayabusa#586]
I can see that hayabusa only supports files with evtx extension.

Would it be possible to add a command line argument to check for a different file extension ?

thanks !

**Comment by YamatoSecurity** [comment]
We only support evtx event log files. What would the use case be?
That is, why would a windows event log have a different file extension?

**Comment by YamatoSecurity** [comment]
I see. Thank you for letting us know. I didn't know different tools save `evtx` files with different file extensions. We will see if we can automatically check if it is a valid `evtx` file regardless of file extension or worst case scenario, just add an option as you said to allow for different file extensions.

@hitenkoku 世の中のイベントファイルの収集ツールが`.evtx_data`等の違うファイル拡張子で保存することがあるみたいなので、それに対応したいのですが、お願いできますか？できれば、`file`コマンドのように拡張子関係なく、ファイルが正当な`evtx`形式かどうか自動的にチェックした方が良さそうですが、`evtx`ライブラリの機能などでそういったチェックは可能ですか？
難しいのであれば、ここで提案されているように`--file-extension evtx_data`のオプションで`.evtx`以外のファイルを解析できるようにしたいです。

**Comment by hitenkoku** [comment]
@YamatoSecurity evtxライブラリの読み込み時にエラーがあった場合読み込みをスキップするようにしてますが、あまり、すべてのファイルに対して行うという形にするとパフォーマンス面で影響が出てしまう可能性もあります。

オプション対応する話ですが、今後似たような拡張子の話をこちらが動作を担保するようにはしたくないので、configファイルで読み込み拡張子を管理しておくのはどうでしょうか（追加するのはユーザーにやってもらう形で……）

**Comment by hitenkoku** [comment]
@YamatoSecurity 承りました。--file-extensionの方法で対応しようと思います。以下2つに付いて仕様を決めたいのですがどうでしょうか。

- --file-extension evtx_data -> 調査対象にするのは evtx_dataとevtxにするか、evtx_dataのみにするか。個人的にはevtxはデフォルトで入れておいたほうがいいかなと思っていました。
- --file-extensionにで複数拡張子をサポートするか？ -> --file-extension evtx_data hogehoge と指定するとevtx_dataとhogehogeを対象とするようにしたほうがよいでしょうか。
