### ISSUE TITLE
--config flag seems to be ignored

### ISSUE THREAD

**Issue by scudette** [Yamato-Security/hayabusa#592]
**Describe the bug**
The --help output shows it is possible to specify a config directory with --config but it seems that the tool **has** to run from its own directory and the --config flag is ignored

**Step to Reproduce**

When not inside the F:\tmp directory it fails even though --config is specified.
```
F:/tmp/hayabusa-1.3.2-win-x64.exe -d C:\Windows\System32\winevt\Logs -o F:/tmp/hayabusa_results_75343047332.csv -r F:/tmp/rules --config F:\tmp\ -F -q
[ERROR] Cannot open file. [file:config/statistics_event_info.txt]
[ERROR] Cannot open file. [file:config/target_eventids.txt]
[ERROR] Hayabusa could not find the config directory.
Please run it from the Hayabusa root directory.
Example: ./hayabusa-1.0.0-windows-x64.exe
```

But if we change to the F:\tmp directory it works ok with the same command line.

**Expected behavior**

It should not matter which directory the tool is run from - it should respect the command line args and find its various config files from where the user specified.

**Environment (please complete the following information):**
 - Windows 11
 - hayabusa 1.3.2-windows

**Comment by hitenkoku** [comment]
@scudette  Thanks for your comment. I checked the same bug. I'll fix it.

**Comment by hitenkoku** [comment]
I checked the help document. `--config` option specifies rule config folder.
`./config` is hayabusa's config folder.

```
 -c, --config <RULE_CONFIG_DIRECTORY>      Specify custom rule config folder (default: ./rules/config)
```

@YamatoSecurity  
こちらですが、rule configのフォルダとhayabusaのconfigフォルダがわかりづらいという指摘だと思いますが、hayabusaのconfigフォルダもオプション指定できるようにしますか？

**Comment by scudette** [comment]
Is it possible to override it so it is not forced to run from the directory?

**Comment by YamatoSecurity** [comment]
@scudette Thank you for the feedback. Hayabusa has two directories for config files. One for the main hayabusa configuration and one for anything that deals with rules. Right now the main config directory is hard coded to be run from `./config` while the rules config directory (default: `./rules/config`) can be changed. I would like to confirm what is the situation where you can't place the hayabusa config directory in the same directory as the binary? If for some reason users need/want to place the hayabusa config directory somewhere else we can probably add an option for that.

**Comment by scudette** [comment]
It's not about the same directory as the binary but the current working directory.

This velociraptor artifact currently fails in some cases because we unpack the zip file into a temp directory then try to run the binary (which starts the process from the working directory of velociraptor)

https://docs.velociraptor.app/exchange/artifacts/pages/windows.eventlogs.hayabusa/

We can fix it from our end by allowing the subprocess to change directory first or wrapping in a PowerShell script to change directory. It was just confusing to me that there is a flag but it appears to be ignored.

**Comment by YamatoSecurity** [comment]
I see, now I understand. I will update the documentation and error handling to try to explain better the difference between the two config directories and that you need to run the binary from the current directory. For now, please try to work around by changing directories before executing it. Thank you for the feedback and work on integrating it with Velociraptor!
(I have been wanting to integrate it for the longest time.)

**Comment by YamatoSecurity** [comment]
@hitenkoku Can have Hayabusa find the correct `config` dir. even if it is run from a different working directory?
一応日本語で・・現在、Hayabusaをカレントディレクトリから実行しないと、`config`ディレクトリが見つからなくて、失敗するが、実行時のパスをベースにして、`config`を探すことは難しいですか？
難しい場合は、`config`ディレクトリ配下の必要なファイル等が存在しているかどうかチェックして、存在していない場合は違うディレクトリから実行している可能性が高いので、「You need to run Hayabusa from the current directory.」という風ににエラーを出したいです。あ、実行したパスがカレントディレクトリであるかどうか確認するのもっと良い方法ですよね？

**Comment by hitenkoku** [comment]
@YamatoSecurity  OK,. I'll check it. Maybe it can.

了解しました。実行時のパスをベースにしてconfigを探すことは調べてみたところ、可能かと思いますが、確認いたします。

**Comment by YamatoSecurity** [comment]
@hitenkoku ありがとうございます！
ついでに`-c / --config`を`-c --rules-config`に変えましょうか？ (少し分かりやすくするため）
