### ISSUE TITLE
Print all field info when no details are defined.

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#606]
ルールの`details`フィールドと`./rules/config/default_details.txt`ファイルに`details`が定義されていない場合は、`-F`オプションのように全フィールドの情報を`details`列に出力したいです。

**Comment by hitenkoku** [comment]
対応は可能ですが、画面表示が非常に煩雑になってしまいますが問題ないでしょうか。
例えば同様に`--full-data` を指定したときのみに全文表示とかのほうが良さそうに見えますがいかがでしょうか。

**Comment by YamatoSecurity** [comment]
確認、ありがとうございます！
目的は普段--full-dataを指定しなくても良いようにしたいです。仰る通り、これを実装したら、--full-dataを指定した時に、殆どのデータが重複されて、--full-dataの意味がほとんど無くなりますが、それで良いです。現在、--full-dataを有効にすると、CSVファイルが100MBから2GBに相当でかくなってしまうが、フィールドデータが無いとアラートを確認できないので、--full-dataを有効にしている人が多いと思います。データが多すぎて、画面表示が煩雑になったり、CSVファイルサイズが大きくなったりした場合は、`default_details.txt`を更新して、より少ないデータを出力するように対応しようと思っています。
ルールテストの時に--full-dataは役立つので、(details出力と比較できるので）そのまま残そうと思っています。

**Comment by hitenkoku** [comment]
承りました。それでは実装していこうと思います。一つの方法としてdetailsとrecord-informationの情報が同じだと、record-informationの出力を「Same as "details" column, so abbreviated」に変更することも考えましたが、そうなるとほかのツールにインポートしたときに不具合がでそうですね。
