### ISSUE TITLE
Enhancement: enable ID filtering by default. -D / --deep-scan option

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#608]
The number of detection rules has grown to the point that it is starting to slow down the scan (around 30sec ~ 1 minute for a live scan) and will just take longer over time with more rules so it is better to filter by IDs. This improves performance by 1.25x ~ 2x in my tests. Even with filtering by IDs, hayabusa should detect almost everything but just in case, we will provide the `--deep-scan` option to ignore the event ID filter list `config/target_eventids.txt` and scan all events.

ルール数が大分増えてきて、スキャン時間が段々遅くなってきているので、デフォルトで`config/target_eventids.txt`のイベントIDフィルタを有効にしたいと思います。IDフィルタしないで、全イベントをスキャンしたい場合は`-D / --deep-scan`オプションでできるようにしたいです。
最近デフォルトでSigmaのdeprecated rulesが無くなって、`--enable-deprecated-rules`を使う機会が少なくなってきているので、short formを無くして、`-D`を`--deep-scan`に使おうと思っています。

`-D, --enable-deprecated-rules` => `--enable-deprecated-rules`
`-D, --deep-scan`

**Comment by hitenkoku** [comment]
@YamatoSecurity  Thank you for your request, I'll it,Please wait.

了解しました。特に追加で確認する事項はないと思います。作成完了したらpull-requestでレビュー依頼を出しますのでよろしくお願い致します。
