### ISSUE TITLE
Enhancement: combining -u and -r options

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#615]
`-u`と`-r`の組み合わせでデフォルトでない`rules`フォルダを更新したいという希望がありました。
@hitenkoku どうしましょう？
コードが汚くなったり、手間がかかったりするのであれば、実装しなくても良いと思いますが。。

その場合は、「Error: Specifying -u and -r at the same time is not supported. Please run `git pull` from your custom rules directory to update to the latest rules.」というエラーメッセージを出しましょうか？

**Comment by hitenkoku** [comment]
少し確認してみます。

**Comment by hitenkoku** [comment]
実装は可能だと思います。ただ、rulesで指定されたレポジトリがサブモジュールでなくても動作が問題なくできるかは検証してみて、手間が非常にかかるようであれば相談させてください

**Comment by hitenkoku** [comment]
特に検証する必要があるのはデフォルトでないrulesフォルダを更新させるレポジトリが別のレポジトリであった場合ですかね

**Comment by YamatoSecurity** [comment]
そうですね。レポジトリ名を確認したら良さそうですね。
