### ISSUE TITLE
[bug] An error occurs when executing cargo run because the files in the config folder cannot be read.

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa#618]
**Describe the bug**
下記2つのバグがあるようです。
* configファイルの読み取り失敗により、cargo runの実行でエラーが発生する。
* --rules-configオプションが効かない

hayabusa.exeを`C:\Users\takai\dev\git\hayabusa`にコピーして下記のように実行すると、エラーは解消される。
````````````````
hayabusa.exe --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -r 
 .\rules\hayabusa\default\alerts\WindowsDefender\1116_WindowsDefenderAlert.yml
````````````````

**Step to Reproduce**
* cargo runを実行すると下記のエラーが発生する。
````````````````
C:\Users\takai\dev\git\hayabusa>cargo run -- --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -r .\rules\hayabusa\default\alerts\WindowsDefender\1116_WindowsDefenderAlert.yml
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target\debug\hayabusa.exe --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -r .\rules\hayabusa\default\alerts\WindowsDefender\1116_WindowsDefenderAlert.yml`
[ERROR] Cannot open file. [file:C:\Users\takai\dev\git\hayabusa\target\debug\rules/config/statistics_event_info.txt]
[ERROR] Cannot open file. [file:C:\Users\takai\dev\git\hayabusa\target\debug\rules/config/target_event_IDs.txt]


[ERROR] Hayabusa could not find the config directory.
Please make sure that it is in the same directory as the hayabusa executable.
````````````````

* --rules-configオプションをつけてcargo runしても反映されていないように見える
````````````````
C:\Users\takai\dev\git\hayabusa>cargo run -- --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -r .\rules\hayabusa\default\alerts\WindowsDefender\1116_WindowsDefenderAlert.yml --rules-config=C:\Users\takai\dev\git\hayabusa\rules\config
   Compiling hayabusa v1.4.2-dev (C:\Users\takai\dev\git\hayabusa)
    Finished dev [unoptimized + debuginfo] target(s) in 2.76s
     Running `target\debug\hayabusa.exe --directory=C:\Users\takai\dev\git\hayabusa-sample-evtx -r .\rules\hayabusa\default\alerts\WindowsDefender\1116_WindowsDefenderAlert.yml --rules-config=C:\Users\takai\dev\git\hayabusa\rules\config`
[ERROR] Cannot open file. [file:C:\Users\takai\dev\git\hayabusa\target\debug\rules/config/statistics_event_info.txt]
[ERROR] Cannot open file. [file:C:\Users\takai\dev\git\hayabusa\target\debug\rules/config/target_event_IDs.txt]


[ERROR] Hayabusa could not find the config directory.
Please make sure that it is in the same directory as the hayabusa executable.
````````````````

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - hayabusa version v1.4.1

**Additional context**

**Comment by YamatoSecurity** [comment]
Velociraptor等のツールから実行すると、カレントディレクトリではないディレクトリからの実行になるので、`config`ディレクトリが見つからないというエラーで失敗するというクレームが来ていたので、カレントディレクトリじゃなくても実行できるようにHayabusa.exeが入っているパスを調べて、そこにある`config`を使っています。なので、開発時に`./target/release/hayabusa.exe`などを実行すると、`config`ディレクトリを`./target/release/config`で探してしまうので、失敗します。
hayabusa.exeが入っているパスに`config`を探して、無い場合はカレントディレクトリに`config`を探すようにすれば、どっちもいけると思います。

**Comment by hitenkoku** [comment]
以下の件について、`--rules`と`--rules-config`について対応をしようと思います。

- --rules: hayabusa.exeが入っているパスを確認し、rulesフォルダがあるか確認し、なければカレントディレクトリのrulesを参照する。そこでrulesフォルダがなければエラーとする。
- --rules-config: hayabusa.exeが入っているパスを確認し、rulesフォルダがあるか確認し、なければカレントディレクトリのrulesを参照する。そこでconfigフォルダがなければエラーとする。configフォルダがあって各種設定ファイルがないことへのチェックはこの処理では行わない(各種設定ファイルの読み込み時にエラーが出るため)

> hayabusa.exeが入っているパスに`config`を探して、無い場合はカレントディレクトリに`config`を探すようにすれば、どっちもいけると思います
