### ISSUE TITLE
[bug/enhancement] display relative rules path

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#623]
**Describe the bug**
現在、`-o`を指定時にルールのフルパスが出力されるが、どのルールでひかかったか分かれば良いので、フルパスではなく、相違パスで良いと思います。
また、1.4.2-devでは、`./`がパスに入っているので、無くしたいです。
1.4.1の出力の例： `/Users/tanaka/Documents/YamatoSecurity/hayabusa/rules/hayabusa/non-default/events/Security/4688_ProcessCreation.yml`
1.4.2-dev出力の例: `/Users/tanaka/Documents/YamatoSecurity/hayabusa/./rules/hayabusa/non-default/events/Security/4688_ProcessCreation.yml`

これから出力したい: `rules/hayabusa/non-default/events/Security/4688_ProcessCreation.yml` (※ 最初の`./`も不要)

**Step to Reproduce**
1.4.2-devで`-o`を指定する

**Comment by hitenkoku** [comment]
./の対応はしますが、rules以外のフォルダを指定している場合は、相対パスで../が多くなる可能性がありますが大丈夫でしょうか

**Comment by YamatoSecurity** [comment]
> ./の対応はしますが、rules以外のフォルダを指定している場合は、相対パスで../が多くなる可能性がありますが大丈夫でしょうか

なるほど。ま、絶対パスより文字数が少ないはずなので、それで良いと思います。`../`も全部削除できそうだったら、無くしても良いかもしれません。

例：`-r ../../../hayabusa-rules`の場合は、出力時に`hayabusa-rules/hayabusa/nantoka.yml`など

(数GBのevtxを解析した時に出力ファイルも大きくなるので、`./`の二文字が増えるだけでファイルサイズが数百MB増えました)

因みに、ユーザが`-r C:¥hogehoge¥rules`などの絶対パスを指定した場合は、そのまま絶対パスを出力すると良いと思います。

**Comment by hitenkoku** [comment]
承りました。絶対パスと相対パスを区別する方法としては `./` という記載が -r に入っていたときには相対パスするという形にします。

**Comment by YamatoSecurity** [comment]
> 承りました。絶対パスと相対パスを区別する方法としては `./` という記載が -r に入っていたときには相対パスするという形にします。

区別する時に`../`から始まる場合も、別のルールディレクトリがhayabusaディレクトリ配下にあった場合は`-r rules2`などになるので(`./`を指定しなくてもいけるので)、以下の区別方法はどうですか？
- Linux/Macの絶対パスを指定した場合は`/`から始まる
- Windowsの場合は`C:¥`などだけど、ドライブレッターが分からない(`D:`や`Y:`かもしれない）

ので、
1. `/`から始まった場合、もしくは２番目の文字が`:`の場合は絶対パスで、そうじゃない場合は相対パスで区別するのはどうですか？
