### ISSUE TITLE
Support other log sources such as auditd, sysmon for linux, etc...

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#626]
https://github.com/wagga40/Zircolite で Auditd / Sysmon for Linux / JSONL or NDJSON logs が対応しているのでHayabusaも同様の形式のファイルを読み込んで、解析できるようにしたい

**Comment by hitenkoku** [comment]
サンプルとなるログが得られないかから確認

**Comment by YamatoSecurity** [comment]
We should probably fork Hayabusa and make a new tool for this as there will be too many options, etc.. resulting in overly complex code.
