### ISSUE TITLE
[investigate] Support wasm

### ISSUE THREAD

**Issue by kazuminn** [Yamato-Security/hayabusa#632]
もし、wasmで使えれば、ダウンロードしなくても、ブラウザ上で使えると思う。
嬉しくなったりするのでは。

ぱっと、wasmターゲット用にコンパイルしてみたのですが、通らず。

ちょっと調査してみます。

ちなみに、wasm何もわかりません。

**Comment by YamatoSecurity** [comment]
ブラウザ上で解析できたら面白いですね。
(サイト運用が大変になりそうだけど）

**Comment by kazuminn** [comment]
コンパイルが進んだ。

tokioが使ってるsocket2がよくないみたい。
最新のtokioに更新して、unstableにしたら、コンパイルが次に進んだ。

また止まった。

**Comment by YamatoSecurity** [comment]
wasmについての記事があったので、共有します: https://zenn.dev/tanakh/articles/rust-emulator-in-browser

**Comment by kazuminn** [comment]
@YamatoSecurity 共有、ありがとうございます。

**Comment by kazuminn** [comment]
wasmは、linuxでbuildしなければいけないことが分かった。windowsは、あまりサポートされてない。。

wasmは、通常の方法では、ファイルが吐けないようになってる。セキュリティー上の理由から。
sysクレートからweb_sysクレイトに書き直せばファイルが吐けるようになる。
書き換えれば、コンパイルが通るかもしれない。

**Comment by kazuminn** [comment]
と思ったけど、sysは、ライブラリで使われているようだ。

**Comment by kazuminn** [comment]
wasm32-unknown-emscripten
wasm32-unknown-unknown
wasm32-wasi
と三つのターゲットがあるんですけど、どれもevtxの依存しているjemallocをサポートしてないので、現段階では、コンパイルできないです。

以上となり、issueを終了します。
