### ISSUE TITLE
Enhancement: Make startswith, endswith, contains  case-insensitive

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#633]
Hayabusa Readme:
<img width="1024" alt="Screen Shot 2022-07-25 at 13 47 16" src="https://user-images.githubusercontent.com/71482215/180700853-0b67d9fa-2819-4c66-861a-afcc96fd9eeb.png">

`|startswith`, `|endswith`, `|contains`は大文字小文字を区別するようにしていますが、Sigma Wikiを再確認したら、区別しないのが正しいっぽいです。
<img width="675" alt="Screen Shot 2022-07-25 at 13 45 59" src="https://user-images.githubusercontent.com/71482215/180700999-ad683c65-daaa-4b8a-b6b2-2265cb206d87.png">
https://github.com/SigmaHQ/sigma/wiki/Specification

区別してしまうと、簡単にルールをバイパスできてしまうので、この３つを大文字小文字を区別しないようにしたいです。
`|re`と`|equalsfield`は今のままで大丈夫です。

**Comment by hitenkoku** [comment]
確認しました。修正すべきところはわかったので確認してみます。

**Comment by YamatoSecurity** [comment]
ありがとうございます！

**Comment by hitenkoku** [comment]
@YamatoSecurity  本件ですが、対象のテストを作ってみたところ、大文字小文字をそもそも区別していないようでした。念のため #634 でテストを追加しましたのでご確認のほどよろしくお願いいたします。
