### ISSUE TITLE
[bug] Miscalculation of Data Reduction in rare cases

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#640]
**Describe the bug**
`./target/release/hayabusa -f ../hayabusa-sample-evtx/DeepBlueCLI/password-spray.evtx -o output.csv`
上記のように`password-spray.evtx`をスキャンした際に、Results Summaryで`Data reduction: 340282366920938463463374607431768211454 events (115349954888453711305695546525052043264.00%)`が出力されます。

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version: 1.4.5-dev, 1.4.2, 1.4.1でも同じ現象が起こっています。

**Comment by hitenkoku** [comment]
原因がわかりました。
すべてのレコード数のカウントは295になっていて、検知したレコード数が297となっていたため、負の数になってしまったためオーバーフローで値がおかしくなってしまったようです。すべてのレコード数のカウントがおかしい可能性があるので確認します。

**Comment by hitenkoku** [comment]
念のためレコード数をイベントビュアーでカウントを確認してみましたが295で合っていました。
おそらく検知したレコード数の方のカウントが間違っているようなので確認致します。

**Comment by hitenkoku** [comment]
aggregation conditionの検知が2件あり、すべてのレコードに対して検知が入っているうえでこのaggregation condition検知2件が入っているので、検知件数はレコードのトータル数より多くなってしまっているようです。
