### ISSUE TITLE
Investigation for Speed up 

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#641]
処理のスピードアップできるかどうか確認する。

**Comment by hitenkoku** [comment]
ref: https://github.com/Yamato-Security/hayabusa/pull/631#issuecomment-1203291493

**Comment by hach1yon** [comment]
#631については、特にスピードアップできそうな部分はなさそうに思います

**Comment by hitenkoku** [comment]
@hach1yon ご確認いただきありがとうございます。それでは本issueはcloseさせていただきます
