### ISSUE TITLE
Minor touchup: remove ./ from rule path when updating

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#642]
細かいところですみませんが、
Windowsでルール更新時にパスが`./rules¥hayabusa¥hogehoge`で`/`と`¥`が混ざって違和感があるので、どのOSでも同じように表示するように最初の`./`を消して、`rules¥hogehoge`にするか、それが難しい場合はmac/Linuxの場合は`./`を使って、Windowsの場合は`.¥`を使いたいのですが、どうですか？

![rules update](https://user-images.githubusercontent.com/71482215/182974943-d69c55bd-9bdd-4ece-82f6-cffca60873f2.jpg)

**Comment by hitenkoku** [comment]
承りました。最初の./を消す方向で検討してみます。
