### ISSUE TITLE
Enhancement: Output to JSON

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#654]
1. jqでの解析
2. Elastic Slackのインポートで各detailsフィールドが別々になるように
3. Filebeat等で簡単にElasticやSplunkにデータを送信できるように
JSON形式に出力できるようにしたいです。

例:
```
Timestamp,Computer,Channel,EventID,Level,MitreTactics,MitreTags,OtherTags,RecordID,RuleTitle,Details,RuleFile,EvtxFile
2016-08-31 02:11:11.262 +09:00 , IE10Win7 , Sec , 4688 , low  , Evas , T1036.003 : T1036.005 ,  , 8525 , Windows Processes Suspicious Parent Directory , CmdLine: taskhost.exe $(Arg0) , Path: C:\Windows\System32\taskhost.exe , PID: 0x338 , User: IE10WIN7$ , LID: 0x3e7 , proc_creation_win_proc_wrong_parent.yml , ../hayabusa-sample-evtx/DeepBlueCLI/many-events-security.evtx
```
を以下のように出力する:
 {
   "Timestamp": "2016-08-31 02:11:11.262 +09:00",
   "Computer": "IE10Win7",
   "Channel": "Sec",
   "EventID": 4688,
   "Level": "low ",
   "MitreTactics": ["Evas"],
   "MitreTags":  ["T1036.003", "T1036.005"],
   "OtherTags": [],
   "RecordID": 8525,
   "RuleTitle": "Windows Processes Suspicious Parent Directory",
   "CmdLine": "taskhost.exe $(Arg0)",
   "Path": "C:\\Windows\\System32\\taskhost.exe",
   "PID": "0x338",
   "User": "IE10WIN7$",
   "LID": "0x3e7",
   "RuleFile": "proc_creation_win_proc_wrong_parent.yml",
   "EvtxFile": "../hayabusa-sample-evtx/DeepBlueCLI/many-events-security.evtx"
 }

`MitreTactics`、`MitreTags`、`OtherTags`は複数可能なので、配列にします。
`Details`フィールドを各フィールドに分けます。(`Field-1: %hogehoge% | Field-2: %hogehoge%`の形式をパースする必要がありますが、現在のHayabusaルールは全部この形式になっているはずです。）

**Comment by hitenkoku** [comment]
承りました。対応いたします。きれいな形にするのはjqなどが対応すると思いますので、単純にJSONでファイルに出力するという方針にします。

outputと同じようにファイル名が重複していた場合は実行を止め他方が良いでしょうか

**Comment by YamatoSecurity** [comment]
ありがとうございます！
1. できれば、画面出力時にカラーで出力したいのですが、crateを調べたら
[json-color](https://crates.io/crates/json-color) と https://crates.io/crates/colored_json が３年以上維持されていなくて、
https://crates.io/crates/termcolor-json なら7ヶ月前にアップデートされているので、使えそうだったら使いたいけど、使いにくいのであれば、カラーなしでも大丈夫です。( `|  jq`に任せましょう）

2. CSVと同じようにファイルが既に存在しているのであれば、実行を止めましょう。

3. オプション名を書き忘れました。OTHER-ACTIONS配下の`-j, --json-timeline`にしましょうか？

**Comment by hitenkoku** [comment]
1.についてですが、画面出力をしたとしても、Resultsummaryがあるのでjqに即投入してもエラーが出る可能性がありますが大丈夫ですか？

**Comment by hitenkoku** [comment]
1.についてですが、画面出力をしたとしても、Resultsummaryがあるのでjqに即投入してもエラーが出る可能性がありますが大丈夫ですか？

**Comment by YamatoSecurity** [comment]
あぁ、たしかに・・
では、カラー出力が難しいのであれば、ユーザにファイルを作成して、それをjqで解析して貰いましょう。

**Comment by hitenkoku** [comment]
承りました。いったん、プロトタイプで作ってみて、それで利用お訃報を検討する方向にしてもよいでしょうか？

**Comment by hitenkoku** [comment]
出力内容ですが、profileで指定した列の出力をするようにします

**Comment by YamatoSecurity** [comment]
> 承りました。いったん、プロトタイプで作ってみて、それで利用方法を検討する方向にしてもよいでしょうか？

はい、ありがとうございます！

> 出力内容ですが、profileで指定した列の出力をするようにします

ありがとうございます！

**Comment by hitenkoku** [comment]
作成が今週中に間に合わなさそうなので1.5.0のマイルストーンから外して1.6.0のマイルストーンに変更しました。

**Comment by hitenkoku** [comment]
@YamatoSecurity  ようやく対応が完了しました。pull-requestを出しましたのでご確認のほどよろしくお願いいたします。
