### ISSUE TITLE
remove build.rs & change allocator to mimalloc

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#657]
今更気づいてすみません。静的コンパイルのために`build.rs`が追加されましたが、ルートディレクトリに置く必要はありますか？
可能であれば、`src/`配下に置きたいです。

**Comment by hitenkoku** [comment]
確認しました。以下のURLによると、ビルドスクリプトを利用しているのですが、こちらはパッケージのルートに配置する必要があるため動かすのはできないようです。

https://doc.rust-lang.org/cargo/reference/build-scripts.html

https://github.com/ChrisDenton/static_vcruntime

**Comment by hitenkoku** [comment]
@YamatoSecurity  こちらの調査内容で問題なければissueのクローズをお願いいたします。

**Comment by YamatoSecurity** [comment]
なるほど。了解しました。調べて頂いてありがとうございました！
では、クローズしますね。

**Comment by fukusuket** [comment]
I checked the below implementation of static_vcruntime which is the actual contents of build.rs
- [static_vcruntime/blob/main/src/lib.rs#L75-L89](https://github.com/ChrisDenton/static_vcruntime/blob/main/src/lib.rs#L75-L89)

All `build.rs`'s work is passing the following options to `rustc`.
- [cargo:rustc-link-arg](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-arg)
- [cargo:rustc-link-search](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-search)
- [MSVC linker options: /DEFAULTLIB](https://learn.microsoft.com/en-us/cpp/build/reference/nodefaultlib-ignore-libraries?view=msvc-170)
- [MSVC linker options: /NODEFAULTLIB](https://learn.microsoft.com/en-us/cpp/build/reference/defaultlib-specify-default-library?view=msvc-170)


Therefore, it is possible to delete `build.rs` by specifying rustflags in the [.cargo/config.toml](https://doc.rust-lang.org/cargo/reference/config.html) as follows.
```
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = [
    "-L", "link-search=native=./cargo/msvcrt.lib",
    "-C", "link-arg=/NODEFAULTLIB:libvcruntimed.lib",
    "-C", "link-arg=/NODEFAULTLIB:vcruntime.lib",
    "-C", "link-arg=/NODEFAULTLIB:vcruntimed.lib",
    "-C", "link-arg=/NODEFAULTLIB:libcmtd.lib",
    "-C", "link-arg=/NODEFAULTLIB:msvcrt.lib",
    "-C", "link-arg=/NODEFAULTLIB:msvcrtd.lib",
    "-C", "link-arg=/NODEFAULTLIB:libucrt.lib",
    "-C", "link-arg=/NODEFAULTLIB:libucrtd.lib",
    "-C", "link-arg=/DEFAULTLIB:libcmt.lib",
    "-C", "link-arg=/DEFAULTLIB:libvcruntime.lib",
    "-C", "link-arg=/DEFAULTLIB:ucrt.lib",
]
``` 
note: About above `msvcrt.lib`, use the file [generated by static_vcruntime](https://github.com/ChrisDenton/static_vcruntime/blob/main/src/lib.rs#L112) as it is.

**Comment by fukusuket** [comment]
I have also confirmed that `build.rs` can be deleted with the following simple measures.
https://github.com/ChrisDenton/static_vcruntime#issues

However, with the above fix, the performance dropped about 1.5 times :(
(probably due to library conflicts...)

**Comment by hitenkoku** [comment]
@fukusuket Thank you for your request.
I agree deleting build.rs  by  add rustflag in .cargo/cargo.toml and remain comment .
