### ISSUE TITLE
Enhancement: Add top alerts to results summary

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#667]
Results Summaryの`Top 5 computers with most unique xxx detections`の後、`Top critical alerts:`、`Top high alerts:`等々(informationalまで）のTop 5アラート(`%RuleTitle%`)とその検知数を表示したいです。
無い場合は`None`を表示します。
他のサマリと同じように色を付けます。

```
例：
Top critical alerts:
Lateral movement (30)
PSEXEC (20)
Hashdump (10)

Top high alerts:
None

Top medium alerts:
Alert 1 (100)
Alert 2 (90)
Alert 3 (80)
Alert 4 (70)
Alert 5 (60)

等々(informationalまで）
```

**Comment by hitenkoku** [comment]
一旦確認します

**Comment by hitenkoku** [comment]
確認したところ特に問題なさそうだったので私の方で対応します。

**Comment by YamatoSecurity** [comment]
ありがとうございます！

**Comment by hitenkoku** [comment]
念のため今後ないとは思いますが、RuleTitleに重複があった場合は考慮したほうがよろしいでしょうか。

**Comment by hitenkoku** [comment]
o

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応が完了しました。ご確認のほどよろしくお願いいたします。
