### ISSUE TITLE
Enhancement: --no-summary option

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#672]
Results Summaryが最近長くなって、バックグラウンドエージェントとしてhayabusaを使っている場合は不要だったりするので、サマリを非表示にできるようにしたいです。
`DISPLAY-SETTINGS:`配下の`--no-summary`オプションで`Saved File: xxx`と`Elapsed Time: xx`の間の`Results Summary`を計算しないで、表示しない機能です。

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応完了しました。お手数ですがご確認のほどよろしくお願いいたします。
