### ISSUE TITLE
[bug] Hayabusa crashes with -L logon summary

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#674]
**Describe the bug**
Hayabusa crashes with -L logon summary

**Step to Reproduce**
`hayabusa.exe -d ../hayabusa-sample-evtx -L`

**Screenshots**

<img width="1065" alt="Screen Shot 2022-08-22 at 9 34 06" src="https://user-images.githubusercontent.com/71482215/185818303-b1aef11d-1a80-49a7-8b4e-a3b973299d05.png">

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version: 1.5.1
 - not affected: 1.4 and below

**Comment by YamatoSecurity** [comment]
@hitenkoku すみませんが、見て頂けますか？

**Comment by hitenkoku** [comment]
確認します

**Comment by hitenkoku** [comment]
確認ができました。一部のデータでNumberではなくStringでデータが入ってしまっていることが原因のようです。
