### ISSUE TITLE
Condense results summary

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#675]
Results Summaryがとても縦長くなっているので、prettytable-rsテーブルを使って、もう少しコンパクトにしたいです:
* Total DetectionsとUnique Detectionsを横にする。
* Top critical alertsとTop high alertsを横にする。
* Top medium alertsとTop low alertsを横にする。

横にするイメージ:
<img width="667" alt="Screen Shot 2022-08-22 at 10 41 54" src="https://user-images.githubusercontent.com/71482215/185822629-801a164c-82ca-41ef-ab94-fd97888f5d01.png">

と思ったが、 @hitenkoku テーブルにすると、様々のカラー出力ができなくなりますか？
(カラー出力が優先なので、そうであればテーブルを諦めましょう）

**Comment by hitenkoku** [comment]
確認はしていないですが、できなくなる可能性は高いです。できたとしても外部ファイルで色指定をするなどの対応は難しそうに思えます。

**Comment by hitenkoku** [comment]
@YamatoSecurity 確認しました。prettytableはカラー出力は可能ですが、固定値で複数種類あるという形です。検知結果のように外部ファイルから読み込んで、それと同じ値を使いたい場合はprettytableだと対応できません。

**Comment by hitenkoku** [comment]
@YamatoSecurity 確認しました。prettytableはカラー出力は可能ですが、固定値で複数種類あるという形です。検知結果のように外部ファイルから読み込んで、それと同じ値を使いたい場合はprettytableだと対応できません。ref https://phsym.github.io/prettytable-rs/master/prettytable/color/index.html

**Comment by YamatoSecurity** [comment]
確認して頂いて、ありがとうございます！なるほど〜、色々悩ましいですね。
では、テーブルをやめた方が良さそうですが、もう少し考えてみます。

**Comment by YamatoSecurity** [comment]
テーブルをやめましょう。

取り敢えず、以下のようにTotalとUnique detectionsを一緒にしましょう。
```
Total detections: 32,726
Total critical detections: 52 (0.16%)
Total high detections: 6,101 (18.64%)
Total medium detections: 1,365 (4.17%)
Total low detections: 6,766 (20.67%)
Total informational detections: 18,442 (56.35%)

Unique detections: 543
Unique critical detections: 19 (3.50%)
Unique high detections: 241 (44.38%)
Unique medium detections: 153 (28.18%)
Unique low detections: 77 (14.18%)
Unique informational detections: 53 (9.76%)
```
↓
```
Total | Unique detections: 32,726 | 543
Total | Unique critical detections: 52 (0.16%) | 19 (3.50%)
Total | Unique high detections: 6,101 (18.64%) | 241 (44.38%)
Total | Unique medium detections: 1,365 (4.17%) | 153 (28.18%)
Total | Unique low detections: 6,766 (20.67%) | 77 (14.18%)
Total | Unique informational detections: 18,442 (56.35%) | 53 (9.76%)
```

**Comment by hitenkoku** [comment]
承りました。それではそのように実装させていただきます

**Comment by YamatoSecurity** [comment]
PRありがとうございます！
良い感じです。ターミナルを全画面にしたらギリギリResults Summaryが収まるが、Saved file情報がまだ見えないので、できれば、もう少し簡潔にしたいです。

同じ行に複数のカラー出力は可能ですか？
可能だったら
```
Date with most total critical detections: 2019-07-19 (15)
Date with most total high detections: 2016-09-20 (3,653)
Date with most total medium detections: 2021-04-22 (146)
Date with most total low detections: 2016-09-20 (3,780)
Date with most total informational detections: 2016-08-19 (2,105)
```
を
↓
`Most total detections: Critical: 2019-07-19 (15), High: 2016-09-20 (3,653), Medium: 2021-04-22 (146), Low: 2016-09-20 (3,780), Info: 2016-08-19 (2,105)`
にしたいです。
(※`Dates with`は書かなくても分かるので、省きました。各レベルと日付はそれぞれのカラーで）

**Comment by hitenkoku** [comment]
同じように複数の出力は対応可能です。対応完了しましたら連絡いたします

**Comment by YamatoSecurity** [comment]
ありがとうございます！

**Comment by hitenkoku** [comment]
対応が完了しました。ご確認のほどよろしくお願いいたします。

**Comment by hitenkoku** [comment]
alertsのタイトルとかも今のところタイトルごとに改行していますが、改行無しでまとめておきましょうか？

**Comment by YamatoSecurity** [comment]
対応、ありがとうございます！
少し長かったので、以下のように短くしました：
```
Dates with most total detections:
critical: 2019-07-19 (15), high: 2016-09-20 (3,653), medium: 2021-04-22 (146), low: 2016-09-20 (3,780), informational: 2016-08-19 (2,105)
```

alertsタイトルは長いので、改行なしよりも、最初に考えていたテーブルで横にしたいが、枠を出力するのではなく、タブで少しalign rightで良いかなと思います。
例えば、https://stackoverflow.com/questions/30379341/how-to-print-well-formatted-tables-to-the-console のように。
イメージ:
<img width="800" alt="Screen Shot 2022-08-25 at 6 02 53" src="https://user-images.githubusercontent.com/71482215/186523040-cd3b87c6-8d6a-4239-b738-ae6937ed341a.png">
（だけどカラー付きで）
mediumとlowアラートも横にしたいです。

ただ、criticalとhigh、mediumとlowのアラート数が4件以下で一致しない場合もあり得るので、ずれないように4件以下の場合は、アラートルールが無いとろこに`N/A`を入れた方が良さそうです。
例：
<img width="796" alt="Screen Shot 2022-08-25 at 6 07 48" src="https://user-images.githubusercontent.com/71482215/186523754-fe1a0aac-d9fa-4519-abc4-ffce461101c2.png">

**Comment by hitenkoku** [comment]
タブで整えるやり方ですが、文字数をカウントして整えないといけない為、prettytableと同様のことをやることになるので手間がかかります。例として出していただいたstackoverflowは文字数の最大値を入れないと体裁を整えることができません。

また、N/Aの件ですが、4件以下で一致しない場合というのがよくわかっていません。
alertsで検出されているルールの種類が5件に満たない場合、例えばA ,B, Cの3種類のみでの時に以下のように出力したいという認識で合ってますか。

Top xxxx alerts:
A(3)
B(2)
C(1)
n/a
n/a

**Comment by YamatoSecurity** [comment]
> タブで整えるやり方ですが、文字数をカウントして整えないといけない為、pretytableと同様のことをやることになるので手間がかかります。例として出していただいたstackoverflowは文字数の最大値を入れないと体裁を整えることができません。stackoverflowに書いてあるtable crateについても、pretytableと同じく、外部から色の情報を引き渡すことができないので対応が難しいです。

なるほど。。タブの方がもっと簡単だと思ったが、結局ややこしいことになるんですね。文字数の最大値は一番長いルールタイトル+20文字？などで良いと思ったけど、カラー出力が難しくなるんだったら、prettytableを使った方が良さそうですね。

今使っている色をprettytableの
　- critical : BRIGHT_RED
　- high: BRIGHT_YELLOW
　- medium: BRIGHT_GREEN
　- low: BRIGHT_CYAN
　- total and informational : BRIGHT_WHITE
に合わせることはできますか？同じ色にできれば、pretty tableに合わせても良いと思いますが、微妙に違う色になるんだったら、見た目が変になるかもしれないので、悩ましいですね。

> また、N/Aの件ですが、4件以下で一致しない場合というのがよくわかっていません。
alertsで検出されているルールの種類が5件に満たない場合、例えばA ,B, Cの3種類のみでの時に以下のように出力したいという認識で合ってますか。

うまく説明できなくてすみません。はい、そういうことです。
ま、空白でも大丈夫です。一番気にしているのは、もしcriticalとhighがなかった場合は:
```
Top critical alerts:                    Top high alerts:





Top medium alerts:                 Top low alerts:
A(5)                                           A(5)
B(4)                                            B(4)
等々
```
で無駄な改行が入るので、無駄の改行が無いように工夫が必要かなと思いました。

**Comment by hitenkoku** [comment]
承りました。いったん対応してみます

**Comment by hitenkoku** [comment]
色比較しやすいように1画面で載せた版(lowはBright:Blueを利用しています)

![image](https://user-images.githubusercontent.com/2350416/186679293-f3d7ff5b-7e14-490b-949a-8a1f5c6d5451.png)

**Comment by YamatoSecurity** [comment]
なるほど、ありがとうございます！ま、とりあえず近い色でも良い気がしてきました。
調べたら、prettytables-rs以外に他のcrateもありました：Comfy-tableが良さそうですが、どう思いますか？
https://github.com/Nukesor/comfy-table

Term-table-cliとcli-tableというもっとシンプルなものもあるようです。

Prettytablesはたまにcargoの更新とPRのマージ以外は維持されないそうですね。

因みに、できれば、`--style rounded`のテーブルにしたいです。(例: https://github.com/wfxr/csview)
(`--style rounded`はコマンドプロンプトで無事に表示されるかな？）

**Comment by YamatoSecurity** [comment]
あと、prettytable-rsもcomfy-tableのheader 2のように、幅を固定にして、自動折返しはできますか？
https://rustrepo.com/repo/nukesor-comfy-table-rust-command-line
これも便利かも。(特に画面出力をテーブル出力にした場合）

**Comment by hitenkoku** [comment]
comfy-table を軽く確認してみました。現在カラー出力を使っているtermcolorへの対応をしているので今の外部ファイルで設定した色も反映できるかもしれません。
一度comfy-tableで作成してみましょうか？

**Comment by YamatoSecurity** [comment]
> 一度comfy-tableで同じように色が出るか確認してみましょうか？

はい、ありがとうございます！

あと、今テーブル(crit/high、med/low、info)の間に改行が入っているが、一個の6セルのテーブルにできますか？ 

一番右下は空白になるので、そこに
```
Dates with most total detections:
critical: 2019-07-19 (15)
high: 2016-09-20 (3,653)
medium: 2021-04-22 (146)
low: 2016-09-20 (3,780)
informational: 2016-08-19 (2,105)
```
を入れますか？

**Comment by hitenkoku** [comment]
@YamatoSecurity  comfy_tableを利用することで、外部ファイルで利用している色を反映して出力することができました。

右下の項目については各行で色が異なっているため、comfy_tableでも対応できませんでした。
comfy_tableはセル単位での色付けはできるが、記載されている文字単位での記載はできないです。

![image](https://user-images.githubusercontent.com/2350416/186952650-d0387e21-fc47-4b8e-9f6f-0bf54f2ff14e.png)

**Comment by hitenkoku** [comment]
やるのであればTop 5 computers... の方を表に入れることはできます。ただ、それをすると表示領域は逆に増えそうなのでやめておいた方がよさそうでしょうか

Top critical alerts | Top5 computers ... critical detections|
Top high alerts | Top5 computers ... high detections|
...

**Comment by YamatoSecurity** [comment]
なるほど、そうですね、Top 5 computersは長いので、これでいきましょう！
とても良い感じです。

**Comment by YamatoSecurity** [comment]
もう一つすみません。。
```
Top 5 computers with most unique critical detections: MSEDGEWIN10 (6), IEWIN7 (3), FS03.offsec.lan (2), rootdc1.offsec.lan (2), IE10Win7 (2)
Top 5 computers with most unique high detections: MSEDGEWIN10 (105), IEWIN7 (67), FS03.offsec.lan (31), fs03vuln.offsec.lan (26), IE10Win7 (22)
Top 5 computers with most unique medium detections: MSEDGEWIN10 (63), IEWIN7 (36), FS03.offsec.lan (15), IE10Win7 (14), PC01.example.corp (14)
Top 5 computers with most unique low detections: MSEDGEWIN10 (36), IEWIN7 (18), FS03.offsec.lan (16), fs03vuln.offsec.lan (13), IE10Win7 (11)
Top 5 computers with most unique informational detections: MSEDGEWIN10 (19), IEWIN7 (17), fs01.offsec.lan (16), PC01.example.corp (13), FS03.offsec.lan (12)
```
は同じ文章を数回リピートしているので、以下のようにしたいですが、お願いできますか？
```
Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (6), IEWIN7 (3), FS03.offsec.lan (2), rootdc1.offsec.lan (2), IE10Win7 (2)
high: MSEDGEWIN10 (105), IEWIN7 (67), FS03.offsec.lan (31), fs03vuln.offsec.lan (26), IE10Win7 (22)
medium: MSEDGEWIN10 (63), IEWIN7 (36), FS03.offsec.lan (15), IE10Win7 (14), PC01.example.corp (14)
low: MSEDGEWIN10 (36), IEWIN7 (18), FS03.offsec.lan (16), fs03vuln.offsec.lan (13), IE10Win7 (11)
informational: MSEDGEWIN10 (19), IEWIN7 (17), fs01.offsec.lan (16), PC01.example.corp (13), FS03.offsec.lan (12)
```

**Comment by hitenkoku** [comment]
@YamatoSecurity  修正が完了しました。ご確認のほどよろしくお願いいたします。

表示を減らしたいというご要望でしたら、変化量は小さいですが以下のように変更すると1行は減らせるかもしれませんがいかがでしょうか

- 現在
```
Total events: 64,948
Data reduction: 45,489 events (70.04%)
```

- 提案
```
Detected events / Total events:  19,459 / 64,948 (reduced 45,489 events (70.04%) )
```

**Comment by YamatoSecurity** [comment]
遅くなってすみません！
PRは良い感じです！
細かいところ一つだけ: Top xxx alertsと`Elapsed Time`の間に改行２つあるようですが、一つにできますか？

> 表示を減らしたいというご要望でしたら、変化量は小さいですが以下のように変更すると1行は減らせるかもしれませんがいかがでしょうか

提案、ありがとうございます！良いですね。
是非お願いします！

**Comment by hitenkoku** [comment]
お待たせいたしました。ご指摘いただいた箇所と文面の修正対応が完了しました。
ご確認のほどよろしくお願いいたします。
