### ISSUE TITLE
Display top 10 informational alerts

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#678]
Top alertsのテーブルの一番右下が空白でもったいないので、informationalイベントだけTop 10を出したいと思います。
右側に#6~#10を出力します。
また、全てがinformationalイベントだと分かるように、もし真ん中のヘッダーセパレータを非表示にできたら非表示にしたいです。
この部分：
<img width="735" alt="Screen Shot 2022-08-31 at 9 16 35" src="https://user-images.githubusercontent.com/71482215/187565883-c1e5a5a1-207c-4cdd-ba1d-f65b262566c5.png">

**Comment by hitenkoku** [comment]
承りました。同じTableで作っているので対応が可能かどうか見てみます

**Comment by YamatoSecurity** [comment]
なるほど。同じテーブルにするのは難しいのであれば、別のテーブルにしても良いと思います。

**Comment by hitenkoku** [comment]
はい、一旦確認させてください。

あとはinformationalよりもcriticalを一行で10項目出すようにして、以下のような表で5項目出すほうが良いような気もしますがいかがでしょうか？

|critical(1-5)  ciritical(6-10)|
|high | medium|
|low  | info |

**Comment by hitenkoku** [comment]
確認してみましたが、
comfy-tableのREADMEでは以下のように記載されており、そもそも複数列をまたぐようなセルは作れないようです。一旦tableの区切り線をなくす形で大きな一つのセルのテーブルができないかを確認しておきます。

> Some things however will most likely not be added to the project since they drastically increase the complexity of the library or cover very specific edge-cases.
> 
> Such features are:
> 
> Nested tables
> Cells that span over multiple columns/rows
> CSV to table conversion and vice versa
