### ISSUE TITLE
[bug] Total events is actually the number of scanned events

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#683]
**Describe the bug**
細かいバグですが、スキャン後のTotal eventsがデフォルトのイベントIDフィルタが有効になっている場合と`-D`で無効になっている場合は合計が変わります。evtxファイルにあるイベント数の合計ではなく、Hayabusaがスキャンしたイベント数の合計になっていると思います。

**Step to Reproduce**
Hayabusaをデフォルトの設定と`-D`のオプションで実行して、`Total events:`の数を比較する。

**Expected behavior**
イベントIDフィルタは関係なく、元々のevtxにあるイベント数のTotal events数を表示した方が良いです。

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version: 1.6.0-dev

**Comment by YamatoSecurity** [comment]
実装が難しいのであれば、`Total events`を`Scanned events`という言い方に変えば良いかも。

**Comment by hitenkoku** [comment]
@YamatoSecurity  #684 にて対応完了しました。ご確認のほどよろしくお願いいたします。
