### ISSUE TITLE
Make Channel field in channel_abbreviations.txt case-insensitive

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#685]
evtxログのChannel名がなぜか小文字にることがあります。
例：`Security`ではなく、`security`
`Microsoft-Windows-PowerShell/Operational`→`microsoft-windows-powershell/operational`

その場合は、CSVのChannel列が`sec`や`PwSh`ではなく、長い小文字のチャンネル名で記録されるので、`rules/config/channel_abbreviations.txt`のチャンネル名を変換する時に大文字小文字を区別しないようにしたいです。

**Comment by hitenkoku** [comment]
regexをかけると処理時間がかかってしまう可能性があるためchannnelの文字をどちらも一旦小文字に直してから比較をするようにします

**Comment by hitenkoku** [comment]
@YamatoSecurity #686 で対応が完了しました。ご確認のほどよろしくお願い致します。
処理時間については誤りがありましたので再度測定し直したところそこまで時間はかかってませんでした。
