### ISSUE TITLE
Change pipe separator character

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#687]
1. コマンドラインオプション等の画面出力に`|`が出力されることがあるので、フィールドの`|`セパレータを`‖`に変えます。
例：
`2022-09-03 13:26:07.810 +09:00 | WinDev2208Eval | Sec | 4624 | info |  | 10692 | Logon (Type 2 Interactive) *Credentials stored in memory* | User: User ¦ Comp: WINDEV2208EVAL ¦ IP-Addr: 127.0.0.1 ¦ LID: 0x30d8b`
↓
`2022-09-03 13:26:07.810 +09:00 ‖ WinDev2208Eval ‖ Sec ‖ 4624 ‖ info ‖  ‖ 10692 ‖ Logon (Type 2 Interactive) *Credentials stored in memory* ‖ User: User ¦ Comp: WINDEV2208EVAL ¦ IP-Addr: 127.0.0.1 ¦ LID: 0x30d8b`

2. タグフィールド(MitreTags, MitreTactics, OtherTags)のセパレータを` : `から` ¦ `に変えます。
例
`2022-09-03 13:26:07.810 +09:00 ‖ WinDev2208Eval ‖ Sec ‖ 4624 ‖ info ‖ LatMov ¦ PrivEsc ‖ 10692 ‖ Alert ‖ User: User ¦ Comp: WINDEV2208EVAL ¦ IP-Addr: 127.0.0.1 ¦ LID: 0x30d8b`

3. `Timestamp|Computer|Channel|EventID|Level|MitreTactics|RecordID|RuleTitle|Details`のヘッダーにスペースがなくて、少し読みにくいので以下のようにする: 
`Timestamp ‖ Computer ‖ Channel ‖ EventID ‖ Level ‖ MitreTactics ‖ RecordID ‖ RuleTitle ‖ Details`

**Comment by hitenkoku** [comment]
@YamatoSecurity 確認したところ、現在利用している文面への変換を行っているcsv::WriteBuilderだと区分けを行うdelimeterはASCII文字になるため、ご指摘の内容の文字が利用できません。別の文字をご指定頂けますでしょうか
