### ISSUE TITLE
Add color to Saved alerts and events / Total events analyzed

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#690]
Saved alerts and events / Total events analyzedを一行にしたので、少し読みにくくなったため、以下のように色を付けたいです。

<img width="1232" alt="Screen Shot 2022-09-09 at 10 21 40" src="https://user-images.githubusercontent.com/71482215/189252517-a42f95a2-c180-4a6c-b7ac-fc53cf540e1d.png">

色はアラートで出しているgreen, blue yellowと同じ。

@hitenkoku 一行に複数の色の出力は可能ですか？

**Comment by hitenkoku** [comment]
確認してみます。

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応が完了しました。ご確認のほどよろしくお願いいたします。一応固定文であれば1行の中に複数色を出すことはできます。(comfytableのセル内での色分けはできません。)
