### ISSUE TITLE
[bug] Saved alerts and events calculation is wrong?

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#692]
**Describe the bug**
例: `./target/release/hayabusa -d ../hayabusa-sample-evtx`を実行したら、
```
Results Summary:

Saved alerts and events / Total events analyzed: 19,545 / 76,967 (Data reduction: 57,422 events (74.61%))

Total | Unique detections: 32,670 | 550
```
となりますが、私の認識ではSaved alerts and eventsの合計はTotal detection (上記の32,670)と同じ値になるはずだと思いますが、今はどのように計算していますか？

**Expected behavior**
Saved alerts and eventsは保存される行数になるはずです。(CSVヘッダーを除いて）
つまり、Total detectionと同じ。

**Environment (please complete the following information):**
 - hayabusa version: 1.6.0-dev

**Additional context**
(`-D`オプションの)1.5.1では 
```
Total events: 76,967
Data reduction: 57,422 events (74.61%)

Total detections: 32,670
```
になっているが、Data reductionの計算は
`Total events (76,967) - Total detections (32,670) = 44,297 (57%)`の方が正しいですよね？

**Comment by hitenkoku** [comment]
@YamatoSecurity #683 で指摘された通り、検査対象のevtxの全レコードの数がTotal events analyzedの数値となります。

Data Reductionはその計算だと負の値を取る可能性があります。

Total  detectionsの方は単純に検知した数(1レコードに複数のルールが検知したらそれぞれカウントする)なので場合によってはレコードの数を超える可能性もありますのでそのように修正をしています。

レコードの時間の文字列とイベントIDの組で管理をもとに管理したセットを用意しています。このセットは複数個のルールで検知されても1としてカウントします。
Data Reductionの計算は Total events(76,967) - (セットの長さを引いた値)にしています。

時間が完全に一致していて同じイベントIDは基本複数個存在しないと考えたうえでの設計になります。

**Comment by YamatoSecurity** [comment]
なるほど。思い出しました！失礼しました！
これが正解です。
文章を`Saved alerts and events`を`Events with hits`に変えばOKです。
