### ISSUE TITLE
Output to JSONL

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#694]
`-J, --jsonl                Save the timeline in JSONL format (ex: -J -o results.json)`

@hitenkoku JSON出力機能ができたら、JSONLの出力も簡単にできますか？

**Comment by hitenkoku** [comment]
はい、少し確認は必要ですが、ある程度は今のJSON出力機能を利活用して対応できると思います

**Comment by hitenkoku** [comment]
JSONLですが、推奨されている拡張子は.jsonlなのでconfigについてはそのように対応しようと思います。

**Comment by hitenkoku** [comment]
@YamatoSecurity  対応が完了しました。お時間のある時にご確認いただけますと幸いです。
