### ISSUE TITLE
Add CODE BLUE 2022 badge to readme

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#695]
Add CODE BLUE 2022 badge to readme

**Comment by hitenkoku** [comment]
@YamatoSecurity  URLを教えてもらえればこちらで対応しますがいかがでしょうか

**Comment by YamatoSecurity** [comment]
ありがとうございます！もしかして無いです。この間のBlackhat Asiaはどうやって作ったんですか？
多分作るしかないです。

**Comment by hitenkoku** [comment]
承りました。
それであれば、こちらで作ってしまいますね。こういう形はいかがでしょうか？

https://img.shields.io/badge/CODEBLUE-2022%20Bluebox-blue

**Comment by hitenkoku** [comment]
@YamatoSecurity #696 に配置順も含めてpull-requestを出しておきましたのでご確認のほどよろしくお願いいたします。
