### ISSUE TITLE
Support Field|base64offset|contains: aggregator

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#705]
現在９件のルールが`Field|base64offset|contains:`を使っていますが、対応していないので、使えません。

```
.//wmi_event/sysmon_wmi_susp_encoded_scripts.yml:        Destination|base64offset|contains:
.//process_creation/proc_creation_win_encoded_frombase64string.yml:    - CommandLine|base64offset|contains: '::FromBase64String'
.//process_creation/proc_creation_win_encoded_iex.yml:    - CommandLine|base64offset|contains:
.//process_creation/proc_creation_win_powershell_defender_disable_feature.yml:        CommandLine|base64offset|contains:
.//process_creation/proc_creation_win_powershell_defender_base64.yml:        CommandLine|base64offset|contains:
.//builtin/security/win_security_cobaltstrike_service_installs.yml:        ServiceFileName|base64offset|contains: "IEX (New-Object Net.Webclient).DownloadString('http://127.0.0.1:"
.//builtin/system/win_cobaltstrike_service_installs.yml:        ImagePath|base64offset|contains: "IEX (New-Object Net.Webclient).DownloadString('http://127.0.0.1:"
```

`contains`で検知したい文字列はbase64でエンコードされていますが、offsetによってエンコードされた文字列が３つの可能性になります。
正しく検知するのに、ルール変換時に３つのbase64でエンコードされた文字列を探す必要があります。

CyberChefで３つのoffsetを計算する例:
<img width="1274" alt="Screen Shot 2022-09-25 at 6 39 02" src="https://user-images.githubusercontent.com/71482215/192119630-0da00f46-ce89-4f1a-9425-1076bf32cfe3.png">

詳細情報:
![base64-offset](https://user-images.githubusercontent.com/71482215/192119647-8bc03ec5-2924-44a3-bb28-b70aae289e99.png)

注意: hayabusa.pyのバックエンドが対応していないので、変換時に失敗して、変換されたファイルが作成されません。`Field|base64offset|contains:`を無視するようにhayabusa.pyを修正する必要があります。

この機能は全部hayabusa.pyで対応して、変換時に３つのエンコードされた文字列を出力するようにできますが、便利なのでhayabusaルールでも`Field|base64offset|contains:`に対応したいです。

**Comment by hitenkoku** [comment]
mtg memo: hayabusa.pyの実装は、かなり難しいので、hayabusa側で対応したほうが良さそう。とは言えhayabusa側でも注意して実装しないと遅さに直結することになる(現在の構成に処理を追加することで対応はできる)。

**Comment by YamatoSecurity** [comment]
因みに`|base64offset|equalsfield`とか`|base64offset|startswith`等々の他の組み合わせに対応しなくても良いはずなので、２つのパイプは入っているが`|base64offset|contains`は`|base64offsetcontains`というような一つのaggregatorとして実装した方が良いかもしれません。ま、`|base64offset|startswith`と`|base64offset|endswith`というルールは今ありませんが、一応有り得そうです。
`|base64offset|equalsfield`と`|base64offset|re`の組み合わせは不可能です。

（メモ）

**Comment by hitenkoku** [comment]
ref: https://github.com/gchq/CyberChef/blob/a3b873fd96111fe2dbcb62a1e037987669290a13/src/core/operations/ShowBase64Offsets.mjs#L60

**Comment by hach1yon** [comment]
sigmaルールからhayabusaルールに変換するスクリプトの方も修正する必要あり。
