### ISSUE TITLE
Change Event ID Statistics wording to Metrics

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#706]
`-s, --statistics`オプション名ですが、英語でこういう集計のことをstatisticsという人が多いが、よく考えたら本当はmetricsの方が正しいと思うので、`-M, --metrics`に変えたいです。混乱しないようにソースコードの方でもstatisticsをmetricsに変えた方が良さそうです。

**Comment by hitenkoku** [comment]
対応します。こちらはオプションの文面は変更なしで良いでしょうか。

オプション名変更に伴いファイル名の方もmetricsに変えておこうと思います

**Comment by YamatoSecurity** [comment]
ありがとうございます！はい、基本的にstatisticsという単語を全部metricsに変えたいです。

**Comment by hitenkoku** [comment]
了解しました。それであればソースコードのファイル名変更も含めて対応しておきます

**Comment by hitenkoku** [comment]
一部そのままにしておいたほうが良さそうなファイルがありましたので共有しておきます。

rules内のstatistics_event_info.txtはrulesレポジトリで管理をしているので、metrics_event_info.txtに名前を変えてしまうと、
ユーザがrulesをアップデートしていないとエラーが出るようになってしまうのでrulesで管理しているconfigファイルはrenameの対象外とさせていただければと思います。

**Comment by YamatoSecurity** [comment]
なるほど。`statistics_event_info.txt`をすぐ消すと良くないですね。取り敢えず新しく使う`event_id_info.txt`を用意しました。
https://github.com/Yamato-Security/hayabusa-rules/pull/121

互換性のために２つのファイルを置いて、３ヶ月後?に`statistics_event_info.txt`を消しましょうか？
