### ISSUE TITLE
Analyze metrics of Event IDs when scanning directory together

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#707]
`-s -d <dir>`を指定した場合は、各ファイルの集計を取っていますが、情報が多くてバラバラなので、あまり役に立ちません。
ので、以下のように改善したいです。

1. `-s`を`-d`と一緒に使う場合は、全てのevtxをスキャンした上で、一個のテーブルで情報を出す。
2. チャンネル名が分からなくなるので、`Channel`カラムを追加する。
3. `-d`では、First TimestampとLast Timestampの情報を出さない。
4. `-s -d <dir> -o <output.csv>`のように`-o`も指定された場合は結果をCSVに出力する。
5. 現在Countと(Percent)を同じ列にしているが、CSV解析等のため、２つの列に分ける。

**Comment by hitenkoku** [comment]
@YamatoSecurity 一点確認させてください。
2. と 5. は-dオプションがなくても実施するということでよろしいでしょうか。


また、現在comfy_table対応を @garigariganzy に行ってもらっていますが、この対処を行うとConflictを起こします。本機能の優先度が高いのであれば、私が以下の2つを実施しますがいかがでしょうか。

- comfy_table への変更対応
- このissueの対応

**Comment by YamatoSecurity** [comment]
@hitenkoku ありがとうございます。
2.と5.は`-f`オプションでも同じように実施しましょう。

上の提案に賛成です。 @garigariganzy どうですか？

**Comment by garigariganzy** [comment]
@YamatoSecurity @hitenkoku さんの案でお願いいたします。本件、完了後、#463 にマージして対応進めます。よろしくお願いいたします。

**Comment by hitenkoku** [comment]
@hitenkokuが実施することで決定したため担当者を変更

**Comment by hitenkoku** [comment]
-s と書いていましたが、-M オプションとして対応します。
