### ISSUE TITLE
Improve HTML Summary Report

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#712]
refs #689 

This issue is to improve HTML Summary Report by css styling.
css styling is defined in `hayabusa_report.css`.

**Comment by YamatoSecurity** [comment]
<img width="180" alt="Screen Shot 2022-09-27 at 20 04 17" src="https://user-images.githubusercontent.com/71482215/192509515-4b216f16-7758-4a4f-8cd7-71a0b774888b.png">
<img width="169" alt="Screen Shot 2022-09-27 at 20 04 06" src="https://user-images.githubusercontent.com/71482215/192509519-78ea3405-ca34-406c-b486-d291676cfbe7.png">

faviconも追加したいですね〜 (上のどっちか）

**Comment by YamatoSecurity** [comment]
@nishikawaakira 
幅が長いので、http://www.pattern-sozai.website/data/119.php の「背景を変える」をクリックした時のページのように左右をこの和柄にして、結果を真ん中にできますか？

<img width="1738" alt="Screen Shot 2022-09-27 at 21 03 43" src="https://user-images.githubusercontent.com/71482215/192520204-e7e635ce-f070-4b1e-8548-23eedd05ec0f.png">


また、一番上に`logo.png`のロゴを見せたいです。

**Comment by hitenkoku** [comment]
faviconの追加ですがlink要素での追加となるのでhtmlファイル側で出力したほうが良いと思いますがいかがでしょうか。

**Comment by hitenkoku** [comment]
@YamatoSecurity  faviconの追加ですがheadのlink要素での追加となるので #689 でhtmlファイル側で出力させていただきます。htmlではfavicon.pngを参照するようにしておいてどちらを使うかはこのissueで相談しましょう。

あと、念のため確認しておきたいのですが、iconの方って自由に使っていいものですか？アイコンのライセンス的なものを気にしています。

**Comment by hitenkoku** [comment]
faviconについても #689 側で対応しました。こんな感じで見えています。

![image](https://user-images.githubusercontent.com/2350416/192531258-af9bff46-9de9-4f13-a154-51def5d2d406.png)

**Comment by nishikawaakira** [comment]
基本的にcssしかいじらない予定でしたので、ロゴとか出す場合は faviconと同じ対応が必要ですね。
背景出す場合はbodyタグが必要になります。

**Comment by hitenkoku** [comment]
bodyタグは存在していますので大丈夫です

**Comment by hitenkoku** [comment]
ロゴ出力についてはどうしましょうかね。#689 をマージしてしまったので別のissueつけて私の方で対応しましょうか

**Comment by YamatoSecurity** [comment]
@hitenkoku もっと早く言えば良かったです。ごめんなさい。お手数をかけますが、別のissueでお願いできますか？

**Comment by nishikawaakira** [comment]
@hitenkoku すみません、bodyタグだけではダメでした。下記のようにすることは可能でしょうか？
```
<body>
  <section>
     結果
  </section>
</body>
```

**Comment by hitenkoku** [comment]
@nishikawaakira  sectionで全体を囲む形にすればよいでしょうか。それであればこちらのほうで今logo.pngを追加しているブランチで対応をしてみます。

**Comment by nishikawaakira** [comment]
@hitenkoku はい、それでお願いしたいです。やり方教えてもらって私が対応でもOKです!

**Comment by YamatoSecurity** [comment]
@nishikawaakira https://github.com/Yamato-Security/hayabusa/pull/715 をマージしたので、main branchをコンパイルして、使って下さい。遅くても明日の朝に1.7.0のリリース版をコンパイルしておきたいので、CSSは今日中にできるところまでお願いしたいです。
バージョン1.7.1を10月10日ぐらいまでにリリースしようと思っているので、今日中に実装が厳しいものがあれば、1.7.1のリリースに入れて頂けたらと思います。

色々急かせて申し訳ありません。

**Comment by hitenkoku** [comment]
すみません。今の #715 だとlogo.pngがセクションに入っていないけど大丈夫そうですか？

**Comment by hitenkoku** [comment]
@YamatoSecurity  #716 で修正したソースコードを出しましたのでご確認の上Approveをお願いいたします。

**Comment by hitenkoku** [comment]
私のコメントで解決したものをResolvedにしてhideにしておきました(cssとかのやり取りでここを使うのにスクロールを毎回するのもよくないと思ったので)

**Comment by YamatoSecurity** [comment]
CSSファイル、favicon、背景の画像ファイル等を`config`配下に置けますか？
もしくは、いつでも更新・修正できるように`rules/config`に置くのはどうですか？

**Comment by YamatoSecurity** [comment]
> そうなると一部html出力側のコードを書き換える必要がありますね。 どこに配置しますか？決めていただければこちらのほうで修正して参照先を変えるようにしようと思います。

ありがとうございます。では、頻繁に更新しなくても良いはずなので、`config/html_report`というディレクトリに配置しましょう。

**Comment by hitenkoku** [comment]
分かりました。ご指摘いただきました内容でpullreauest出しておきます

**Comment by hitenkoku** [comment]
https://github.com/Yamato-Security/hayabusa/pull/718 で対応が完了しました。ご確認のほどよろしくお願いいたします。

> 
> ありがとうございます。では、頻繁に更新しなくても良いはずなので、`config/html_report`というディレクトリに配置しましょう。

**Comment by nishikawaakira** [comment]
![スクリーンショット 2022-09-28 17 54 44](https://user-images.githubusercontent.com/6489077/192735717-8c89286c-9315-4a94-ab22-8c24c4195af4.png)
@YamatoSecurity 
こういうかんじなんです感じなんですけど、背景がbusyな感じはしませんか？よいですか？

**Comment by nishikawaakira** [comment]
@YamatoSecurity 一旦PR( #719  )出しておいたので確認しておいていただければと思います
