### ISSUE TITLE
Output rule authors in standard out

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#724]
今更ですが、シグマルールのライセンスではルール作者の名前を出力しないといけないようなので、`Results Summary`の直前にルール作者の一覧を出力したいです。
イメージ:
`Rules brought to you by:`の後にcomfy-tableの４列のテーブルで作者と(ルール数)を順番に出力します。
```
Author1 (300) | Author2 (200) | Author3 (100) | Author4 (50)
Author5 (30) | Author6 (20) | 等々
```
注意点:
1. 複数の作者があるルールが多いので、コンマの区切りで一個ずつ抽出する
 例: `frack113, Nasreddine Bencherchali` の場合は、`frack113`と`Nasreddine Bencherchali`を別の作者として扱う。
2. `( hogehoge )`の括弧の間に不要の情報があるので、削除する。例: `E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community`の場合は` (originally from Atomic Blue Detections, Endgame)`を削除する。（※たまにTwitter名が括弧に入ったりするけど、本名だけで十分なので、仕方なく消す）
3. ダブルクォートかシングルクォートで囲まれていることがたまにあるので、クォートを削除する: 例: `"Christian Burkard, pH-T"`、`'Florian Roth, Nasreddine Bencherchali @nas_bench'`等々
4. 作者のルール数は合計ではなく、uniqueなルール数

**Comment by hitenkoku** [comment]
念のため以下2点を確認させてください

- uniqueであることの判断はruleのidをもとに判断すればよろしいでしょうか。

- 今回のルールは利用したものを対象とする(検知したかどうかは関係なし)

**Comment by YamatoSecurity** [comment]
確認、ありがとうございます。

> uniqueであることの判断はruleのidをもとに判断すればよろしいでしょうか。

そうですね。rule idを使ったら良さそうです。

> 今回のルールは利用したものを対象とすることでよいでしょうか(検知したかどうかは関係なし)

利用したルール全部ではなく、実際に検知したルールの作者をリストアップしたいです。(例：ヒットが１件の場合は作者一覧に一人だけ出力する。）因みに、ヒットが０件の場合は`Rules brought to you by`のメッセージと作者一覧のテーブルを全部非表示にしましょうか？

**Comment by hitenkoku** [comment]
承りました。それでは検知したもののみ対象とさせていただきます。
