### ISSUE TITLE
Upgrade to Clap 4

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#725]
先日Clap 4.xがリリースされて、見た目が良くなっているのと、これから4.xが主に維持されるので、アップデートしたいです。
### Migrating

Steps:

0. [Upgrade to v3](https://github.com/clap-rs/clap/blob/v3-master/CHANGELOG.md#migrating) if you haven't already
1. Add CLI tests (including example below), `-h` and `--help` output at a minimum (recommendation: [trycmd](https://docs.rs/trycmd/) for snapshot testing)
2. *If using Builder API*: Explicitly set the `arg.action(ArgAction::...)` on each argument (`StoreValue` for options and `IncOccurrences` for flags)
3. Run `cargo check --features clap/deprecated` and resolve all deprecation warnings
4. Upgrade to v4
5. Update feature flags
  - *If `default-features = false`*, run `cargo add clap -F help,usage,error-context`
  -  Run `cargo add clap -F wrap_help` unless you want to hard code line wraps
6. Resolve compiler errors
7. Resolve behavior changes (see "subtle changes" under BREAKING CHANGES)
8. *At your leisure:* resolve new deprecation notices

詳細: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md

**Comment by hitenkoku** [comment]
確認しましたが、testが通らない状況になっているので1.7.1での作成は難しいと判断してv2.0に変えました
