### ISSUE TITLE
Don't display "Loading detections rules. Please wait." with metrics or logon summary option

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#730]
細かいところで申し訳ありませんが、、
`-M`と`-L`オプションで`Loading detections rules. Please wait.`が表示されるが、検知ルールは使われないので、少し紛らわしいです。
可能であれば、`-M`と`-L`時に`Loading detections rules. Please wait.`を非表示にしたいです。

**Comment by hitenkoku** [comment]
うけたまわりました。対応します

**Comment by hitenkoku** [comment]
#732 で作成完了しました。ご確認のほどよろしくお願いいたします。
