### ISSUE TITLE
fix EventID string contains double quote in record

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#735]
> 普段のスキャン時でもイベントIDがダブルクォートに囲まれているせいで、IDが一致しなくて検知漏れが出ている可能性はありそうですか？もしあり得るのであれば、別のissueでイベントIDをチェックする前に全部ダブルクォートをtrimした方が良さそうですが、どう思いますか？

_Originally posted by @YamatoSecurity in https://github.com/Yamato-Security/hayabusa/issues/729#issuecomment-1272188335_

**Comment by hitenkoku** [comment]
@YamatoSecurity テストコードで確認をしてみたところ、文字列としてデータを意図的に入れてみたところ、selectionnodesのテストが通っていることを確認しました。私が試したやり方は以下の行の4103をダブルクォートで囲ってみて確認をして見ました。

https://github.com/Yamato-Security/hayabusa/blob/main/src/detections/rule/selectionnodes.rs#L438

問題がなければ本issueのcloseをお願い致します。

**Comment by YamatoSecurity** [comment]
ありがとうございます！
こちらでも確認できました。問題なさそうですね。では、この件をクローズします。
