### ISSUE TITLE
Limit Rule Author names to 40 characters

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#751]
@hitenkoku これをお願いしても良いですか？

最近とても長いルール作者の名前が出ているので、これ以上長いものが入ったら、テーブルが折返しして、読めなくなるので、今のうちにルール作者の名前を40文字までに制限をかけた方が良いと思いますが、いかがでしょうか？
現在、一番長い名前がちょうど40文字なので、今と変わらないけど、それ以上幅が広くならないようにしたいです。
<img width="1364" alt="Screen Shot 2022-10-16 at 18 12 39" src="https://user-images.githubusercontent.com/71482215/196027656-9fbf328a-37ba-4a63-ae1d-6865e4471f92.png">

**Comment by hitenkoku** [comment]
承りました。40文字を超えた場合は「……」としてomitしても良いですか？

**Comment by YamatoSecurity** [comment]
`...`は確かあった方が良いですね。でも40文字から43文字になったら、x 4列なので、幅が広くなってしまいます。
41文字以上の場合は文字列を37文字にして、最後の３文字を`...`にするのはどうですか？
（ややこしくて申し訳ありません）

**Comment by hitenkoku** [comment]
@YamatoSecurity  #752 で対応が完了しました。ご確認のほどよろしくお願い致します。
