### ISSUE TITLE
[bug] Rule author count is off by one

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#770]
**Describe the bug**
単体のルールを指定した時に、Rule Authorsのところでunique rule数が`1`になっているはずですが、`2`になっています。

**Step to Reproduce**
`./hayabusa-1.7.2-mac-intel -d ../hayabusa-sample-evtx -r ../hayabusa-rules/hayabusa/sysmon/Sysmon_2_Low_PossibleTimestomping.yml`
等適当に単体のルールを指定するだけです。

**Expected behavior**
Rule Authorsのところでunique rule数が`1`になっているはずですが、`2`になっています。

**Screenshots**
<img width="1493" alt="Screen Shot 2022-10-21 at 15 53 04" src="https://user-images.githubusercontent.com/71482215/197132210-c6e37f40-a85b-4843-b293-d6b2f2c82f44.png">

**Environment (please complete the following information):**
 - OS: mac
 - hayabusa version: 1.7.2

**Comment by hitenkoku** [comment]
@YamatoSecurity 
失礼いたしました。カウントアップの初期値を1としてしまっていたことが原因のバグでした。
#783 で修正しましたのでご確認のほどよろしくお願いします。
