### ISSUE TITLE
[bug] %MitreTags%・%MitreTactics% output randomly miss a few value

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#807]
**Describe the bug**
When outputting with a Profile containing `%MitreTags%` and `%MitreTactics%`, the results are different every time.

**Step to Reproduce**

1. execute hayabuse.exe with `-P super-verbose` 2times
   - `hayabusa.exe -d ./hayabusa-sample-evtx -o a.csv -P super-verbose`
   - `hayabusa.exe -d ./hayabusa-sample-evtx -o b.csv -P super-verbose`
2. compare file size
   - (Get-Item -Path "a.csv").Length
   - (Get-Item -Path "b.csv").Length

**Expected behavior**
the two csv have same size

**Actual behavior**
the two csv have different size

**Screenshots**
file size is differ as follows.
![diff](https://user-images.githubusercontent.com/41001169/201678354-4582fef1-727a-402c-a17d-9eaa419e453a.png)

I checked the diff in winmerge, %MitreTags% seems to have a bit of a diff
![win-merge](https://user-images.githubusercontent.com/41001169/201678333-c8368a29-8ad7-40ac-b715-f64c2e0a0963.png)

**Environment (please complete the following information):**

- OS: Windows 10 Home edition.
- hayabusa version 1.8.0 (I haven't checked if it's reproducible in previous versions but may have same issue )

**Comment by fukusuket** [comment]
再現手順で古いバージョンも試したところ、1.5.0 ~ 1.7.2では本事象発生しませんでした。1.8.0でのみ発生する事象のようです🤔（1.7.2までは、発生確率が低いということかもしれないですが）

**Comment by YamatoSecurity** [comment]
@fukusuket 調べてくれてありがとうございました！原因は何でしょうね・・
@hitenkoku 何か心当たりありますか？

**Comment by fukusuket** [comment]
https://github.com/Yamato-Security/hayabusa/blob/v1.8.0/src/detections/detection.rs#L249
↑の処理で`TAGS_CONFIG.values();`を`TAGS_CONFIG.values().sorted();`にすると事象解消しました

https://github.com/Yamato-Security/hayabusa/blob/v1.8.0/src/detections/detection.rs#L338
また↑のfilterをコメントアウトすると、ファイルサイズが一定になりました。

なので、TAGS_CONFIG(HashMap)をvalues()で変換した後の並び順次第でファイルサイズが変わる問題のようで、race condition が原因ではないかもしれません🤔

**Comment by fukusuket** [comment]
```
[dependencies]
itertools = "0.10.5"
hashbrown = "0.12.*"
```

```main.rs
use hashbrown::HashMap;
use itertools::Itertools;

fn main() {
    let mut map = HashMap::new();
    map.insert("a".to_string(), "1".to_string());
    map.insert("b".to_string(), "2".to_string());
    map.insert("c".to_string(), "3".to_string());

    let mut values = map.values();
    println!("{:?}", values);
    let a = values.contains(&"1".to_string());
    let b = values.contains(&"2".to_string());
    let c = values.contains(&"3".to_string());
    println!("a: {}", a);
    println!("b: {}", b);
    println!("c: {}", c);
}
```
上記コードで擬似的に事象が再現しました。
上記実行すると、毎回出力結果が変わります(containsの結果true/falseが不定) :(

結果が毎回異なる理由は、以下2点でした。
- [HashMap::values()](https://docs.rs/hashbrown/latest/hashbrown/struct.HashMap.html#method.values)は、vecではなくiteratorを返し、中身の順序は不定
- [std::vec::Vec::contains()](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.contains)ではなく、[itertools::contains()](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.contains)が実際には呼ばれている
  - Vec::contains()は要素有無の判定だが、itertools::contains()は値が見つかるまでiteratorの要素を消費する(そのため複数回同じiteratorにcontainsすると結果が変わってしまう)

**Comment by hitenkoku** [comment]
ありがとうございます。こちらがitertoolで誤って使っていたのが原因だったのですね。大変失礼いたしました。

**Comment by fukusuket** [comment]
同名の contains() -> bool で内部的な挙動が違うのはなかなか罠ですね😭涙
