### ISSUE TITLE
Parallel processing to improve performance

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#810]
Consider whether parallel processing can be used to improve processing speed.

**Comment by hitenkoku** [comment]
rayonによる並列処理でdetectInfoの登録を並列化したが逆に時間がかかる形になった

**Comment by YamatoSecurity** [comment]
@hitenkoku これをクローズしますか？

**Comment by hitenkoku** [comment]
そうですね。一旦これは想定していたものをやったが、効果がなかったということでcloseさせてください
