### ISSUE TITLE
Test coverage in CI

### ISSUE THREAD

**Issue by kazuminn** [Yamato-Security/hayabusa#812]
CIの方でテストカバーレッジを見れるようにしておくと、
カバーレッジを上げるための策が見つかり、
品質が良くなるかも。

**Comment by hitenkoku** [comment]
FYI:
- https://github.com/marketplace/actions/rust-grcov
- https://qiita.com/shinya_sun_sun/items/6c14e7145235713db434
- https://github.com/actions-rs/example/blob/master/.github/workflows/grcov.yml

**Comment by kazuminn** [comment]
ciで出したカバレージのパーセントをREADMEのバッジに出せるようなので、出せるようにできるとよい。

**Comment by YamatoSecurity** [comment]
今何%か分かりますか？

**Comment by kazuminn** [comment]
@YamatoSecurity 
line numberでは、72%です。
https://github.com/Yamato-Security/hayabusa/pull/820#issue-1456787889
