### ISSUE TITLE
Add SECCON 2023 Shield

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#871]
SECCONでワークショップをすることになったので、`SECCON | 2023`のバッジを追加したいです。

**Comment by hitenkoku** [comment]
おめでとうございます。SECCONのワークショップというと2023/2/11のものとかと思いますが、このWebページは
SECCON2022となっていますが2023で問題ないでしょうか？

また、バッジをクリックした際に移動したいリンクがありましたらお教えください。

**Comment by hitenkoku** [comment]
#872 でひとまずSECCON2022にリンクしたバッジを作成しました。ご確認のほどよろしくお願いいたします。
