### ISSUE TITLE
Add command line to HTML report

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#877]
HTMLレポートのGeneral Overview配下、Start timeの上に`Command line: hayabusa-2.2.0-win-64.exe csv-timeline -d ../hayabusa-rules -o output.csv -H report.html`等のフルコマンドラインを記載したいです。

**Comment by hitenkoku** [comment]
@YamatoSecurity  #880 で対応完了しました。ご確認のほどよろしくお願いたします。
