### ISSUE TITLE
New feature: %ExtraFieldInfo%

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#900]
We have %Details% that prints out minimal information and %AllFieldInfo% that prints out all original fields but I would like to have %ExtraFieldInfo% that prints out just the fields that %Details% does not output. This way we don't have to print out duplicate field information with both %Details% and %AllFieldInfo% making the file size unnecessarily big.

**Comment by YamatoSecurity** [comment]
@hitenkoku 他のissueを既にやっていると思うので、途中のissueを先にやっても大丈夫です。良いタイミングができたら、これをお願いできますか？
今milestone 3.0になっていますが、これを実装するとファイルサイズがかなり減るので、優先度を上げました。

**Comment by hitenkoku** [comment]
@YamatoSecurity  承りました。時間がかかって申し訳ございません。こちらの方を優先して取り組みます
