### ISSUE TITLE
Hayabusa 2+ shows long underlines in help menu

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#911]
It seems that after updating to Clap 4, Hayabusa prints long underlines in Command Prompt.
I think this is a bug in Clap though so may need to get them to fix upstream.

@hitenkoku What do you think? should we raise an issue to the Clap repository to have them look at it?

![underbar](https://user-images.githubusercontent.com/71482215/217373832-2b654ed9-af8e-4cc6-96e2-a89e6b91d415.png)

**Comment by hitenkoku** [comment]
I checked following enviroments. Underlines didn't show up in my environment...

- PowerShellv5(Windows 11 via terminal app)
- cmd.exe(Windows11 via terminal app)
- PowerShell v7(Windows 11 via terminal app)

**Comment by YamatoSecurity** [comment]
Humm.. from start -> run as command, if you open cmd.exe without using the terminal app, does it also not show?
Maybe this is just a problem with my environment. Btw, using Windows 10

**Comment by hitenkoku** [comment]
Yes,  underlines didn't show up when following way.

> Humm.. from start -> run as command, if you open cmd.exe without using the terminal app, does it also not show?

Sorry, I don't have Windows 10 environment now.
> Maybe this is just a problem with my environment. Btw, using Windows 10

**Comment by fukusuket** [comment]
I have the same issue in the following environment :(

- Windows 10 Home(and Pro) Edition
- PowerShell 7or cmd.exe

It may be a problem that can be reproduced only with Windows 10... 🤔 I will also check the reproduction conditions.

**Comment by fukusuket** [comment]
I found the following same issue in clap repo :)
https://github.com/clap-rs/clap/issues/4431

**Comment by hitenkoku** [comment]
@fukusuket  Thanks for checking!

Since it is difficult to fix as hayabusa, and we need to deal with fixing dependent libraries, we have added a "waiting for dependencies crate update" tag.

**Comment by YamatoSecurity** [comment]
This was fixed in clap 4.1.10
https://github.com/clap-rs/clap/issues/4431#event-8783111003
