### ISSUE TITLE
Enhancement: make channel names shorter in the metrics command

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#923]
When running the `metrics` command, sometimes the channel name is too long and the table overlaps like this:

<img width="1726" alt="Screen Shot 2023-02-16 at 5 00 22 PM" src="https://user-images.githubusercontent.com/71482215/219307368-bf45450e-d385-46a8-9141-26c7abf47aa8.png">

After converting the Channel name abbreviations according to the `channel_abbreviations.txt` file, I would like to make the remaining channel names shorter by abbreviating the following words:

`Microsoft` => `MS`
`Windows` => `Win`
`Operational` => `Op`
`Diagnosis` => `Diag`
`Package` => `Pkg`
`Server` => `Svr`
`Client` => `Cli`
`Management` => `Mgmt`
`Security` => `Sec`
`Connection` => `Conn`
`Application` => `App`

For example, in the screenshot above, `Microsoft-Windows-Diagnosis-PLA/Operational` would become `MS-Win-Diag-PLA/Op`.

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for sending issue.
Could you tell us what you envision for the following questions?

1. This name shorter is only in metrics command?
2. Is These abbrevation defined by external config file? or hardcode?

**Comment by YamatoSecurity** [comment]
Good questions!
1. I was thinking just the metrics command at first, but it would reduce size of the CSV and JSON file so maybe implement it there too if it is not too difficult.
2. I was thinking hardcoding at first, but it will probably need periodic updates so would be better in an external config file under `rules/config/channel_abbreviations_generic.txt`
