### ISSUE TITLE
Architecture/Usage Diagram

### ISSUE THREAD

**Issue by kazuminn** [Yamato-Security/hayabusa#925]
最近アーキテクチャーの本を読んでいたのですが、Hayabusaにそれがあってもいいかと思い、以下のvulsの図を参考にして作ろうかと思っています。（正確には、アーキテクチャー図ではないかもしれませんが。）

https://github.com/future-architect/vuls/blob/master/img/vuls-abstract.png

READMEを見たときにパット視覚的に、より分かりやすくなると思います。

evtxをルールに食わせると、jsonやyamlなどが出てきていろいろできることを視覚的にわかりやすく表現したいです。
細かい機能などはいろいろありますが、それは割愛していこうかと思っています。

ロゴの方は、MacやWindowsなどのロゴを無許可で使うと、法的に？怒られるので、オープンソース以外は、文字で表示しようかと思っています。

ゆっくりやっていきたいと思っていますが、
何か意見が欲しいです。

**Comment by YamatoSecurity** [comment]
ご提案ありがとうございます！readmeがとても長くて、スクリーンショットだけでは素晴らしさが伝わらないという指摘があったので、追加でパッと見て仕組みが分かるようにしたいですね。こちらの方でも考えてみます。

**Comment by YamatoSecurity** [comment]
今度Hayabusaを解説する時に簡単に重要な機能を伝えるための図を作ってみました。
使用例も絵で可視化したいのですが、難しいですね〜。

![Slide1](https://user-images.githubusercontent.com/71482215/219923305-635a782d-55d0-4d80-af54-aabb6730a713.jpeg)
![Slide2](https://user-images.githubusercontent.com/71482215/219923314-5ad92e64-5ebd-4564-901a-c8eb2dc6d1ff.jpeg)
![Slide3](https://user-images.githubusercontent.com/71482215/219923313-ca48a063-9125-4591-9dde-26f78074f862.jpeg)
![Slide4](https://user-images.githubusercontent.com/71482215/219923312-e228b574-982a-425e-a688-a75e15cd3ceb.jpeg)
![Slide5](https://user-images.githubusercontent.com/71482215/219923311-410656f6-3676-4375-8e60-fb22506ce728.jpeg)
![Slide6](https://user-images.githubusercontent.com/71482215/219923309-f8717b5b-cb9c-40f6-b1bf-7ed16b4267c5.jpeg)

**Comment by YamatoSecurity** [comment]
@kazuminn これでどうですか？他に追加したいことありますか？

**Comment by kazuminn** [comment]
@YamatoSecurity jsonとかcsv がロゴのほうがいいかと思いましたが、ロゴがいろいろあるみたいなので、それで良さそうです。
ありがとうございます。
