### ISSUE TITLE
Enhancement: Add first and last timestamp to Results Summary

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#938]
Add the first and last timestamps to Results Summary and HTML report:
Before:
```
Results Summary:

Events with hits / Total events: 19,616 / 47,465 (Data reduction: 27,849 events (58.67%))
```
After:
```
Results Summary:

First timestamp: 2022-06-01 02:55:30.738 +09:00
Last timestamp: 2022-09-25 04:53:50.748 +09:00

Events with hits / Total events: 19,616 / 47,465 (Data reduction: 27,849 events (58.67%))
```
I would like to print the timestamp in the same format as the other timestamps. (according to the Time Format options).

In the HTML report, output the timestamps before `Results Summary` and `Saved alerts and events`.

**Comment by hitenkoku** [comment]
@YamatoSecurity I have the following two questions
1. First timestamp and last timestamp are the information of the detected record?
2. Should the timestamp be displayed before the sparkline display?

**Comment by YamatoSecurity** [comment]
@hitenkoku 
1. based on all records
2. When the sparkline timeline is displayed, let's put it after the timeline and right before `Events with hits / Total events`
