### ISSUE TITLE
Hayabusa stopping on large EVTX with Killed message with no context

### ISSUE THREAD

**Issue by Silentcartographer** [Yamato-Security/hayabusa#946]
**Describe the bug**
Running Hayabusa on various large security EVTX files causes Hayabusa to stop after a period of time with the message "Killed". I can not find any log to explain this. This has been tested on multiple machines and multiple different EVTX files. 

**Step to Reproduce**

1. Get a security evtx file larger than 3GB 
2. Run Hayabusa with default rules and default minimum level 
3. Choose output as either CSV or JSON 
4. Wait for Hayabusa to terminate with the message "Killed"

**Expected behavior**
Hayabusa takes longer to process the file but completes or an error message explaining why the process was killed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18573010/221833878-5b9bc634-0b43-4bd9-acf6-b7ec39e7074a.png)

**Environment (please complete the following information):**

- Ubuntu 22.04.1 LTS
- hayabusa-2.1.0-lin-gnu 

**Additional context**
Tested on different Ubuntu, one container, one VM. Max RAM allocated was 16GB and failure was still present. Monitoring system resources there were no memory issues.

**Comment by YamatoSecurity** [comment]
@Silentcartographer 
Thank you for notifying us about this. We would like to first check if it is due to the evtx library we are using or hayabusa itself. Could you download evtxdump from https://github.com/omerbenamram/evtx/releases and see if you can dump the results on the 3GB+ file?
Example:
`./evtx_dump /path/to/BigEventLog.evtx -o json -f test.json`

**Comment by YamatoSecurity** [comment]
@Silentcartographer 
Actually, since this does not look like a Rust error and more like the OS killing the process, I am guessing it is the OOM(Out Of Memory) killer on linux killing the process due to it using too much memory. You can turn it off with this command: `systemctl disable --now systemd-oomd`
Please let us know if that works for you.

**Comment by Silentcartographer** [comment]
Hi,Thanks for the emails. I was doing some testing and downloaded version 2.2.2 of Hayabusa. This did a successful full run on the file. I note there were numerous memory improvements in the new release, so I suspect your theory was correct and the new version means the OS is not killing the process.Really appreciate the reply and the great work with Hayabusa generally.I am working on an updated dashboard for Opensearch as the ELK one doesn’t import into the latest version of Opensearch.I will share it once I am done.Many Thanks.On 1 Mar 2023, at 01:50, Yamato Security ***@***.***> wrote:﻿
@Silentcartographer
Actually, since this does not look like a Rust error and more like the OS killing the process, I am guessing it is the OOM(Out Of Memory) killer on linux killing the process due to it using too much memory. You can turn it off with this command: systemctl disable --now systemd-oomd
Please let us know if that works for you.

**Comment by YamatoSecurity** [comment]
@Silentcartographer 
Glad that version 2.2.2 works for you. I tried to reproduce the issue on the same Ubuntu version with Hayabusa 2.1.0, but with even only 8GB of memory allocated to the VM I could scan a 5GB+ file as well as a 14GB directory of evtx files without a problem. (although memory did hit about 99% at the very end of the 14GB scan.) I was able to do it without turning off the OOM killer but you may want to try that next time if you get Killed errors again.

Please share the dashboard when you are done. Looking forward to seeing it.
