### ISSUE TITLE
Double quote CSV fields

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#965]
@hitenkoku 
Is it possible to enclose fields in CSV output in double quotes?
For example, instead of:
`2020-05-02 02:55:26.493 +00:00,UZUMAKI-PC.hinokabe.local,Sysmon,10,low,138294,Proc Access,SrcProc: C:\windows\system32\svchost.exe ¦ TgtProc: C:\windows\System32\svchost.exe ¦ SrcUser: n/a ¦ TgtUser: n/a ¦ Access: 0x1000 ¦ SrcPID: 900 ¦ SrcPGUID: {6bbf237a-cafb-5eac-1000-000000000400} ¦ TgtPID: 2092 ¦ TgtPGUID: {6bbf237a-cb97-5eac-6202-000000000400}`
I want to output:
`"2020-05-02 02:55:26.493 +00:00","UZUMAKI-PC.hinokabe.local","Sysmon","10","low","138294","Proc Access","SrcProc: C:\windows\system32\svchost.exe ¦ TgtProc: C:\windows\System32\svchost.exe ¦ SrcUser: n/a ¦ TgtUser: n/a ¦ Access: 0x1000 ¦ SrcPID: 900 ¦ SrcPGUID: {6bbf237a-cafb-5eac-1000-000000000400} ¦ TgtPID: 2092 ¦ TgtPGUID: {6bbf237a-cb97-5eac-6202-000000000400}"`

The reason is the `Details` and especially `AllFieldInfo` field are too long so I want to convert ` ¦ ` to return character but because the strings do not have double quotes, the new characters put the fields on the next row.
Something like this: `cat results.csv | awk '{gsub(/ ¦ /,"\r\n"); print;}' > multi-line-results.csv`

If `results.csv` uses double quotes, we can import with multiple lines like this:
<img width="1322" alt="Screen Shot 2023-03-17 at 5 53 37 PM" src="https://user-images.githubusercontent.com/71482215/225857844-ad71fd32-f426-4232-b447-dccba6ea5aa1.png">

This makes things easier to analyze on normal screens.

**Comment by hitenkoku** [comment]
@YamatoSecurity 
Thank you very much. Let me check a few things.

1. is there no need for an option to make the output like this?

2. what if I have data like this

```` csv
Payload: ixr "http://evil.example.com"
```

I am assuming that with this modification, it would look something like this.
``` csv
"Payload: ixr ""http://evil.example.com""""
```
