### ISSUE TITLE
[bug] `level-tuning` command panics on ver `2.3.1`, `2.3.2`

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#977]
**Describe the bug**
`level-tuning` command panics on 2.3.1, 2,3,2 🤔

I noticed it while running integration test.
https://github.com/Yamato-Security/hayabusa/actions/runs/4490110725/jobs/7896764932

**Step to Reproduce**

```
./hayabusa level-tuning -f ./rules/config/level_tuning.txt
```

**Expected behavior**
level-tuning` command success.

**Actual behavior**
```
fukusuke@fukusukenoAir hayabusa-2.3.2-all-platforms % ./hayabusa-2.3.2-mac-arm level-tuning -f ./rules/config/level_tuning.txt

╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
   by Yamato Security

Start time: 2023/03/22 22:29

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/yaml.rs:297:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Environment**

- OS: macOS
- hayabusa version 2.3.1, 2,3,2 (Does not occur in versions below 2.3.0)

**Comment by YamatoSecurity** [comment]
@hitenkoku @fukusuket Why didn't this failed test show up and block PRs from being merged?

**Comment by hitenkoku** [comment]
@YamatoSecurity The test is created on a per-function basis, and there is no test that executes the target function in the LevelTuning case.

**Comment by fukusuket** [comment]
The reason is that integration tests are manually triggered tests, not commit triggered tests :(

Ideally, it would be better to run it on each commit, but it takes time, so I run it manually.

It might be better to run the integration tests just once before the release🤔

**Comment by YamatoSecurity** [comment]
@fukusuket I see. I will remember to run it before releasing a new version then. Thanks!
