### ISSUE TITLE
Bug in --visualize-timeline in 2.3.3

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#997]
Up to v2.3.2 Hayabusa will show the event frequency timeline as follows:
<img width="1657" alt="Screen Shot 2023-04-11 at 7 47 30 AM" src="https://user-images.githubusercontent.com/71482215/231013341-54a83d5a-03cf-49d3-9f24-5c030626d3d4.png">

However, I think due to the recent 0.5.1 update with the krapslog crate, it now shows the first timestamp in 1970:

<img width="1657" alt="Screen Shot 2023-04-11 at 7 44 08 AM" src="https://user-images.githubusercontent.com/71482215/231013414-9b5e1949-a0d6-4a94-85aa-fdb45562e792.png">

@hitenkoku Can you check this?

I am checking with this command:
`./hayabusa-2.3.3-mac-intel csv-timeline -J -f ./kosen-challenge.json -o hogehoge.csv -T`

**Comment by hitenkoku** [comment]
@YamatoSecurity 

I have also confirmed the subject event.

I changed the version of krapslog crate from 0.5.1 to 0.5.0 and tried to build it, but it compiles 0.5.1.

I checked the changes to the krapslog crate, but v0.5.1 is an update to the crate used, and I did not see any changes that might affect its operation as a library.

Would it be ok to set the krapslog crate to 0.4 for once?

I'd like to submit an issue to krapslog crate to confirm.

**Comment by hitenkoku** [comment]
Perhaps a change in a dependent library caused the process of calculating the frequency to go awry as a result.

**Comment by YamatoSecurity** [comment]
@hitenkoku Yea, it seems like a dependency that we use is causing the problem.
As you mentioned, just specifying `krapslog = 0.5.0` will still use the 0.5.1 version.
I was able to use 0.5.0 by specifying `krapslog = { git = "https://github.com/acj/krapslog-rs.git" , rev = "306b5a7" } ` but the problem does not go away. I think we need to downgrade a dependency in our Cargo.toml.
Do you have any ideas of what crate could effect this?
